function handles=ddb_initializeSWANInput(handles,id,runid,varargin)

ii=strmatch('SWAN',{handles.Model.Name},'exact');

handles.Model(ii).Input.Runid=runid;
handles.Model(ii).Input.MdwFile=[runid '.mdw'];
handles.Model(ii).Input.AttName=handles.Model(ii).Input.Runid;
handles.Model(ii).Input.ProjectName='';
handles.Model(ii).Input.ProjectNumber='';
handles.Model(ii).Input.Description={'','',''};
handles.Model(ii).Input(id).ComputationalGrids={'','',''};
handles.Model(ii).Input(id).GrdFile='';
handles.Model(ii).Input(id).EncFile='';
handles.Model(ii).Input(id).DepFile='';
handles.Model(ii).Input(id).NstFile='';
handles.Model(ii).Input(id).StartDir={''};
handles.Model(ii).Input(id).EndDir={''};
handles.Model(ii).Input(id).NumberDir={''};
handles.Model(ii).Input(id).LowFreq={''};
handles.Model(ii).Input(id).HighFreq={''};
handles.Model(ii).Input(id).NumberFreq={''};
handles.Model(ii).Input(id).GridNested={''};
handles.Model(ii).Input(id).WaterlevelCor={''};
handles.Model(ii).Input(id).Timepoints={'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''};
handles.Model(ii).Input(id).Time={''};
handles.Model(ii).Input(id).WaterLevel={''};
handles.Model(ii).Input(id).Xvelocity={''};
handles.Model(ii).Input(id).Yvelocity={''};
handles.Model(ii).Input(id).Boundaries={'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''};
handles.Model(ii).Input(id).BndName={''};
handles.Model(ii).Input(id).BndDefby={'Orientation','Grid coordinates','XY coordinates'};
handles.Model(ii).Input(id).BndOrient={'North','Northwest','West','Southwest','South','Southeast','East','Northeast'};
handles.Model(ii).Input(id).BndStart1={''};
handles.Model(ii).Input(id).BndStart2={''};
handles.Model(ii).Input(id).BndEnd1={''};
handles.Model(ii).Input(id).BndEnd2={''};
handles.Model(ii).Input(id).Obstacles={'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''};
handles.Model(ii).Input(id).Reflections={'No','Specular','Diffuse'};
handles.Model(ii).Input(id).Refcoef={''};
handles.Model(ii).Input(id).Height={''};
handles.Model(ii).Input(id).Alpha={''};
handles.Model(ii).Input(id).Beta={''};
handles.Model(ii).Input(id).Segments={'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''};
handles.Model(ii).Input(id).Xstart={''};
handles.Model(ii).Input(id).Ystart={''};
handles.Model(ii).Input(id).Xend={''};
handles.Model(ii).Input(id).Yend={''};
handles.Model(ii).Input(id).SpeedW={''};
handles.Model(ii).Input(id).DirectionW={''};
handles.Model(ii).Input(id).WindFile={''};
handles.Model(ii).Input(id).XoriginW={''};
handles.Model(ii).Input(id).YoriginW={''};
handles.Model(ii).Input(id).AngleW={''};
handles.Model(ii).Input(id).XcellsW={''};
handles.Model(ii).Input(id).YcellsW={''};
handles.Model(ii).Input(id).XsizeW={''};
handles.Model(ii).Input(id).YsizeW={''};
handles.Model(ii).Input(id).Generation={'None','1-st generation','2-nd generation','3-rd generation'};
% 
% handles.Model(ii).Input(id).NrObservationPoints=0;
% handles.Model(ii).Input(id).NrOpenBoundaries=0;
% handles.Model(ii).Input(id).NrDryPoints=0;
% handles.Model(ii).Input(id).NrThinDams=0;
% handles.Model(ii).Input(id).NrCrossSections=0;
% handles.Model(ii).Input(id).NrDischarges=0;
% handles.Model(ii).Input(id).NrObservationPoints=0;
% handles.Model(ii).Input(id).NrDrogues=0;
% handles.Model(ii).Input(id).NrAstronomicComponentSets=0;
% handles.Model(ii).Input(id).NrAstro=0;
% handles.Model(ii).Input(id).NrHarmo=0;
% handles.Model(ii).Input(id).NrTime=0;
% handles.Model(ii).Input(id).NrCor=0;
% handles.Model(ii).Input(id).NrHarmonicComponents=2;
% handles.Model(ii).Input(id).HarmonicComponents=[0.0 30.0];
% handles.Model(ii).Input(id).ThdFile='';
% handles.Model(ii).Input(id).CrsFile='';
% handles.Model(ii).Input(id).DroFile='';
% handles.Model(ii).Input(id).IniFile='';
% handles.Model(ii).Input(id).RstId='';
% handles.Model(ii).Input(id).TrimId='';
% handles.Model(ii).Input(id).BndFile='';
% handles.Model(ii).Input(id).BchFile='';
% handles.Model(ii).Input(id).BctFile='';
% handles.Model(ii).Input(id).BcqFile='';
% handles.Model(ii).Input(id).BccFile='';
% handles.Model(ii).Input(id).SedFile='';
% handles.Model(ii).Input(id).MorFile='';
% handles.Model(ii).Input(id).FouFile='';
% handles.Model(ii).Input(id).ObsFile='';
% handles.Model(ii).Input(id).CrsFile='';
% handles.Model(ii).Input(id).RghFile='';
% handles.Model(ii).Input(id).EdyFile=''; 
% handles.Model(ii).Input(id).UniformDepth=10;
% 
if nargin<4
    handles.Model(ii).Input.FlowBedlevel=0;
    handles.Model(ii).Input.FlowWaterlevel=0;
    handles.Model(ii).Input.FlowVelocity=0;
    handles.Model(ii).Input.FlowWind=0;
    handles.Model(ii).Input(id).CompGrid=0;
    handles.Model(ii).Input(id).OtherGrid=0;
    handles.Model(ii).Input(id).MMax=0;
    handles.Model(ii).Input(id).NMax=0;
    handles.Model(ii).Input(id).Circle=0;
    handles.Model(ii).Input(id).Sector=0;    
    handles.Model(ii).Input(id).Uniform=0;
    handles.Model(ii).Input(id).Spacevarying=0;
    handles.Model(ii).Input(id).Parametric=0;
    handles.Model(ii).Input(id).FromFile=0;
    handles.Model(ii).Input(id).Sheet=0;
    handles.Model(ii).Input(id).Dam=0;
    handles.Model(ii).Input(id).Transmcoef=0;
    handles.Model(ii).Input(id).Gravity=9.81;
    handles.Model(ii).Input(id).Waterdensity=1000;
    handles.Model(ii).Input(id).Northwaxis=90;
    handles.Model(ii).Input(id).Mindepth=0.05;
    handles.Model(ii).Input(id).Nautical=0;
    handles.Model(ii).Input(id).Cartesian=0;
    handles.Model(ii).Input(id).None=0;
    handles.Model(ii).Input(id).Activated=0;
    handles.Model(ii).Input(id).Waveenergy=0;
    handles.Model(ii).Input(id).Radiation=0;
    handles.Model(ii).Input(id).UniformW=0;
    handles.Model(ii).Input(id).SpacevaryingW=0;
    handles.Model(ii).Input(id).Asbathy=0;
    handles.Model(ii).Input(id).Tospecify=0;
%     handles.Model(ii).Input(id).BndDefby={'Orientation'};
%     handles.Model(ii).Input(id).BndOrient={'North'};
%     handles.Model(ii).Input(id).BcaFile='';
%     handles.Model(ii).Input(id).CorFile='';
%     handles.Model(ii).Input(id).Latitude=0.0;
%     handles.Model(ii).Input(id).Orientation=0.0;
%     handles.Model(ii).Input(id).KMax=1;
%     handles.Model(ii).Input(id).Depth=[];
%     handles.Model(ii).Input(id).GridX=[];
%     handles.Model(ii).Input(id).GridY=[];
%     handles.Model(ii).Input(id).Thick=100;
%     handles.Model(ii).Input(id).InitialConditions='unif';
%     handles.Model(ii).Input(id).UniformRoughness=1;
%     handles.Model(ii).Input(id).UniformViscosity=1; 
%     handles.Model(ii).Input(id).Zeta0=0.0;
%     handles.Model(ii).Input(id).U0=0.0;
%     handles.Model(ii).Input(id).V0=0.0; 
%     handles.Model(ii).Input(id).ItDate=floor(now);
%     handles.Model(ii).Input(id).StartTime=floor(now);
%     handles.Model(ii).Input(id).StopTime=floor(now)+2;
%     handles.Model(ii).Input(id).TimeStep=1.0;
%     handles.Model(ii).Input(id).MapStartTime=handles.Model(ii).Input(id).StartTime;
%     handles.Model(ii).Input(id).MapStopTime=handles.Model(ii).Input(id).StopTime;
%     handles.Model(ii).Input(id).MapInterval=10;
%     handles.Model(ii).Input(id).ComStartTime=handles.Model(ii).Input(id).StartTime;
%     handles.Model(ii).Input(id).ComStopTime=handles.Model(ii).Input(id).StartTime;
%     handles.Model(ii).Input(id).ComInterval=0;
%     handles.Model(ii).Input(id).HisInterval=5*handles.Model(ii).Input(id).TimeStep;
%     handles.Model(ii).Input(id).RstInterval=0;
%     handles.Model(ii).Input(id).OnlineVisualisation=0;
%     handles.Model(ii).Input(id).OnlineCoupling=0;
%     handles.Model(ii).Input(id).FourierAnalysis=0;
%     handles.Model(ii).Input(id).OnlineWave=0;
%     handles.Model(ii).Input(id).Roller=0;
%     handles.Model(ii).Input(id).SecondarySWAN=0;
%     handles.Model(ii).Input(id).TidalForces=0;
%     handles.Model(ii).Input(id).Dredging=0; 
%     handles.Model(ii).Input(id).Latitude=0.0;
%     handles.Model(ii).Input(id).Orientation=0.0;
%     Sub1  = #    #
%     Sub2  = # CW#
%     Namc1 = #Sediment sand       #
%     Commnt=
%     Wnsvwp= #N#
%     Wndint= #Y#
%     handles.Model(ii).Input(id).G=9.81;
%     handles.Model(ii).Input(id).RhoW=1000.0;
%     Alph0 = [.]
%     handles.Model(ii).Input(id).TempW=15;
%     handles.Model(ii).Input(id).SalW=31;
%     handles.Model(ii).Input(id).RouWav='FR84';
%     handles.Model(ii).Input(id).WindStress=[6.3000000e-004  0.0000000e+000  7.2300000e-003  3.0000000e+001];
%     handles.Model(ii).Input(id).RhoAir=1.0;
%     handles.Model(ii).Input(id).BetaC=0.5;
%     handles.Model(ii).Input(id).Equili=0;
%     handles.Model(ii).Input(id).VerticalTurbulenceModel='            ';
%     handles.Model(ii).Input(id).KTemp=0;
%     handles.Model(ii).Input(id).FClou=0;
%     handles.Model(ii).Input(id).SArea=0;
%     handles.Model(ii).Input(id).Temint=0;
%     handles.Model(ii).Input(id).RoughnessType='C';
%     handles.Model(ii).Input(id).URoughness=65;
%     handles.Model(ii).Input(id).VRoughness=65;
%     handles.Model(ii).Input(id).Xlo=0;
%     handles.Model(ii).Input(id).VicoUV=1;
%     handles.Model(ii).Input(id).DicoUV=1;
%     handles.Model(ii).Input(id).HLES=0;
%     handles.Model(ii).Input(id).VicoWW=1.0e-6;
%     handles.Model(ii).Input(id).DicoWW=1.0e-6;
%     handles.Model(ii).Input(id).Irov=0;
%     handles.Model(ii).Input(id).Z0v=0.0;
%     handles.Model(ii).Input(id).SedFile='';
%     handles.Model(ii).Input(id).MorFile='';
%     handles.Model(ii).Input(id).Iter=0;
%     handles.Model(ii).Input(id).DryFlp=1;
%     handles.Model(ii).Input(id).DpsOpt='MAX';
%     handles.Model(ii).Input(id).DpuOpt='MEAN';
%     handles.Model(ii).Input(id).DryFlc=0.1;
%     handles.Model(ii).Input(id).Dco=-999.0;
%     handles.Model(ii).Input(id).SmoothingTime=60.0;
%     handles.Model(ii).Input(id).ThetQH=0;
%     handles.Model(ii).Input(id).ForresterHor=0;
%     handles.Model(ii).Input(id).ForresterVer=0;
%     handles.Model(ii).Input(id).SigmaCorrection=0;
%     handles.Model(ii).Input(id).TraSol='Cyclic-method';
%     handles.Model(ii).Input(id).MomSol='';
%     handles.Model(ii).Input(id).OnlineVisualisation=0;
%     handles.Model(ii).Input(id).WaqMod=0;
%     handles.Model(ii).Input(id).WaveOnline=0;
%     snelli= #no#
%     Cstbnd= #yes#
%     Roller= #yes#
%     Commnt=
%     Gamdis= 0.7
%     betaro= 0.05
%     F_lam = -2.0
%     Thr   = 0.01
%     TraFrm= #vrijn2004.frm#
%     Trtrou= #Y#
%     Trtdef= #vrijn04.trt#
%     Trtu  = #trtuv.inp#
%     Trtv  = #trtuv.inp#
%     TrtDt = 2.
end

