function ax=absaxes(fig,cmposll,alfdeg,cmsize,xlim,ylim);
% ABSAXES create a axes with an absolute paper position
%   by setting the lowerleft corner, rotation, size,
%   xlim, and ylim
%
%   NewAxesHandle=absaxes(FigureHandle,CmPositionLowerLeft, ...
%                         AngleDeg,CmSize,XLim,YLim)

cmpos=[cmposll cmsize];
alfrad=alfdeg*pi/180;

punit=get(fig,'paperunits');
set(fig,'paperunits','centimeters');
ppos=get(fig,'paperposition');
set(fig,'paperunits',punit);

pos=ones(1,4);
pos(1:2)=cmposll./ppos(3:4);
pos(1:2)=pos(1:2)-.5;

PhysSize=min(ppos(3:4)); % physical size of the restrictive dimension
                         % for A4 portrait ppos(3); for A4 landscape ppos(4)

dar=[(xlim(2)-xlim(1))/cmsize(1)*PhysSize (ylim(2)-ylim(1))/cmsize(2)*PhysSize 1];
cuv=[sin(alfrad) cos(alfrad) 0].*dar;
cuv=cuv/norm(cuv);
ax=axes('parent',fig, ...
       'cameraviewangle',1, ...
       'cameraposition',[xlim(1) ylim(1) 180/pi], ...
       'cameratarget',[xlim(1) ylim(1) 0], ...
       'cameraupvector',cuv, ...
       'xlim',xlim, ...
       'ylim',ylim, ...
       'units','normalized', ...
       'position', pos, ...
       'dataaspectratio',dar, ...
       'plotboxaspectratiomode','auto', ...
       'projection','orthographic', ...
       'visible','on');
