function handles=ddb_initializeDelft3DWAVEInput(handles,id,runid,varargin)

ii=strmatch('Delft3DWAVE',{handles.Model.name},'exact');

handles.Model(ii).Input.ActiveDomain       = 1;
handles.Model(ii).Input.Runid              =  runid;
handles.Model(ii).Input.ItDate             =  floor(now);
handles.Model(ii).Input.StartTime          =  floor(now);
handles.Model(ii).Input.StopTime           =  floor(now)+2;
handles.Model(ii).Input.TimeStep           =  1.0;
handles.Model(ii).Input.AttName            =  handles.Model(ii).Input.Runid;
handles.Model(ii).Input.MdwFile            =  [runid '.mdw'];
				             
handles.Model(ii).Input.ProjectName        = '';
handles.Model(ii).Input.ProjectNumber      = '';
handles.Model(ii).Input.Description        = {'','',''};
				             
handles.Model(ii).Input.FlowBedLevel       = 0;
handles.Model(ii).Input.FlowWaterLevel     = 0;
handles.Model(ii).Input.FlowVelocity       = 0;
handles.Model(ii).Input.FlowWind           = 0;
handles.Model(ii).Input.MDFFile            = '';
handles.Model(ii).Input.AvailableFlowTimes = '';

handles.Model(ii).Input.ComputationalGrids={''};
handles.Model(ii).Input.Domain(id).PathnameComputationalGrids='';
handles.Model(ii).Input.Domain(id).Coordsyst = '';
handles.Model(ii).Input.Domain(id).GrdFile   = 'testing';
handles.Model(ii).Input.Domain(id).EncFile   = '';
handles.Model(ii).Input.Domain(id).DepFile   = '';
handles.Model(ii).Input.Domain(id).NstGrid   = '';
handles.Model(ii).Input.Domain(id).MMax      = '';
handles.Model(ii).Input.Domain(id).NMax      = '';
%% grid
handles.Model(ii).Input.Domain(id).CompGrid  = '';
handles.Model(ii).Input.Domain(id).OtherGrid = '';
handles.Model(ii).Input.Domain(id).CompDep   = '';
handles.Model(ii).Input.Domain(id).Xorig     = '';
handles.Model(ii).Input.Domain(id).Yorig     = '';
handles.Model(ii).Input.Domain(id).Xgridsize = '';
handles.Model(ii).Input.Domain(id).Ygridsize = '';
%% fre + dir
handles.Model(ii).Input.Domain(id).Circle     = 1;
handles.Model(ii).Input.Domain(id).Sector     = 0;    
handles.Model(ii).Input.Domain(id).StartDir   = '';
handles.Model(ii).Input.Domain(id).EndDir     = '';
handles.Model(ii).Input.Domain(id).NumberDir  = 36;
handles.Model(ii).Input.Domain(id).LowFreq    = 0.05;
handles.Model(ii).Input.Domain(id).HighFreq   = 1;
handles.Model(ii).Input.Domain(id).NumberFreq = 24;

handles.Model(ii).Input.Domain(id).GridNested = '';
handles.Model(ii).Input.Domain(id).NestedValue= '';

handles.Model(ii).Input.WaterlevelCor=0;
handles.Model(ii).Input.Timepoints={''};
handles.Model(ii).Input.Time={''};
handles.Model(ii).Input.WaterLevel={''};
handles.Model(ii).Input.Xvelocity={''};
handles.Model(ii).Input.Yvelocity={''};
handles.Model(ii).Input.TimeTemp='';
handles.Model(ii).Input.WaterLevelTemp='';
handles.Model(ii).Input.XvelocityTemp='';
handles.Model(ii).Input.YvelocityTemp='';
handles.Model(ii).Input.TimepointsIval='';
handles.Model(ii).Input.TimeDependentQuantitiesFile='';
handles.Model(ii).Input.NumberQuantities='';

handles.Model(ii).Input.Boundaries='';
handles.Model(ii).Input.Uniform='';
handles.Model(ii).Input.Spacevarying='';
handles.Model(ii).Input.Parametric='';
handles.Model(ii).Input.FromFile='';
handles.Model(ii).Input.BndName='';
handles.Model(ii).Input.BndDefby={'Orientation';'Grid coordinates';'XY coordinates'};
handles.Model(ii).Input.BndOrient={'North';'Northwest';'West';'Southwest';'South';'Southeast';'East';'Northeast'};
handles.Model(ii).Input.BndDefbyval='';
handles.Model(ii).Input.BndOrientval='';
handles.Model(ii).Input.BndStart1='';
handles.Model(ii).Input.BndStart2='';
handles.Model(ii).Input.BndEnd1='';
handles.Model(ii).Input.BndEnd2='';
handles.Model(ii).Input.UniformTemp=0;
handles.Model(ii).Input.SpacevaryingTemp=0;
handles.Model(ii).Input.ParametricTemp=0;
handles.Model(ii).Input.FromFileTemp=0;
handles.Model(ii).Input.BndNameTemp=0;
handles.Model(ii).Input.BndDefbyTemp=1;
handles.Model(ii).Input.BndOrientTemp=1;
handles.Model(ii).Input.BndStart1Temp=0;
handles.Model(ii).Input.BndStart2Temp=0;
handles.Model(ii).Input.BndEnd1Temp=0;
handles.Model(ii).Input.BndEnd2Temp=0;
handles.Model(ii).Input.BoundariesIval='';

handles.Model(ii).Input.Hs='';
handles.Model(ii).Input.Tp='';
handles.Model(ii).Input.Dir='';
handles.Model(ii).Input.Spread='';
handles.Model(ii).Input.DistTemp=0;
handles.Model(ii).Input.HsTemp=0;
handles.Model(ii).Input.TpTemp=0;
handles.Model(ii).Input.DirTemp=0;
handles.Model(ii).Input.SpreadTemp=0;
handles.Model(ii).Input.ClockTemp=1;
handles.Model(ii).Input.CounterClockTemp=0;
handles.Model(ii).Input.BndFileTemp='';
handles.Model(ii).Input.Sections='';
handles.Model(ii).Input.SectionsIval='';
handles.Model(ii).Input.SecOrient='';
handles.Model(ii).Input.SecDist='';
handles.Model(ii).Input.SecHs='';
handles.Model(ii).Input.SecTp='';
handles.Model(ii).Input.SecDir='';
handles.Model(ii).Input.SecSpread='';
handles.Model(ii).Input.BndFile='';
handles.Model(ii).Input.SpacevaryingParam(id).Sections='';
handles.Model(ii).Input.SpacevaryingParam(id).Dist='';
handles.Model(ii).Input.SpacevaryingParam(id).Hs='';
handles.Model(ii).Input.SpacevaryingParam(id).Tp='';
handles.Model(ii).Input.SpacevaryingParam(id).Dir='';
handles.Model(ii).Input.SpacevaryingParam(id).Spread='';
handles.Model(ii).Input.SpacevaryingParam(id).Clock='';
handles.Model(ii).Input.SpacevaryingParam(id).CounterClock='';
handles.Model(ii).Input.SpacevaryingParam(id).BndFile='';

handles.Model(ii).Input.Jonswap ='';
handles.Model(ii).Input.Jonswapval='';
handles.Model(ii).Input.Pierson ='';
handles.Model(ii).Input.Gauss   ='';
handles.Model(ii).Input.Gaussval='';
handles.Model(ii).Input.Peak    ='';
handles.Model(ii).Input.Mean    ='';
handles.Model(ii).Input.Cosine  ='';
handles.Model(ii).Input.Degrees ='';
handles.Model(ii).Input.JonswapTemp=1;
handles.Model(ii).Input.JonswapvalTemp=3.3;
handles.Model(ii).Input.PiersonTemp=0;
handles.Model(ii).Input.GaussTemp  =0;
handles.Model(ii).Input.GaussvalTemp=0.01;
handles.Model(ii).Input.PeakTemp   =1;
handles.Model(ii).Input.MeanTemp   =0;
handles.Model(ii).Input.CosineTemp =1;
handles.Model(ii).Input.DegreesTemp=0;

handles.Model(ii).Input.Obstacles='';
handles.Model(ii).Input.ObstaclesIval='';
handles.Model(ii).Input.Sheet=1;
handles.Model(ii).Input.Dam=0;
handles.Model(ii).Input.Reflections={'No';'Specular';'Diffuse'};
handles.Model(ii).Input.Reflectionsval=1;
handles.Model(ii).Input.Refcoef=0;
handles.Model(ii).Input.Transmcoef=1;
handles.Model(ii).Input.Height=0;
handles.Model(ii).Input.Alpha=2.6;
handles.Model(ii).Input.Beta=0.15;
handles.Model(ii).Input.ObstaclesNb(id).Segments='';
handles.Model(ii).Input.ObstaclesNb(id).SegmentsIval='';
handles.Model(ii).Input.ObstaclesNb(id).Xstart=0;
handles.Model(ii).Input.ObstaclesNb(id).Ystart=0;
handles.Model(ii).Input.ObstaclesNb(id).Xend=0;
handles.Model(ii).Input.ObstaclesNb(id).Yend=0;
handles.Model(ii).Input.PolFile='';

handles.Model(ii).Input.Gravity        = 9.81;
handles.Model(ii).Input.Waterdensity   = 1000;
handles.Model(ii).Input.Northwaxis     = 90;
handles.Model(ii).Input.Mindepth       = 0.05;
handles.Model(ii).Input.Nautical       = 0;
handles.Model(ii).Input.Cartesian      = 0;
handles.Model(ii).Input.None           = 0;
handles.Model(ii).Input.Activated      = 0;
handles.Model(ii).Input.Waveenergy     = 0;
handles.Model(ii).Input.Radiation      = 0;
handles.Model(ii).Input.UniformW       = 1;
handles.Model(ii).Input.SpacevaryingW  = 0;
handles.Model(ii).Input.Asbathy        = 0;
handles.Model(ii).Input.Tospecify      = 0;
handles.Model(ii).Input.SpeedW         = '';
handles.Model(ii).Input.DirectionW     = '';
handles.Model(ii).Input.WindFile       = '';
handles.Model(ii).Input.XoriginW       = '';
handles.Model(ii).Input.YoriginW       = '';
handles.Model(ii).Input.AngleW         = '';
handles.Model(ii).Input.XcellsW        = '';
handles.Model(ii).Input.YcellsW        = '';
handles.Model(ii).Input.XsizeW         = '';
handles.Model(ii).Input.YsizeW         = '';
handles.Model(ii).Input.Generation     = {'None';'1-st generation';'2-nd generation';'3-rd generation'};
handles.Model(ii).Input.GenerationIval = 4;

handles.Model(ii).Input.Breaking    = 1;
handles.Model(ii).Input.Triad       = 0;
handles.Model(ii).Input.Friction    = 1;
handles.Model(ii).Input.Diffraction = 0;
handles.Model(ii).Input.Alpha1      = 1;
handles.Model(ii).Input.Gamma       = 0.8;
handles.Model(ii).Input.Alpha2      = 0.1;
handles.Model(ii).Input.Beta        = 2.2;
handles.Model(ii).Input.Type        = {'JONSWAP';'Collins';'Madsen et al.'};
handles.Model(ii).Input.Typeval     = 1;
handles.Model(ii).Input.Coefficient = 0.067;
handles.Model(ii).Input.Smoothcoef  = 0.2;
handles.Model(ii).Input.Smoothsteps = 5;
handles.Model(ii).Input.Propagation = 1;

handles.Model(ii).Input.Acti1   = 0;
handles.Model(ii).Input.DeActi1 = 1;
handles.Model(ii).Input.Acti2   = 1;
handles.Model(ii).Input.DeActi2 = 0;
handles.Model(ii).Input.Acti3   = 0;
handles.Model(ii).Input.DeActi3 = 1;
handles.Model(ii).Input.Acti4   = 1;
handles.Model(ii).Input.DeActi4 = 0;
handles.Model(ii).Input.Acti5   = 1;
handles.Model(ii).Input.DeActi5 = 0;

handles.Model(ii).Input.First = 1;
handles.Model(ii).Input.Third = 0;
handles.Model(ii).Input.CDD   = 0.5;
handles.Model(ii).Input.CSS   = 0.5;

handles.Model(ii).Input.HSTM01   = 0.02;
handles.Model(ii).Input.HSchange = 0.02;
handles.Model(ii).Input.TM01     = 0.02;
handles.Model(ii).Input.PercWet  = 98;
handles.Model(ii).Input.MaxIter  = 15;

handles.Model(ii).Input.TestOutput=0;
handles.Model(ii).Input.Debug=0;
handles.Model(ii).Input.TimeStepOutput=10;
handles.Model(ii).Input.Interval=10;
handles.Model(ii).Input.Mode={'stationnary';'quasi-stationary';'non-stationnary'};
handles.Model(ii).Input.ModeIval=1;
handles.Model(ii).Input.Hotstart=0;
handles.Model(ii).Input.Verify=0;
handles.Model(ii).Input.OutputFlowGrid=0;
handles.Model(ii).Input.OutputFlowGridFile='';
handles.Model(ii).Input.Compgrid1=1;
handles.Model(ii).Input.Compgrid2=0;
handles.Model(ii).Input.Compgrid3=0;
handles.Model(ii).Input.OutputSpecific=0;
handles.Model(ii).Input.Table=0;
handles.Model(ii).Input.oneDspectra=0;
handles.Model(ii).Input.twoDspectra=0;
handles.Model(ii).Input.LocFromFile=1;
handles.Model(ii).Input.LocFileName='';
handles.Model(ii).Input.LocSpecified=0;
handles.Model(ii).Input.Locations='';
handles.Model(ii).Input.LocationsIval='';
handles.Model(ii).Input.LocXTemp=0;
handles.Model(ii).Input.LocYTemp=0;
handles.Model(ii).Input.LocX=0;
handles.Model(ii).Input.LocY=0;






