function h = XBRV_initiate_h
%XBRV_INITIATE_H  One line description goes here.
%
%   More detailed description goes here.
%
%   Syntax:
%   h = XBRV_initiate_h
%
%   Input:

%
%   Output:
%   h =
%
%   Example
%   XBRV_initiate_h
%
%   See also 

%% Copyright notice
%   --------------------------------------------------------------------
%   Copyright (C) 2009 Deltares
%       Kees den Heijer
%
%       Kees.denHeijer@Deltares.nl	
%
%       Deltares
%       P.O. Box 177
%       2600 MH Delft
%       The Netherlands
%
%   This library is free software: you can redistribute it and/or
%   modify it under the terms of the GNU Lesser General Public
%   License as published by the Free Software Foundation, either
%   version 2.1 of the License, or (at your option) any later version.
%
%   This library is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%   Lesser General Public License for more details.
%
%   You should have received a copy of the GNU Lesser General Public
%   License along with this library. If not, see <http://www.gnu.org/licenses/>.
%   --------------------------------------------------------------------

% This tool is part of <a href="http://OpenEarth.nl">OpenEarthTools</a>.
% OpenEarthTools is an online collaboration to share and manage data and 
% programming tools in an open source, version controlled environment.
% Sign up to recieve regular updates of this function, and to contribute 
% your own tools.

%% Version <http://svnbook.red-bean.com/en/1.5/svn.advanced.props.special.keywords.html>
% Created: 27 Nov 2009
% Created with Matlab version: 7.7.0.471 (R2008b)

% $Id$
% $Date$
% $Author$
% $Revision$
% $HeadURL$
% $Keywords: $

%%
h = struct(...
    'fig',[],...
    'menu',[],...
    'dirbutton',[],...
    'dirfield',[],...
    'instpanel',[],...
    'contrpanel',[],...
    'control',[],...
    'plotspec',[],...
    'plothan',[],...
    'plotax',[],...
    'infoax',[]);

h.menu = struct(...
    'File',[],...
    'Datasets',[],...
    'Help',[]);

h.menu.File = struct('Main',[],...
    'NewProject',[],...
    'LoadProject',[],...
    'SaveProject',[],...
    'Close',[]);

h.menu.Datasets = struct('Main',[],...
    'LoadSet',[],...
    'SaveSet',[],...
    'RemoveSet',[],...
    'Sets',[]);

h.menu.Help = struct('Main',[],...
    'About',[]);

h.control = struct(...
    'rew',[],...
    'stop',[],...
    'startpause',[],...
    'forw',[],...
    'slider',[]);

h.plotspec = struct(...
    'currentdataset',1,...
    'ddd',false,...
    'nyid',2,...
    'dt',0.01,...
    'dframes',1,...
    'hrmson',true,...
    'nthin',30,...
    'thin',1,...
    'WaterColor',[140 175 245]/255,...
    'WaterEdgeColor','b',...
    'SedimentColor',[245 210 130]/255,...
    'SedimentEdgeColor','k',...
    'LineStyle','none',...
    'HrmsMarker','o',...
    'HrmsEdgeColor','r',...
    'HrmsEdgeWidth',2,...
    'HrmsFaceColor','w',...
    'xlim',[],...
    'ylim',[],...
    'zlim',[]);

h.plothan = struct(...
    'plotspec',[],...
    'hrmsleg',[],...
    'hleg',[],...
    'legnames',[],...
    'hpb',[],...
    'hpw',[],...
    'hpwleg',[],...
    'hpbleg',[],...
    'hb',[],...
    'hw',[],...
    'hrms1',[],...
    'hrms2',[]);

h.plothan.plotspec = struct(...
    'currentdataset',1,...
    'ddd',false,...
    'nyid',2,...
    'dt',0.01,...
    'dframes',1,...
    'hrmson',true,...
    'nthin',30,...
    'WaterColor',[140 175 245]/255,...
    'WaterEdgeColor','b',...
    'SedimentColor',[245 210 130]/255,...
    'SedimentEdgeColor','k',...
    'LineStyle','none',...
    'HrmsMarker','o',...
    'HrmsEdgeColor','r',...
    'HrmsEdgeWidth',2,...
    'HrmsFaceColor','w',...
    'xlim',[],...
    'ylim',[],...
    'zlim',[]);