//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BwnMatLabTest.Bwn {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Bwn.BwnFunctionsWrapperSoap")]
    public interface BwnFunctionsWrapperSoap {
        
        // CODEGEN: Generating message contract since element name ncFilePath from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterpolateToLine", ReplyAction="*")]
        BwnMatLabTest.Bwn.InterpolateToLineResponse InterpolateToLine(BwnMatLabTest.Bwn.InterpolateToLineRequest request);
        
        // CODEGEN: Generating message contract since element name ncFilePath from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlotTimeSeries", ReplyAction="*")]
        BwnMatLabTest.Bwn.PlotTimeSeriesResponse PlotTimeSeries(BwnMatLabTest.Bwn.PlotTimeSeriesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InterpolateToLineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InterpolateToLine", Namespace="http://tempuri.org/", Order=0)]
        public BwnMatLabTest.Bwn.InterpolateToLineRequestBody Body;
        
        public InterpolateToLineRequest() {
        }
        
        public InterpolateToLineRequest(BwnMatLabTest.Bwn.InterpolateToLineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InterpolateToLineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ncFilePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ncVariableName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double centreLatitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double centreLongitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double vertexLatitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double vertexLongitude;
        
        public InterpolateToLineRequestBody() {
        }
        
        public InterpolateToLineRequestBody(string ncFilePath, string ncVariableName, double centreLatitude, double centreLongitude, double vertexLatitude, double vertexLongitude) {
            this.ncFilePath = ncFilePath;
            this.ncVariableName = ncVariableName;
            this.centreLatitude = centreLatitude;
            this.centreLongitude = centreLongitude;
            this.vertexLatitude = vertexLatitude;
            this.vertexLongitude = vertexLongitude;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InterpolateToLineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InterpolateToLineResponse", Namespace="http://tempuri.org/", Order=0)]
        public BwnMatLabTest.Bwn.InterpolateToLineResponseBody Body;
        
        public InterpolateToLineResponse() {
        }
        
        public InterpolateToLineResponse(BwnMatLabTest.Bwn.InterpolateToLineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InterpolateToLineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InterpolateToLineResult;
        
        public InterpolateToLineResponseBody() {
        }
        
        public InterpolateToLineResponseBody(string InterpolateToLineResult) {
            this.InterpolateToLineResult = InterpolateToLineResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlotTimeSeriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlotTimeSeries", Namespace="http://tempuri.org/", Order=0)]
        public BwnMatLabTest.Bwn.PlotTimeSeriesRequestBody Body;
        
        public PlotTimeSeriesRequest() {
        }
        
        public PlotTimeSeriesRequest(BwnMatLabTest.Bwn.PlotTimeSeriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlotTimeSeriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ncFilePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ncVariableName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string startTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string stopTime;
        
        public PlotTimeSeriesRequestBody() {
        }
        
        public PlotTimeSeriesRequestBody(string ncFilePath, string ncVariableName, string startTime, string stopTime) {
            this.ncFilePath = ncFilePath;
            this.ncVariableName = ncVariableName;
            this.startTime = startTime;
            this.stopTime = stopTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlotTimeSeriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlotTimeSeriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BwnMatLabTest.Bwn.PlotTimeSeriesResponseBody Body;
        
        public PlotTimeSeriesResponse() {
        }
        
        public PlotTimeSeriesResponse(BwnMatLabTest.Bwn.PlotTimeSeriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlotTimeSeriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PlotTimeSeriesResult;
        
        public PlotTimeSeriesResponseBody() {
        }
        
        public PlotTimeSeriesResponseBody(string PlotTimeSeriesResult) {
            this.PlotTimeSeriesResult = PlotTimeSeriesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface BwnFunctionsWrapperSoapChannel : BwnMatLabTest.Bwn.BwnFunctionsWrapperSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class BwnFunctionsWrapperSoapClient : System.ServiceModel.ClientBase<BwnMatLabTest.Bwn.BwnFunctionsWrapperSoap>, BwnMatLabTest.Bwn.BwnFunctionsWrapperSoap {
        
        public BwnFunctionsWrapperSoapClient() {
        }
        
        public BwnFunctionsWrapperSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BwnFunctionsWrapperSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BwnFunctionsWrapperSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BwnFunctionsWrapperSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BwnMatLabTest.Bwn.InterpolateToLineResponse BwnMatLabTest.Bwn.BwnFunctionsWrapperSoap.InterpolateToLine(BwnMatLabTest.Bwn.InterpolateToLineRequest request) {
            return base.Channel.InterpolateToLine(request);
        }
        
        public string InterpolateToLine(string ncFilePath, string ncVariableName, double centreLatitude, double centreLongitude, double vertexLatitude, double vertexLongitude) {
            BwnMatLabTest.Bwn.InterpolateToLineRequest inValue = new BwnMatLabTest.Bwn.InterpolateToLineRequest();
            inValue.Body = new BwnMatLabTest.Bwn.InterpolateToLineRequestBody();
            inValue.Body.ncFilePath = ncFilePath;
            inValue.Body.ncVariableName = ncVariableName;
            inValue.Body.centreLatitude = centreLatitude;
            inValue.Body.centreLongitude = centreLongitude;
            inValue.Body.vertexLatitude = vertexLatitude;
            inValue.Body.vertexLongitude = vertexLongitude;
            BwnMatLabTest.Bwn.InterpolateToLineResponse retVal = ((BwnMatLabTest.Bwn.BwnFunctionsWrapperSoap)(this)).InterpolateToLine(inValue);
            return retVal.Body.InterpolateToLineResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BwnMatLabTest.Bwn.PlotTimeSeriesResponse BwnMatLabTest.Bwn.BwnFunctionsWrapperSoap.PlotTimeSeries(BwnMatLabTest.Bwn.PlotTimeSeriesRequest request) {
            return base.Channel.PlotTimeSeries(request);
        }
        
        public string PlotTimeSeries(string ncFilePath, string ncVariableName, string startTime, string stopTime) {
            BwnMatLabTest.Bwn.PlotTimeSeriesRequest inValue = new BwnMatLabTest.Bwn.PlotTimeSeriesRequest();
            inValue.Body = new BwnMatLabTest.Bwn.PlotTimeSeriesRequestBody();
            inValue.Body.ncFilePath = ncFilePath;
            inValue.Body.ncVariableName = ncVariableName;
            inValue.Body.startTime = startTime;
            inValue.Body.stopTime = stopTime;
            BwnMatLabTest.Bwn.PlotTimeSeriesResponse retVal = ((BwnMatLabTest.Bwn.BwnFunctionsWrapperSoap)(this)).PlotTimeSeries(inValue);
            return retVal.Body.PlotTimeSeriesResult;
        }
    }
}
