function [AuthorizedOptions] = authoptions( filename )


switch filename

    case {'ge_axes' }
        
        AuthorizedOptions = {'altitudeMode',...
                             'axesOrigin',...
                             'axesType',...
                             'hAxisLength',...
                             'hLineColor',...
                             'hTick',...
                             'lineColor',...
                             'lineWidth',...
                             'msgToScreen',...
                             'xTick',...                    
                             'xyLineColor',...
                             'xzLineColor',...
                             'yTick',...
                             'yzLineColor',...
                             'zTick'};
                 
    case {'ge_barbdaes' }

        AuthorizedOptions = {'barbAlpha',...
                             'barbColor',...
                             'daeDir',...
                             'msgToScreen'};
               
    case {'ge_box' }
        
        AuthorizedOptions = {'altitude',...
                             'altitudeMode',...
                             'description',...
                             'extrude',...
                             'lineColor',...
                             'lineWidth',...
                             'msgToScreen',...
                             'name',...
                             'polyColor',...
                             'snippet',...
                             'tessellate',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'visibility'};
    case {'ge_circle' }
        
        AuthorizedOptions = {'altitude',...
                             'altitudeMode',...
                             'description',...
                             'divisions',...
                             'lineColor',...
                             'lineWidth',...
                             'msgToScreen',...
                             'name',...
                             'nameVisibility',...
                             'polyColor',...
                             'snippet',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'visibility'};
                 
    case {'ge_colorbar' }
        
        AuthorizedOptions = {'altitude',...
                             'altitudeMode',...
                             'cBarBorderWidth',...
                             'cBarFormatStr',...
                             'cLimHigh',...
                             'cLimLow',...
                             'cMap',...
                             'extrude',... 
                             'labels',...
                             'msgToScreen',...      
                             'name',...
                             'nanValue',...
                             'numUnits',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'visibility'};
               
    case {'ge_contour' }
        
        AuthorizedOptions = {'altitude',...
                             'altitudeMode',...
                             'cLimHigh',...
                             'cLimLow',...
                             'cMap',...
                             'description',...
                             'extrude',...
                             'forceAsLine',...
                             'lineColor',...
                             'lineWidth',...
                             'lineValues',...
                             'msgToScreen',...
                             'numLevels',...
                             'name',...
                             'snippet',...
                             'tessellate',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'visibility'};

    case {'ge_contourf','ge_contourf_old'}
        
        AuthorizedOptions = {'altitude',...
                             'altitudeMode',...
                             'cLimHigh',...
                             'cLimLow',...
                             'cMap',...
                             'description',...
                             'extrude',...
                             'autoClose',...
                             'lineColor',...
                             'lineWidth',...
                             'lineValues',...
                             'msgToScreen',...
                             'nearInf',...
                             'name',...
                             'numLevels',...
                             'snippet',...
                             'tessellate',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'tinyRes',...
                             'visibility',...
                             'polyAlpha'};
                         
    case {'ge_cylinder' }
        
        AuthorizedOptions = {'description',...
                             'divisions',...
                             'lineColor',...
                             'lineWidth',...
                             'msgToScreen',...
                             'name',...
                             'polyColor',...
                             'snippet',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'visibility'};
                 
    case {'ge_gplot' }
        
        AuthorizedOptions = {'altitude',...
                             'altitudeMode',...
                             'description',...
                             'extrude',...
                             'forceAsLine',...
                             'lineColor',...
                             'lineWidth',...
                             'msgToScreen',...                     
                             'name',...
                             'snippet',...
                             'tessellate',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'visibility'};

    case {'ge_grid' }
        
        AuthorizedOptions = {'altitude', ...
                             'altitudeMode', ...
                             'description', ...
                             'extrude', ...
                             'lineWidth', ...
                             'lineColor', ...
                             'latRes', ...
                             'lonRes', ...
                             'name',...
                             'polyColor', ...
                             'snippet', ...
                             'timeStamp', ...
                             'timeSpanStart', ...
                             'timeSpanStop',...
                             'visibility'};

    case {'ge_groundoverlay' }
        
        AuthorizedOptions = {'altitude',...
                             'altitudeMode',...
                             'color',...
                             'description',...
                             'extrude',...
                             'imageURL',...
                             'msgToScreen',...
                             'name',...
                             'polyAlpha',...
                             'rotation',...
                             'snippet',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'viewBoundScale',...
                             'visibility'};
                 
    case {'ge_imagesc' }
        
        AuthorizedOptions = {'altitude',...    
                             'altitudeMode',...
                             'cLimHigh',...
                             'cLimLow',...
                             'cMap',...
                             'dataFormatStr',...
                             'description',...
                             'extrude',...
                             'imageURL',...
                             'lineColor',...
                             'lineWidth',...
                             'msgToScreen',...
                             'name',...
                             'nanValue',...
                             'polyAlpha',...
                             'snippet',...
                             'tessellate',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'visibility',...
                             'xResolution',...
                             'yResolution'};
                 
    case {'ge_kml' }
        
        AuthorizedOptions = {'name',...
                             'msgToScreen',...
                             'resourceURLs',...
                             'kmlTargetDir',...
                             'tmpDir'};
          
    case {'ge_kmz' }
        
        AuthorizedOptions = {'msgToScreen',...
                             'resourceURLs',...
                             'kmzTargetDir',...
                             'tmpDir'};

    case {'ge_output' }
        
        AuthorizedOptions = {'msgToScreen',...
                             'name'};
   case {'ge_overlay'}
       
        AuthorizedOptions = {'color',...
                             'id',...
                             'name',...
                             'visibility',...
                             'snippet',...
                             'description',...
                             'drawOrder',...
                             'x',...
                             'y',...
                             'xunits',...
                             'yunits',...
                             'rotation',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'xSize',...
                             'ySize',...
                             'xSizeUnits',...
                             'ySizeUnits',...
                             'visibility'};
                         
    case {'ge_plot3' }
        
        AuthorizedOptions = {'altitudeMode',...
                             'description',...
                             'extrude',...
                             'forceAsLine',...
                             'lineColor',...
                             'lineWidth',...
                             'msgToScreen',...
                             'name',...
                             'snippet',...
                             'tessellate',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'visibility'};
    case {'ge_plot' }
        
        AuthorizedOptions = {'altitude',...
                             'altitudeMode',...
                             'snippet', ...
                             'description', ...
                             'extrude',...
                             'forceAsLine',...
                             'lineColor',...
                             'lineWidth', ...
                             'msgToScreen',...
                             'name',...
                             'tessellate',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'visibility'};

                 
    case {'ge_point'}
        
        AuthorizedOptions = {'altitudeMode',...
                             'dataFormatStr',...
                             'description',...
                             'extrude',...
                             'iconColor',...
                             'iconScale',...
                             'iconURL',...
                             'msgToScreen',...
                             'name',...
                             'pointDataCell',...      
                             'snippet',...
                             'tableBorderWidth',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'visibility'};
    case {'ge_poly3'}
        
        AuthorizedOptions = {'altitudeMode',...
                             'autoClose',...
                             'description',...
                             'extrude',...
                             'lineColor',...
                             'lineWidth',...
                             'msgToScreen',...
                             'name',...
                             'polyColor',...
                             'snippet',...
                             'tessellate',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'visibility'};
    case {'ge_poly'}
        
        AuthorizedOptions = {'altitude',...
                             'altitudeMode',...
                             'autoClose',...
                             'description',...
                             'extrude',...
                             'lineColor',...
                             'lineWidth',...
                             'msgToScreen',...
                             'name',...
                             'polyColor',...
                             'snippet',...
                             'tessellate',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'visibility',...
                             'innerBoundsStr'};
                 
    case {'ge_polyplace'}
        
        AuthorizedOptions = {
                             'altitude', ...
                             'altitudeMode', ...
                             'description', ...
                             'extrude', ...
                             'lineWidth', ...
                             'lineColor', ...
                             'msgToScreen',...
                             'name',...
                             'polyColor', ...
                             'snippet',...
                             'tessellate', ...
                             'timeStamp', ...
                             'timeSpanStart', ...
                             'timeSpanStop', ...
                             'visibility'};
                 
    case {'ge_quiver3'}
        AuthorizedOptions = {'altitudeMode',...
                             'arrowScale',...
                             'description',...
                             'fixedArrowLength',...
                             'modelLinkStr',...
                             'msgToScreen',...
                             'name',...
                             'snippet',...
                             'timeSpanStart',...
                             'timeSpanStop',...                     
                             'timeStamp'};  
    case {'ge_quiver'}
        
        AuthorizedOptions = {'altitude',...
                             'altitudeMode',...
                             'description',...
                             'extrude',...
                             'msgToScreen',...
                             'lineColor',...
                             'lineWidth',...
                             'name',...
                             'snippet',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'visibility'};

    case {'ge_surf'}
        
        AuthorizedOptions = {'altitude',...    
                             'altitudeMode',...
                             'altRefLevel',...                     
                             'cLimHigh',...
                             'cLimLow',...
                             'cMap',...
                             'extrude',...
                             'lineColor',...
                             'lineWidth',...
                             'msgToScreen',...
                             'name',...
                             'nanValue',...                     
                             'polyAlpha',...
                             'snippet',...
                             'description',...
                             'tessellate',...
                             'timeSpanStart',...
                             'timeSpanStop',...
                             'timeStamp',...
                             'vertExagg',...
                             'visibility',...
                             'xResolution',...
                             'yResolution'};
                 
    case {'ge_windbarb'}
        
        AuthorizedOptions = {'altitudeMode',...
                             'arrowScale',...
                             'msgToScreen',...
                             'rLink',...
                             'timeSpanStart',...
                             'timeSpanStop'};       
    case {'ge_writecollada'}
        
        AuthorizedOptions = {'modelStyle',...
                             'faceColor',...
                             'faceAlpha',...
                             'daeFileName'};

    otherwise
        error('non recognized ge_function');
end

