function demo_ge_plot()%% Demo ge_plot

a = 180*pi;

X = linspace(0,a,2*a);
Y1 = 10*sin(X);
Y2 = 5*cos(X);

kmlStr01 = ge_plot(X,Y1,...
             'lineWidth',5.0, ...
             'lineColor','ffffa432',...
           'msgToScreen',true,...
           'altitude',5000000,...
           'extrude',0,...
           'altitudeMode','relativeToGround');
       
kmlStr02 = ge_plot(X,Y2,...
            'lineWidth',5.0,...
            'lineColor','ffa4ff32',...
          'msgToScreen',true);

kmlFileName = 'demo_ge_plot.kml';
ge_output([kmlFileName],[kmlStr01,kmlStr02],...
                                                  'name',kmlFileName,...
                                           'msgToScreen',true);