#   Copyright notice
#   --------------------------------------------------------------------
#   Copyright (C) 2017 Deltares
#       Gerben Hagenaars
#
#       Gerben.Hagenaars@deltares.nl
#       
#       Wiebe de Boer
#
#       Wiebe.deBoer@deltares.nl
#
#       P.O. Box 177
#       2600 MH Delft
#       The Netherlands
#
#   This library is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Lesser General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This library is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this library.  If not, see <http://www.gnu.org/licenses/>.
#   --------------------------------------------------------------------
#
# This tool is developed as part of the research cooperation between
# Deltares and the Korean Institute of Science and Technology (KIOST).
# The development is funded by the CoMIDAS project of the South Korean
# government and the Deltares strategic research program Coastal and
# Offshore Engineering. This financial support is highly appreciated.

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Fri May 20 12:06:12 2016
# by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	def _fromUtf8(s):
		return s

try:
	_encoding = QtGui.QApplication.UnicodeUTF8

	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig)


class Ui_Dialog(object):
	def setupUi(self, Dialog):
		Dialog.setObjectName(_fromUtf8("Dialog"))
		#Dialog.showMaximized()
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
		Dialog.setPalette(palette)
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Calibri"))
		font.setPointSize(10)
		Dialog.setFont(font)
		Dialog.setMouseTracking(False)
		Dialog.setAutoFillBackground(False)
		self.tab = QtGui.QTabWidget(Dialog)
		self.tab.setEnabled(True)
		self.tab.setGeometry(QtCore.QRect(10, 10, 1191, 731))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Calibri"))
		font.setPointSize(11)
		font.setBold(False)
		font.setWeight(50)
		self.tab.setFont(font)
		self.tab.setFocusPolicy(QtCore.Qt.NoFocus)
		self.tab.setAutoFillBackground(True)
		self.tab.setTabShape(QtGui.QTabWidget.Triangular)
		self.tab.setObjectName(_fromUtf8("tab"))
		self.dl_page = QtGui.QWidget()
		self.dl_page.setObjectName(_fromUtf8("dl_page"))
		self.name = QtGui.QLineEdit(self.dl_page)
		self.name.setGeometry(QtCore.QRect(10, 40, 151, 21))
		self.name.setAlignment(QtCore.Qt.AlignCenter)
		self.name.setObjectName(_fromUtf8("name"))
		self.nameLabel = QtGui.QLabel(self.dl_page)
		self.nameLabel.setGeometry(QtCore.QRect(10, 20, 151, 21))
		font = QtGui.QFont()
		font.setPointSize(11)
		font.setBold(False)
		font.setUnderline(True)
		font.setWeight(50)
		self.nameLabel.setFont(font)
		self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.nameLabel.setObjectName(_fromUtf8("nameLabel"))
		self.sdateLabel = QtGui.QLabel(self.dl_page)
		self.sdateLabel.setGeometry(QtCore.QRect(10, 260, 151, 21))
		font = QtGui.QFont()
		font.setPointSize(11)
		font.setBold(False)
		font.setUnderline(True)
		font.setWeight(50)
		self.sdateLabel.setFont(font)
		self.sdateLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.sdateLabel.setObjectName(_fromUtf8("sdateLabel"))
		self.sdate = QtGui.QDateEdit(self.dl_page)
		self.sdate.setGeometry(QtCore.QRect(10, 280, 151, 22))
		self.sdate.setAlignment(QtCore.Qt.AlignCenter)
		self.sdate.setDate(QtCore.QDate(1985, 1, 1))
		self.sdate.setCalendarPopup(True)
		self.sdate.setObjectName(_fromUtf8("sdate"))
		self.ccLabel = QtGui.QLabel(self.dl_page)
		self.ccLabel.setGeometry(QtCore.QRect(10, 460, 151, 21))
		font = QtGui.QFont()
		font.setPointSize(11)
		font.setBold(False)
		font.setUnderline(True)
		font.setWeight(50)
		self.ccLabel.setFont(font)
		self.ccLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.ccLabel.setObjectName(_fromUtf8("ccLabel"))
		self.epsgLabel = QtGui.QLabel(self.dl_page)
		self.epsgLabel.setGeometry(QtCore.QRect(10, 530, 151, 21))
		font = QtGui.QFont()
		font.setPointSize(11)
		font.setBold(False)
		font.setUnderline(True)
		font.setWeight(50)
		self.epsgLabel.setFont(font)
		self.epsgLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.epsgLabel.setObjectName(_fromUtf8("epsgLabel"))
		self.epsg = QtGui.QLineEdit(self.dl_page)
		self.epsg.setGeometry(QtCore.QRect(10, 550, 151, 20))
		self.epsg.setToolTip(_fromUtf8(""))
		self.epsg.setWhatsThis(_fromUtf8(""))
		self.epsg.setInputMask(_fromUtf8(""))
		self.epsg.setAlignment(QtCore.Qt.AlignCenter)
		self.epsg.setObjectName(_fromUtf8("epsg"))
		self.edate = QtGui.QDateEdit(self.dl_page)
		self.edate.setGeometry(QtCore.QRect(10, 350, 151, 22))
		self.edate.setAlignment(QtCore.Qt.AlignCenter)
		self.edate.setDate(QtCore.QDate(2017, 1, 1))
		self.edate.setCalendarPopup(True)
		self.edate.setObjectName(_fromUtf8("edate"))
		self.dl_button = QtGui.QPushButton(self.dl_page)
		self.dl_button.setGeometry(QtCore.QRect(26, 601, 121, 41))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Calibri"))
		font.setPointSize(11)
		self.dl_button.setFont(font)
		self.dl_button.setObjectName(_fromUtf8("dl_button"))
		self.webView = QtWebKit.QWebView(self.dl_page)
		self.webView.setGeometry(QtCore.QRect(179, 10, 1001, 541))
		self.webView.setAutoFillBackground(False)
		self.webView.setUrl(QtCore.QUrl(_fromUtf8("ee_fex/map.html")))
		self.webView.setObjectName(_fromUtf8("webView"))
		self.edateLabel = QtGui.QLabel(self.dl_page)
		self.edateLabel.setGeometry(QtCore.QRect(10, 330, 151, 21))
		font = QtGui.QFont()
		font.setPointSize(11)
		font.setBold(False)
		font.setUnderline(True)
		font.setWeight(50)
		self.edateLabel.setFont(font)
		self.edateLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.edateLabel.setObjectName(_fromUtf8("edateLabel"))
		self.progressBar = QtGui.QProgressBar(self.dl_page)
		self.progressBar.setEnabled(False)
		self.progressBar.setGeometry(QtCore.QRect(30, 650, 118, 23))
		self.progressBar.setProperty("value", 0)
		self.progressBar.setTextVisible(True)
		self.progressBar.setObjectName(_fromUtf8("progressBar"))
		self.satGroup = QtGui.QGroupBox(self.dl_page)
		self.satGroup.setGeometry(QtCore.QRect(10, 90, 151, 141))
		font = QtGui.QFont()
		font.setUnderline(True)
		self.satGroup.setFont(font)
		self.satGroup.setAlignment(QtCore.Qt.AlignCenter)
		self.satGroup.setObjectName(_fromUtf8("satGroup"))
		self.splitter = QtGui.QSplitter(self.satGroup)
		self.splitter.setGeometry(QtCore.QRect(32, 23, 85, 110))
		self.splitter.setOrientation(QtCore.Qt.Vertical)
		self.splitter.setObjectName(_fromUtf8("splitter"))
		self.L4_check = QtGui.QCheckBox(self.splitter)
		self.L4_check.setEnabled(True)
		font = QtGui.QFont()
		font.setUnderline(False)
		self.L4_check.setFont(font)
		self.L4_check.setIconSize(QtCore.QSize(50, 50))
		self.L4_check.setChecked(True)
		self.L4_check.setTristate(False)
		self.L4_check.setObjectName(_fromUtf8("L4_check"))
		self.L5_check = QtGui.QCheckBox(self.splitter)
		self.L5_check.setEnabled(True)
		font = QtGui.QFont()
		font.setUnderline(False)
		self.L5_check.setFont(font)
		self.L5_check.setIconSize(QtCore.QSize(50, 50))
		self.L5_check.setChecked(True)
		self.L5_check.setTristate(False)
		self.L5_check.setObjectName(_fromUtf8("L5_check"))
		self.L7_check = QtGui.QCheckBox(self.splitter)
		self.L7_check.setEnabled(True)
		font = QtGui.QFont()
		font.setUnderline(False)
		self.L7_check.setFont(font)
		self.L7_check.setIconSize(QtCore.QSize(50, 50))
		self.L7_check.setChecked(False)
		self.L7_check.setTristate(False)
		self.L7_check.setObjectName(_fromUtf8("L7_check"))
		self.L8_check = QtGui.QCheckBox(self.splitter)
		self.L8_check.setEnabled(True)
		font = QtGui.QFont()
		font.setUnderline(False)
		self.L8_check.setFont(font)
		self.L8_check.setIconSize(QtCore.QSize(50, 50))
		self.L8_check.setChecked(True)
		self.L8_check.setTristate(False)
		self.L8_check.setObjectName(_fromUtf8("L8_check"))
		self.S2_check = QtGui.QCheckBox(self.splitter)
		self.S2_check.setEnabled(True)
		font = QtGui.QFont()
		font.setUnderline(False)
		self.S2_check.setFont(font)
		self.S2_check.setIconSize(QtCore.QSize(50, 50))
		self.S2_check.setChecked(True)
		self.S2_check.setTristate(False)
		self.S2_check.setObjectName(_fromUtf8("S2_check"))
		self.reset_button = QtGui.QPushButton(self.dl_page)
		self.reset_button.setEnabled(True)
		self.reset_button.setGeometry(QtCore.QRect(1047, 17, 121, 41))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Calibri"))
		font.setPointSize(11)
		self.reset_button.setFont(font)
		self.reset_button.setObjectName(_fromUtf8("reset_button"))
		self.cc = QtGui.QDoubleSpinBox(self.dl_page)
		self.cc.setGeometry(QtCore.QRect(10, 480, 151, 22))
		self.cc.setAlignment(QtCore.Qt.AlignCenter)
		self.cc.setDecimals(1)
		self.cc.setProperty("value", 15.0)
		self.cc.setObjectName(_fromUtf8("cc"))
		self.ccplotter = MatplotlibWidget(self.dl_page)
		self.ccplotter.setGeometry(QtCore.QRect(179, 560, 1001, 141))
		self.ccplotter.setObjectName(_fromUtf8("ccplotter"))
		self.cc_button = QtGui.QPushButton(self.dl_page)
		self.cc_button.setGeometry(QtCore.QRect(26, 399, 121, 41))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Calibri"))
		font.setPointSize(11)
		self.cc_button.setFont(font)
		self.cc_button.setObjectName(_fromUtf8("cc_button"))
		self.tab.addTab(self.dl_page, _fromUtf8(""))
		self.ft_page = QtGui.QWidget()
		self.ft_page.setEnabled(True)
		self.ft_page.setObjectName(_fromUtf8("ft_page"))
		self.ldbIcon = QtGui.QLabel(self.ft_page)
		self.ldbIcon.setGeometry(QtCore.QRect(37, 435, 101, 31))
		self.ldbIcon.setText(_fromUtf8(""))
		self.ldbIcon.setPixmap(QtGui.QPixmap(_fromUtf8("ee_fex/zm_clicked.png")))
		self.ldbIcon.setScaledContents(True)
		self.ldbIcon.setObjectName(_fromUtf8("ldbIcon"))
		self.kmlIcon = QtGui.QLabel(self.ft_page)
		self.kmlIcon.setGeometry(QtCore.QRect(66, 546, 41, 51))
		self.kmlIcon.setText(_fromUtf8(""))
		self.kmlIcon.setPixmap(QtGui.QPixmap(_fromUtf8("ee_fex/kml_logo.png")))
		self.kmlIcon.setScaledContents(True)
		self.kmlIcon.setObjectName(_fromUtf8("kmlIcon"))
		self.extract_button = QtGui.QPushButton(self.ft_page)
		self.extract_button.setEnabled(True)
		self.extract_button.setGeometry(QtCore.QRect(26, 475, 121, 41))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Calibri"))
		font.setPointSize(11)
		self.extract_button.setFont(font)
		self.extract_button.setObjectName(_fromUtf8("extract_button"))
		self.plotter = MatplotlibWidget(self.ft_page)
		self.plotter.setGeometry(QtCore.QRect(179, 10, 1001, 691))
		self.plotter.setObjectName(_fromUtf8("plotter"))
		self.next_button = QtGui.QPushButton(self.ft_page)
		self.next_button.setEnabled(True)
		self.next_button.setGeometry(QtCore.QRect(89, 350, 58, 40))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Calibri"))
		font.setPointSize(11)
		self.next_button.setFont(font)
		self.next_button.setObjectName(_fromUtf8("next_button"))
		self.prev_button = QtGui.QPushButton(self.ft_page)
		self.prev_button.setEnabled(True)
		self.prev_button.setGeometry(QtCore.QRect(26, 350, 58, 40))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Calibri"))
		font.setPointSize(11)
		self.prev_button.setFont(font)
		self.prev_button.setObjectName(_fromUtf8("prev_button"))
		self.kml_button = QtGui.QPushButton(self.ft_page)
		self.kml_button.setEnabled(True)
		self.kml_button.setGeometry(QtCore.QRect(26, 601, 121, 41))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Calibri"))
		font.setPointSize(11)
		self.kml_button.setFont(font)
		self.kml_button.setObjectName(_fromUtf8("kml_button"))
		self.projList = QtGui.QListWidget(self.ft_page)
		self.projList.setGeometry(QtCore.QRect(10, 40, 151, 301))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Calibri"))
		font.setPointSize(11)
		self.projList.setFont(font)
		self.projList.setAutoFillBackground(False)
		self.projList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
		self.projList.setAlternatingRowColors(False)
		self.projList.setTextElideMode(QtCore.Qt.ElideLeft)
		self.projList.setLayoutMode(QtGui.QListView.SinglePass)
		self.projList.setObjectName(_fromUtf8("projList"))
		self.projLabel = QtGui.QLabel(self.ft_page)
		self.projLabel.setGeometry(QtCore.QRect(10, 20, 151, 21))
		font = QtGui.QFont()
		font.setPointSize(11)
		font.setBold(False)
		font.setUnderline(True)
		font.setWeight(50)
		self.projLabel.setFont(font)
		self.projLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.projLabel.setObjectName(_fromUtf8("projLabel"))
		self.resetProj_button = QtGui.QPushButton(self.ft_page)
		self.resetProj_button.setEnabled(True)
		self.resetProj_button.setGeometry(QtCore.QRect(1047, 17, 121, 41))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Calibri"))
		font.setPointSize(11)
		self.resetProj_button.setFont(font)
		self.resetProj_button.setObjectName(_fromUtf8("resetProj_button"))
		self.verticalLayoutWidget = QtGui.QWidget(self.ft_page)
		self.verticalLayoutWidget.setGeometry(QtCore.QRect(430, 22, 601, 31))
		self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
		self.toolbar = QtGui.QVBoxLayout(self.verticalLayoutWidget)
		self.toolbar.setMargin(0)
		self.toolbar.setObjectName(_fromUtf8("toolbar"))
		self.tab.addTab(self.ft_page, _fromUtf8(""))
		self.google_logo = QtGui.QLabel(Dialog)
		self.google_logo.setGeometry(QtCore.QRect(760, 750, 241, 51))
		self.google_logo.setText(_fromUtf8(""))
		self.google_logo.setPixmap(QtGui.QPixmap(_fromUtf8("ee_fex/EarthEngine_Logo.png")))
		self.google_logo.setScaledContents(True)
		self.google_logo.setObjectName(_fromUtf8("google_logo"))
		self.deltares_logo = QtGui.QLabel(Dialog)
		self.deltares_logo.setGeometry(QtCore.QRect(410, 744, 201, 51))
		self.deltares_logo.setText(_fromUtf8(""))
		self.deltares_logo.setPixmap(QtGui.QPixmap(_fromUtf8("ee_fex/Deltares_logo.png")))
		self.deltares_logo.setScaledContents(True)
		self.deltares_logo.setObjectName(_fromUtf8("deltares_logo"))
		self.quit_button = QtGui.QPushButton(Dialog)
		self.quit_button.setEnabled(True)
		self.quit_button.setGeometry(QtCore.QRect(1078, 751, 121, 41))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Calibri"))
		font.setPointSize(11)
		self.quit_button.setFont(font)
		self.quit_button.setObjectName(_fromUtf8("quit_button"))
		self.ee_logo = QtGui.QLabel(Dialog)
		self.ee_logo.setGeometry(QtCore.QRect(722, 753, 41, 41))
		self.ee_logo.setText(_fromUtf8(""))
		self.ee_logo.setPixmap(QtGui.QPixmap(_fromUtf8("ee_fex/EarthEngine_Logo2.png")))
		self.ee_logo.setScaledContents(True)
		self.ee_logo.setObjectName(_fromUtf8("ee_logo"))
		self.eeFEX_logo = QtGui.QLabel(Dialog)
		self.eeFEX_logo.setGeometry(QtCore.QRect(180, 741, 131, 61))
		self.eeFEX_logo.setText(_fromUtf8(""))
		self.eeFEX_logo.setPixmap(QtGui.QPixmap(_fromUtf8("ee_fex/eeFEX_logo.png")))
		self.eeFEX_logo.setScaledContents(True)
		self.eeFEX_logo.setObjectName(_fromUtf8("eeFEX_logo"))

		self.retranslateUi(Dialog)
		self.tab.setCurrentIndex(0)
		QtCore.QObject.connect(self.quit_button, QtCore.SIGNAL(_fromUtf8("pressed()")), Dialog.reject)
		QtCore.QObject.connect(self.reset_button, QtCore.SIGNAL(_fromUtf8("pressed()")), self.webView.reload)
		QtCore.QMetaObject.connectSlotsByName(Dialog)
		Dialog.setTabOrder(self.name, self.L4_check)
		Dialog.setTabOrder(self.L4_check, self.L5_check)
		Dialog.setTabOrder(self.L5_check, self.L7_check)
		Dialog.setTabOrder(self.L7_check, self.L8_check)
		Dialog.setTabOrder(self.L8_check, self.S2_check)
		Dialog.setTabOrder(self.S2_check, self.sdate)
		Dialog.setTabOrder(self.sdate, self.edate)
		Dialog.setTabOrder(self.edate, self.cc_button)
		Dialog.setTabOrder(self.cc_button, self.cc)
		Dialog.setTabOrder(self.cc, self.epsg)
		Dialog.setTabOrder(self.epsg, self.dl_button)
		Dialog.setTabOrder(self.dl_button, self.webView)
		Dialog.setTabOrder(self.webView, self.reset_button)
		Dialog.setTabOrder(self.reset_button, self.projList)
		Dialog.setTabOrder(self.projList, self.prev_button)
		Dialog.setTabOrder(self.prev_button, self.next_button)
		Dialog.setTabOrder(self.next_button, self.extract_button)
		Dialog.setTabOrder(self.extract_button, self.kml_button)
		Dialog.setTabOrder(self.kml_button, self.resetProj_button)
		Dialog.setTabOrder(self.resetProj_button, self.quit_button)

	def retranslateUi(self, Dialog):
		Dialog.setWindowTitle(_translate("Dialog", "eeFEX (Feature Extraction)", None))
		self.name.setText(_translate("Dialog", "Sandmotor", None))
		self.nameLabel.setText(_translate("Dialog", "New Project Name", None))
		self.sdateLabel.setText(_translate("Dialog", "Start Date", None))
		self.sdate.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd", None))
		self.ccLabel.setText(_translate("Dialog", "Min. Cloud Cover [%]", None))
		self.epsgLabel.setText(_translate("Dialog", "EPSG Code", None))
		self.epsg.setText(_translate("Dialog", "28992", None))
		self.edate.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd", None))
		self.dl_button.setText(_translate("Dialog", "Download", None))
		self.edateLabel.setText(_translate("Dialog", "End Date", None))
		self.satGroup.setTitle(_translate("Dialog", "Satellites", None))
		self.L4_check.setText(_translate("Dialog", "Landsat 4", None))
		self.L4_check.setShortcut(_translate("Dialog", "Enter", None))
		self.L5_check.setText(_translate("Dialog", "Landsat 5", None))
		self.L5_check.setShortcut(_translate("Dialog", "Enter", None))
		self.L7_check.setText(_translate("Dialog", "Landsat 7", None))
		self.L7_check.setShortcut(_translate("Dialog", "Enter", None))
		self.L8_check.setText(_translate("Dialog", "Landsat 8", None))
		self.L8_check.setShortcut(_translate("Dialog", "Enter", None))
		self.S2_check.setText(_translate("Dialog", "Sentinel 2", None))
		self.S2_check.setShortcut(_translate("Dialog", "Enter", None))
		self.reset_button.setText(_translate("Dialog", "Reset Map", None))
		self.cc_button.setText(_translate("Dialog", "Cloud Analysis", None))
		self.tab.setTabText(self.tab.indexOf(self.dl_page), _translate("Dialog", "Image Download", None))
		self.extract_button.setText(_translate("Dialog", "Extract", None))
		self.next_button.setText(_translate("Dialog", "Next", None))
		self.prev_button.setText(_translate("Dialog", "Prev.", None))
		self.kml_button.setText(_translate("Dialog", "Save to *.kml", None))
		self.projList.setSortingEnabled(True)
		self.projLabel.setText(_translate("Dialog", "Available Projects", None))
		self.resetProj_button.setText(_translate("Dialog", "Reset Project", None))
		self.tab.setTabText(self.tab.indexOf(self.ft_page), _translate("Dialog", "Feature Extraction", None))
		self.quit_button.setText(_translate("Dialog", "Quit", None))


from PyQt4 import QtWebKit
from matplotlibwidget import MatplotlibWidget
