function str = nc_getEPSGdescription(EPSGcode)
%UNTITLED  One line description goes here.
%
%   More detailed description goes here.
%
%   Syntax:
%   varargout = Untitled(varargin)
%
%   Input:
%   varargin  =
%
%   Output:
%   varargout =
%
%   Example
%   Untitled
%
%   See also

%% Copyright notice
%   --------------------------------------------------------------------
%   Copyright (C) 2010 Delft University of Technology
%       Mark van Koningsveld
%
%       m.vankoningsveld@tudelft.nl
%
%       Hydraulic Engineering Section
%       Faculty of Civil Engineering and Geosciences
%       Stevinweg 1
%       2628CN Delft
%       The Netherlands
%
%   This library is free software: you can redistribute it and/or
%   modify it under the terms of the GNU Lesser General Public
%   License as published by the Free Software Foundation, either
%   version 2.1 of the License, or (at your option) any later version.
%
%   This library is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%   Lesser General Public License for more details.
%
%   You should have received a copy of the GNU Lesser General Public
%   License along with this library. If not, see <http://www.gnu.org/licenses/>.
%   --------------------------------------------------------------------

% This tool is part of <a href="http://OpenEarth.nl">OpenEarthTools</a>.
% OpenEarthTools is an online collaboration to share and manage data and
% programming tools in an open source, version controlled environment.
% Sign up to recieve regular updates of this function, and to contribute
% your own tools.

%% Version <http://svnbook.red-bean.com/en/1.5/svn.advanced.props.special.keywords.html>
% Created: 20 Mar 2010
% Created with Matlab version: 7.7.0.471 (R2008b)

% $Id$
% $Date$
% $Author$
% $Revision$
% $HeadURL$
% $Keywords: $

%%
switch EPSGcode
    case 28355 % GDA94 / MGA zone 55
        str = ['PROJCS["GDA94 / MGA zone 55",' char(10) ...
            '    GEOGCS["GDA94",' char(10) ...
            '        DATUM["Geocentric_Datum_of_Australia_1994",' char(10) ...
            '            SPHEROID["GRS 1980",6378137,298.257222101,' char(10) ...
            '                AUTHORITY["EPSG","7019"]],' char(10) ...
            '            TOWGS84[0,0,0,0,0,0,0],' char(10) ...
            '            AUTHORITY["EPSG","6283"]],' char(10) ...
            '        PRIMEM["Greenwich",0,' char(10) ...
            '            AUTHORITY["EPSG","8901"]],' char(10) ...
            '        UNIT["degree",0.01745329251994328,' char(10) ...
            '            AUTHORITY["EPSG","9122"]],' char(10) ...
            '        AUTHORITY["EPSG","4283"]],' char(10) ...
            '    UNIT["metre",1,' char(10) ...
            '        AUTHORITY["EPSG","9001"]],' char(10) ...
            '    PROJECTION["Transverse_Mercator"],' char(10) ...
            '    PARAMETER["latitude_of_origin",0],' char(10) ...
            '    PARAMETER["central_meridian",147],' char(10) ...
            '    PARAMETER["scale_factor",0.9996],' char(10) ...
            '    PARAMETER["false_easting",500000],' char(10) ...
            '    PARAMETER["false_northing",10000000],' char(10) ...
            '    AUTHORITY["EPSG","28355"],' char(10) ...
            '    AXIS["Easting",EAST],' char(10) ...
            '    AXIS["Northing",NORTH]]'];
    case 28992
        str = ['PROJCS["Amersfoort / RD New",' char(10) ...
            '    GEOGCS["Amersfoort",' char(10) ...
            '        DATUM["Amersfoort",' char(10) ...
            '            SPHEROID["Bessel 1841",6377397.155,299.1528128,' char(10) ...
            '                AUTHORITY["EPSG","7004"]],' char(10) ...
            '            AUTHORITY["EPSG","6289"]],' char(10) ...
            '        PRIMEM["Greenwich",0,' char(10) ...
            '            AUTHORITY["EPSG","8901"]],' char(10) ...
            '        UNIT["degree",0.01745329251994328,' char(10) ...
            '            AUTHORITY["EPSG","9122"]],' char(10) ...
            '        AUTHORITY["EPSG","4289"]],' char(10) ...
            '    UNIT["metre",1,' char(10) ...
            '        AUTHORITY["EPSG","9001"]],' char(10) ...
            '    PROJECTION["Oblique_Stereographic"],' char(10) ...
            '    PARAMETER["latitude_of_origin",52.15616055555555],' char(10) ...
            '    PARAMETER["central_meridian",5.38763888888889],' char(10) ...
            '    PARAMETER["scale_factor",0.9999079],' char(10) ...
            '    PARAMETER["false_easting",155000],' char(10) ...
            '    PARAMETER["false_northing",463000],' char(10) ...
            '    AUTHORITY["EPSG","28992"],' char(10) ...
            '    AXIS["X",EAST],' char(10) ...
            '    AXIS["Y",NORTH]]'];
    case 29902
        str = ['PROJCS["TM65 / Irish Grid",' char(10) ...
        '    GEOGCS["TM65",' char(10) ...
        '        DATUM["TM65",' char(10) ...
        '            SPHEROID["Airy Modified 1849",6377340.189,299.3249646,' char(10) ...
        '                AUTHORITY["EPSG","7002"]],' char(10) ...
        '            AUTHORITY["EPSG","6299"]],' char(10) ...
        '        PRIMEM["Greenwich",0,' char(10) ...
        '            AUTHORITY["EPSG","8901"]],' char(10) ...
        '        UNIT["degree",0.01745329251994328,' char(10) ...
        '            AUTHORITY["EPSG","9122"]],' char(10) ...
        '        AUTHORITY["EPSG","4299"]],' char(10) ...
        '    UNIT["metre",1,' char(10) ...
        '        AUTHORITY["EPSG","9001"]],' char(10) ...
        '    PROJECTION["Transverse_Mercator"],' char(10) ...
        '    PARAMETER["latitude_of_origin",53.5],' char(10) ...
        '    PARAMETER["central_meridian",-8],' char(10) ...
        '    PARAMETER["scale_factor",1.000035],' char(10) ...
        '    PARAMETER["false_easting",200000],' char(10) ...
        '    PARAMETER["false_northing",250000],' char(10) ...
        '    AUTHORITY["EPSG","29902"],' char(10) ...
        '    AXIS["Easting",EAST],' char(10) ...
        '    AXIS["Northing",NORTH]]'];
end