function refresh(Obj);

AllItems=handles(ob_ideas(Obj));
if isempty(AllItems),
  ui_message('warning','AllItems empty in ob_counter/refresh');
  return;
end;
MainItem=AllItems(1);

UD=get(MainItem,'userdata');
Info=UD.Info;

ErrorMsg='';

if isempty(Info.Link),
  if ~isempty(Info.OldLink),
    unlink(Info.OldLink,UD.Object);
  end;
else,
  if ~isequal(Info.Link,Info.OldLink),
    if ~isempty(Info.OldLink),
      unlink(Info.OldLink,UD.Object);
    end;
    link(Info.Link,UD.Object);
  end;
  LinkHandles=handles(Info.Link);
  if isempty(LinkHandles),
    ui_message('warning','Counter-linked object has disappeared.');
    Info.Link=[];
  else,
    LinkUD=get(LinkHandles(1),'userdata');
    if isfield(LinkUD,'CurrentTime'),
      Info.Value=LinkUD.CurrentTime;
      if ~isequal(size(Info.Value),[1 1]),
        ui_message('warning',{sprintf('%s:',mfilename), ...
          sprintf('''%s'' has an invalid CurrentTime field.',LinkUD.Name)});
        Info.Value=0;
      end;
    else,
      Info.Value=0;
      try,
        ui_message('warning',{sprintf('%s:',mfilename), ...
          sprintf('''%s'' does not have a CurrentTime field.',LinkUD.Name)});
      end;
    end;
  end;
end;
Info.OldLink=Info.Link;
if isnan(Info.Value),
  Info.Value=0;
end;
% --------
%  Create / update object here
% --------
switch Info.CounterType,
case 'none',
  delete(allchild(MainItem));
  set(MainItem, ...
      'xlim',[0 1], ...
      'ylim',[0 1], ...
      'zlim',[0 1], ...
      'xtick',[], ...
      'ytick',[], ...
      'ztick',[], ...
      'dataaspectratio',[1 1 1], ...
      'view',[0 90], ...
      'box','on', ...
      'color','w');
  set(get(MainItem,'xlabel'),'string','');
  set(get(MainItem,'ylabel'),'string','');
  set(get(MainItem,'zlabel'),'string','');
  UD.CounterType='none';
otherwise,
  if ~isequal(UD.CounterType,Info.CounterType),
    delete(allchild(MainItem));
    switch Info.CounterType,
    case 'counter',
      set(MainItem, ...
            'visible','off', ...
            'dataaspectratio',[1 3 1], ...
            'xlim',[-1 1], ...
            'ylim',[-1 1]);
      
      % background plate
      B=patch([-1 1 1 -1],[-1 -1 1 1],-ones(1,4), ...
         'facecolor','w', ...
         'parent',MainItem, ...
         'tag','BackgroundPlateClock', ...
         'clipping','off');
      
      fontsize=0.8;
      %numbers and indicators
      TT=text(0,0,'00.00', ...
         'color','k', ...
         'fontunits','normalized', ...
         'fontsize',fontsize, ...
         'horizontalalignment','center', ...
         'verticalalignment','middle', ...
         'parent',MainItem, ...
         'clipping','off', ...
         'tag','ValueText');
    case 'analog clock',
      set(MainItem, ...
            'visible','off', ...
            'dataaspectratio',[1 1 1], ...
            'xlim',[-1 1], ...
            'ylim',[-1 1]);
      
      % background plate
      X=sin(0:.1:(2*pi));
      Y=cos(0:.1:(2*pi));
      B=patch(X,Y,-ones(size(X)), ...
            'facecolor','w', ...
            'parent',MainItem, ...
            'tag','BackgroundPlateClock', ...
            'clipping','off');
      
      % hour ticks
      XH=sin((1:12)*(2*pi)/12);
      YH=cos((1:12)*(2*pi)/12);
      HT=line([.9*XH; .85*XH],[.9*YH;.85*YH], ...
            'color','k', ...
            'parent',MainItem, ...
            'tag','HourTicks', ...
            'clipping','off');
      
      %hands and indicators
      SH=line(0.8*[0 0],0.8*[0 1], ...
         'color','r', ...
         'parent',MainItem, ...
         'clipping','off', ...
         'tag','SecondsHand');
      MH=line(0.9*[0 0],0.9*[0 1], ...
         'color','k', ...
         'parent',MainItem, ...
         'clipping','off', ...
         'tag','MinutesHand');
      HH=line(0.5*[0 0],0.5*[0 1], ...
         'color','k', ...
         'linewidth',1.5, ...
         'parent',MainItem, ...
         'clipping','off', ...
         'tag','HoursHand');
      AM=text(0.5,0,'AM', ...
         'color','k', ...
         'fontunits','normalized', ...
         'fontsize',.1, ...
         'horizontalalignment','center', ...
         'verticalalignment','middle', ...
         'parent',MainItem, ...
         'clipping','off', ...
         'tag','AM/PMIndicator');
    case 'digital clock',
      set(MainItem, ...
            'visible','off', ...
            'dataaspectratio',[1 3 1], ...
            'xlim',[-1 1], ...
            'ylim',[-1 1]);
      
      % background plate
      B=patch([-1 1 1 -1],[-1 -1 1 1],-ones(1,4), ...
          'facecolor','k', ...
          'parent',MainItem, ...
          'tag','BackgroundPlateClock', ...
          'clipping','off');
      
      fontsize=0.5;
      %numbers and indicators
      ST=text(0.6,0,'00', ...
         'color','r', ...
         'parent',MainItem, ...
         'fontunits','normalized', ...
         'fontsize',fontsize, ...
         'horizontalalignment','center', ...
         'verticalalignment','middle', ...
         'clipping','off', ...
         'tag','SecondsText');
      SEP1=text(0.3,0,':', ...
         'color','r', ...
         'parent',MainItem, ...
         'fontunits','normalized', ...
         'fontsize',fontsize, ...
         'horizontalalignment','center', ...
         'verticalalignment','middle', ...
         'clipping','off', ...
         'tag','Separator 1');
      MT=text(0,0,'00', ...
         'color','r', ...
         'fontunits','normalized', ...
         'fontsize',fontsize, ...
         'horizontalalignment','center', ...
         'verticalalignment','middle', ...
         'parent',MainItem, ...
         'clipping','off', ...
         'tag','MinutesText');
      SEP2=text(-0.3,0,':', ...
         'color','r', ...
         'parent',MainItem, ...
         'fontunits','normalized', ...
         'fontsize',fontsize, ...
         'horizontalalignment','center', ...
         'verticalalignment','middle', ...
         'clipping','off', ...
         'tag','Separator 2');
      HT=text(-0.6,0,'00', ...
         'color','r', ...
         'fontunits','normalized', ...
         'fontsize',fontsize, ...
         'horizontalalignment','center', ...
         'verticalalignment','middle', ...
         'parent',MainItem, ...
         'clipping','off', ...
         'tag','HoursText');
    case 'calendar',
      set(MainItem, ...
            'visible','off', ...
            'dataaspectratio',[1 1 1], ...
            'xlim',[-1 1], ...
            'ylim',[-1 1]);
      
      % background plate
      B=patch([-1 -1 1 1],[-1 1 1 -1],-ones(1,4), ...
          'facecolor','w', ...
          'parent',MainItem, ...
          'tag','BackgroundPlateCalendar', ...
          'clipping','off');
      
      %indicators
      WD=text(0,.6,'WD', ...
          'color','k', ...
          'fontunits','normalized', ...
          'fontsize',0.1, ...
          'horizontalalignment','center', ...
          'verticalalignment','middle', ...
          'tag','Weekday', ...
          'parent',MainItem, ...
          'clipping','off');
      D=text(0,.2,'D', ...
          'color',[1 0 0], ...
          'fontunits','normalized', ...
          'fontsize',0.25, ...
          'fontweight','bold', ...
          'horizontalalignment','center', ...
          'verticalalignment','middle', ...
          'tag','Day', ...
          'parent',MainItem, ...
          'clipping','off');
      M=text(0,-0.2,'M', ...
          'color','k', ...
          'fontunits','normalized', ...
          'fontsize',0.15, ...
          'horizontalalignment','center', ...
          'verticalalignment','middle', ...
          'tag','Month', ...
          'parent',MainItem, ...
          'clipping','off');
      Y=text(0,-.6,'Y', ...
          'color','k', ...
          'fontunits','normalized', ...
          'fontsize',0.15, ...
          'horizontalalignment','center', ...
          'verticalalignment','middle', ...
          'tag','Year', ...
          'parent',MainItem, ...
          'clipping','off');
    end;
    UD.CounterType=Info.CounterType;
  else,
    switch Info.CounterType,
    case 'counter',
      B =findobj(MainItem,'tag','BackgroundPlateClock');
      TT=findobj(MainItem,'tag','ValueText');
    case 'analog clock',
      B =findobj(MainItem,'tag','BackgroundPlateClock');
      SH=findobj(MainItem,'tag','SecondsHand');
      MH=findobj(MainItem,'tag','MinutesHand');
      HH=findobj(MainItem,'tag','HoursHand');
      HT=findobj(MainItem,'tag','HourTicks');
      AM=findobj(MainItem,'tag','AM/PMIndicator');
    case 'digital clock',
      B =findobj(MainItem,'tag','BackgroundPlateClock');
      ST=findobj(MainItem,'tag','SecondsText');
      MT=findobj(MainItem,'tag','MinutesText');
      HT=findobj(MainItem,'tag','HoursText');
      SEP1=findobj(MainItem,'tag','Separator 1');
      SEP2=findobj(MainItem,'tag','Separator 2');
    case 'calendar',
      B =findobj(MainItem,'tag','BackgroundPlateCalendar');
      WD=findobj(MainItem,'tag','Weekday');
      D =findobj(MainItem,'tag','Day');
      M =findobj(MainItem,'tag','Month');
      Y =findobj(MainItem,'tag','Year');
    end;
  end;
  Value=min(max(Info.Value-Info.Reference,Info.Minimum),Info.Maximum);
  switch UD.CounterType,
  case 'counter',
    Str=sprintf('%7.2f',Value);
    Str=Str(end-6:end);
    set(TT,'string',Str,'visible',OnOff(Info.Visible));
    set(B,'visible',OnOff(Info.Visible));
  case 'analog clock',
    Value=datevec(Value);
    second=Value(6);
    minute=Value(5);
    hour=Value(4);
    set(SH,'xdata',0.8*[0 sin(second*2*pi/60)], ...
           'ydata',0.8*[0 cos(second*2*pi/60)], ...
           'visible',OnOff(Info.SHVis & Info.Visible));
    set(MH,'xdata',0.9*[0 sin((minute+second/60)*2*pi/60)], ...
           'ydata',0.9*[0 cos((minute+second/60)*2*pi/60)], ...
           'visible',OnOff(Info.MHVis & Info.Visible));
    set(HH,'xdata',0.5*[0 sin((hour+minute/60+second/3600)*2*pi/12)], ...
           'ydata',0.5*[0 cos((hour+minute/60+second/3600)*2*pi/12)], ...
           'visible',OnOff(Info.HHVis & Info.Visible));
    if hour<12,
      set(AM,'string','AM', ...
             'visible',OnOff(Info.AMVis & Info.Visible));
    else,
      set(AM,'string','PM', ...
             'visible',OnOff(Info.AMVis & Info.Visible));
    end;
    set(B,'visible',OnOff(Info.Visible));
    set(HT,'visible',OnOff(Info.Visible));
  case 'digital clock',
    Value=datevec(Value);
    second=round(Value(6));
    minute=Value(5);
    hour=Value(4);
    set(ST,'string',sprintf('%2.2i',second),'visible',OnOff(Info.Visible));
    set(MT,'string',sprintf('%2.2i',minute),'visible',OnOff(Info.Visible));
    if hour<10,
      set(HT,'string',sprintf('  %i',hour),'visible',OnOff(Info.Visible));
    else,
      set(HT,'string',sprintf('%2i',hour),'visible',OnOff(Info.Visible));
    end;
    set(B,'visible',OnOff(Info.Visible));
    set([SEP1 SEP2],'visible',OnOff(Info.Visible));
  case 'calendar',
    daystr=str2mat('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday');
    monthstr=str2mat('January','February','March','April','May','June','July','August','September','October','November','December');

    set(WD,'string',deblank(daystr(weekday(Value),:)),'visible',OnOff(Info.Visible));
    Value=datevec(Value);      
    set(D,'string',int2str(Value(3)),'visible',OnOff(Info.Visible));
    set(M,'string',deblank(monthstr(Value(2),:)),'visible',OnOff(Info.Visible));
    set(Y,'string',int2str(Value(1)),'visible',OnOff(Info.Visible));
    set(B,'visible',OnOff(Info.Visible));
  end;
end;

if ~isempty(ErrorMsg),
  uiwait(msgbox(ErrorMsg,'modal'));
end;

UD.Info=Info;
UD.Name=UD.Info.Name;
set(MainItem,'userdata',UD);

function Str=OnOff(L),
if L,
  Str='on';
else,
  Str='off';
end;
