function md_animate0()

ss=get(0,'screensize');

a = figure('Units','pixels', ...
	'Color',[0.8 0.8 0.8], ...
	'HandleVisibility','off', ...
	'IntegerHandle','off', ...
	'MenuBar','none', ...
	'Name','Select items to animate ...', ...
	'NumberTitle','off', ...
	'Position',[ss(3)-321 ss(4)-500 321 259], ...
	'Resize','off', ...
        'closerequestfcn','', ...
	'Tag','IDEAS animate items');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
	'Position',[10 30 300 80], ...
	'String',' ', ...
	'Style','listbox', ...
	'Tag','anim list', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
	'Position',[11 150 300 80], ...
	'String',' ', ...
	'Style','listbox', ...
	'Tag','noanim list', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'HorizontalAlignment','left', ...
	'Position',[10 230 150 15], ...
	'String','don''t animate', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'HorizontalAlignment','left', ...
	'Position',[10 110 150 15], ...
	'String','animate', ...
	'Style','text', ...
	'Tag','StaticText2');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','md_animate anim', ...
	'FontSize',12, ...
	'Position',[162 130 150 20], ...
	'String','animate item', ...
	'Tag','anim');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','md_animate noanim', ...
	'FontSize',12, ...
	'Position',[162 110 150 20], ...
	'String','don''t animate item', ...
	'Tag','noanim');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','md_animate continue', ...
	'FontSize',12, ...
	'Position',[160 10 150 20], ...
	'String','continue', ...
	'Tag','continue');
