function ui_gfxmngr()

ss=get(0,'screensize');

a = figure('Color',[0.8 0.8 0.8], ...
	'HandleVisibility','off', ...
	'IntegerHandle','off', ...
	'MenuBar','none', ...
	'Name','Graphics manager', ...
	'NumberTitle','off', ...
	'Position',[20 ss(4)-190 230 140], ...
	'Resize','off', ...
	'Tag','Graphics manager for Matlab (c)');

b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'Position',[10 110 210 20], ...
	'Style','text', ...
	'String','', ...
	'Tag','message');

b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','gfxmngr copy', ...
	'FontSize',12, ...
	'Position',[10 80 100 20], ...
	'String','copy', ...
	'Tag','copy');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','gfxmngr move', ...
	'FontSize',12, ...
	'Position',[10 60 100 20], ...
	'String','move', ...
	'Tag','move');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','gfxmngr delete', ...
	'FontSize',12, ...
	'Position',[10 40 100 20], ...
	'String','delete', ...
	'Tag','delete');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','gfxmngr addtext', ...
	'FontSize',12, ...
	'Position',[110 80 100 20], ...
	'String','add text', ...
	'Tag','add text');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','gfxmngr edit', ...
	'FontSize',12, ...
	'Position',[110 60 100 20], ...
	'String','edit', ...
	'Tag','edit');

b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','gfxmngr close', ...
	'FontSize',12, ...
	'Position',[10 10 210 20], ...
	'String','close', ...
	'Tag','close');
