function ui_ideas()

activestyle=logicalswitch(isunix,'pushbutton','frame');
enablemode=logicalswitch(isunix,'on','inactive');
cb_or_bdf=logicalswitch(isunix,'callback','buttondownfcn');

ss=get(0,'screensize');

a = figure('CloseRequestFcn','', ...
	'Color',[0.8 0.8 0.8], ...
	'HandleVisibility','off', ...
	'IntegerHandle','off', ...
	'MenuBar','none', ...
	'Name','IDEAS for Matlab', ...
	'NumberTitle','off', ...
	'Position',[ss(3)-330 ss(4)-400 320 370], ...
	'Resize','off', ...
	'Tag','IDEAS - main');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','ideas newfigure', ...
	'FontSize',12, ...
	'Position',[10 310 145 20], ...
	'String','new figure', ...
	'Tag','newfig', ...
	'UserData',3);
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ideas figurelist', ...
	'FontSize',12, ...
	'Position',[10 210 145 80], ...
	'Style','listbox', ...
	'Tag','figlist', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','ideas deletefigure', ...
	'Enable','off', ...
	'FontSize',12, ...
	'Position',[30 190 125 20], ...
	'String','delete figure', ...
	'Tag','delfig');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','ideas newaxes', ...
	'Enable','off', ...
	'FontSize',12, ...
	'Position',[165 310 145 20], ...
	'String','new object', ...
	'Tag','newaxes');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ideas axeslist', ...
	'FontSize',12, ...
	'Position',[165 210 145 80], ...
	'Style','listbox', ...
	'Tag','axeslist', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','ideas deleteaxes', ...
	'Enable','off', ...
	'FontSize',12, ...
	'Position',[185 190 125 20], ...
	'String','delete axes', ...
	'Tag','delaxes');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','ideas close', ...
	'FontSize',12, ...
	'Position',[165 340 145 20], ...
	'String','close', ...
	'Tag','close');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','ideas newitem', ...
	'Enable','off', ...
	'FontSize',12, ...
	'Position',[10 110 145 20], ...
	'String','new item', ...
	'Tag','newitem');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ideas itemlist', ...
	'FontSize',12, ...
	'Position',[10 30 300 80], ...
	'Style','listbox', ...
	'Tag','itemlist', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','ideas deleteitem', ...
	'Enable','off', ...
	'FontSize',12, ...
	'Position',[185 10 125 20], ...
	'String','delete item', ...
	'Tag','delitem');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','ideas closedata', ...
	'Enable','off', ...
	'FontSize',12, ...
	'Position',[165 160 145 20], ...
	'String','close data file', ...
	'Tag','closedata');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','ideas printfigure', ...
	'Enable','off', ...
	'FontSize',12, ...
	'Position',[10 290 47 20], ...
	'String','print', ...
	'Tag','printfig');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','ideas edititem', ...
	'Enable','off', ...
	'FontSize',12, ...
	'Position',[165 110 145 20], ...
	'String','edit item', ...
	'Tag','editem');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','ideas editaxes', ...
	'Enable','off', ...
	'FontSize',12, ...
	'Position',[165 290 145 20], ...
	'String','edit axes / border', ...
	'Tag','editaxes');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','ideas savefigure', ...
	'Enable','off', ...
	'FontSize',12, ...
	'Position',[108 290 47 20], ...
	'String','save', ...
	'Tag','savefig');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	cb_or_bdf,'ideas deletefigurelock', ...
	'Position',[15 195 10 10], ...
	'Style',activestyle, ...
        'Enable',enablemode, ...
	'Tag','delfiglock', ...
	'UserData',[0 1 0]);
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	cb_or_bdf,'ideas deleteaxeslock', ...
	'Position',[170 195 10 10], ...
	'Style',activestyle, ...
        'Enable',enablemode, ...
	'Tag','delaxeslock', ...
	'UserData',[0 1 0]);
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	cb_or_bdf,'ideas deleteitemlock', ...
	'Position',[170 15 10 10], ...
	'Style',activestyle, ...
        'Enable',enablemode, ...
	'Tag','delitemlock', ...
	'UserData',[0 1 0]);
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','ideas loadfigure', ...
	'FontSize',12, ...
	'Position',[58 290 49 20], ...
	'String','load', ...
	'Tag','loadfig');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','ideas opendata', ...
	'FontSize',12, ...
	'Position',[10 160 145 20], ...
	'String','open data file', ...
	'Tag','opendata');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','ideas currentdata', ...
	'Enable','off', ...
	'FontSize',12, ...
	'Position',[10 140 300 20], ...
	'String',' ', ...
	'Style','popupmenu', ...
	'Tag','currentdata', ...
	'Value',1);
