function a=ui_winmngr(HVis)

ss=get(0,'screensize');

if isunix,
  Size=[20 ss(4)-410 230 360];
  XDispOnOff='on';
else,
  Size=[20 ss(4)-325 230 275];
  XDispOnOff='off';
end;

a = figure('Color',[0.8 0.8 0.8], ...
	'HandleVisibility','off', ...
	'IntegerHandle','off', ...
	'MenuBar','none', ...
	'Name','Window manager', ...
	'NumberTitle','off', ...
	'Position',Size, ...
   'resize','on', ...
   'resizefcn','winmngr resize', ...
	'Tag','Window manager for Matlab (c)');

b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','winmngr moveto', ...
	'FontSize',12, ...
	'Position',[10 330 100 20], ...
	'String','move to', ...
	'Visible',XDispOnOff, ...
	'Tag','move to');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','winmngr new', ...
	'FontSize',12, ...
	'Position',[120 330 100 20], ...
	'String','new', ...
	'Visible',XDispOnOff, ...
	'Tag','new');

UD.fighandles=[];
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','winmngr refresh', ...
	'FontSize',12, ...
	'Max',1, ...
	'Position',[10 270 210 55], ...
	'String',{''}, ...
	'Style','listbox', ...
	'Tag','displist', ...
	'Visible',XDispOnOff, ...
	'Value',1);

b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','winmngr delete', ...
	'FontSize',12, ...
	'Position',[10 225 100 20], ...
	'String','delete', ...
	'Tag','delete');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','winmngr edit', ...
	'FontSize',12, ...
	'Position',[120 225 100 20], ...
	'String','edit', ...
	'Tag','edit');

b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','winmngr togglehvis', ...
	'FontSize',12, ...
	'Position',[10 245 100 20], ...
	'String','toggle HVis', ...
	'Visible','off', ...
	'Tag','hvis');
if (nargin>0) & strcmp(HVis,'hvis'),
  set(b,'Visible','on');
end;

b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','winmngr print', ...
	'FontSize',12, ...
	'Position',[120 245 100 20], ...
	'String','print', ...
	'Tag','print');

b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
        'Callback','winmngr listbox', ...
	'CreateFcn','winmngr refresh', ...
	'FontSize',12, ...
	'Max',2, ...
	'Position',[10 55 210 165], ...
	'String',{''}, ...
	'Style','listbox', ...
	'Tag','figlist', ...
	'UserData',UD, ...
	'Value',1);

b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','winmngr refresh', ...
	'FontSize',12, ...
	'Position',[10 30 210 20], ...
	'String','refresh', ...
	'Tag','refresh');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','winmngr close', ...
	'FontSize',12, ...
	'Position',[10 10 210 20], ...
	'String','close', ...
	'Tag','close');