function ui_wsmngr()

ss=get(0,'screensize');

a = figure('Color',[0.8 0.8 0.8], ...
	'HandleVisibility','off', ...
	'IntegerHandle','off', ...
	'MenuBar','none', ...
	'Name','Workspace manager', ...
	'NumberTitle','off', ...
	'Position',[20 ss(4)-305 230 255], ...
	'Resize','off', ...
	'Tag','Window manager for Matlab (c)');

UD.varhandles=[];
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'CreateFcn','wsmngr refresh', ...
	'FontSize',12, ...
	'Max',2, ...
	'Position',[10 55 210 165], ...
	'String',{''}, ...
	'Style','listbox', ...
	'Tag','varlist', ...
	'UserData',UD, ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','wsmngr clear', ...
	'FontSize',12, ...
	'Position',[10 225 100 20], ...
	'String','clear', ...
	'Tag','clear');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','wsmngr edit', ...
	'FontSize',12, ...
	'Position',[120 225 100 20], ...
	'String','edit', ...
	'Tag','edit');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','wsmngr refresh', ...
	'FontSize',12, ...
	'Position',[10 30 210 20], ...
	'String','refresh', ...
	'Tag','refresh');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','wsmngr close', ...
	'FontSize',12, ...
	'Position',[10 10 210 20], ...
	'String','close', ...
	'Tag','close');
