flowexedir       = /u/mol/d3d/Delft3D-FLOW/3.60.00.5347/intel/flow/bin/
flowexename      = delftflow
flowargs         = delft3d-flow_args.txt dummy delft3d
waveexedir       = /u/mol/d3d/Delft3D-WAVES/3.01.00.8399/intel/wave/bin/ 
waveargs         = example.mdw 1
swanbatdir       = /p/1200745-morfologie/Task_2_IJmuiden/5_Delft3D/AM/runs/flowwave/mormerge/run1/input/
#nodes            = local
nodes            = 2
debug            = 1
workdir          = /var/tmp
condition:weight =   run01 : 50
condition:weight =   run02 : 50
