function fig = ui_ds_loadfield()

ss=get(0,'screensize');

Handles.Figure = figure('BackingStore','off', ...
	'Color',[0.8 0.8 0.8], ...
	'HandleVisibility','off', ...
	'IntegerHandle','off', ...
	'MenuBar','none', ...
	'NumberTitle','off', ...
	'Position',[ss(3)-330 ss(4)-410 320 370], ...
	'RendererMode','manual', ...
	'Resize','off', ...
        'CloseRequestFcn','', ...
	'Tag','DSLoadField - main');
Handles.List = uimenu('Parent',Handles.Figure, ...
	'Label','&list', ...
	'Tag','list');
Handles.ListLoad = uimenu('Parent',Handles.List, ...
	'Label','&load', ...
        'Callback',['stackudf(gcbf,''CommandStack'',[5 1])'], ...
	'Tag','listload');
Handles.ListSave = uimenu('Parent',Handles.List, ...
	'Label','&save', ...
        'Callback',['stackudf(gcbf,''CommandStack'',[5 2])'], ...
	'Tag','listsave');
Handles.OpenFile = uicontrol('Parent',Handles.Figure, ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[10 340 145 20], ...
	'String','open data file', ...
        'Callback',['stackudf(gcbf,''CommandStack'',[1 1])'], ...
	'Tag','opendata');
Handles.CloseFile = uicontrol('Parent',Handles.Figure, ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[165 340 145 20], ...
	'String','close data file', ...
        'Callback',['stackudf(gcbf,''CommandStack'',[1 2])'], ...
	'Enable','off', ...
	'Tag','closedata');
Handles.CurrentData = uicontrol('Parent',Handles.Figure, ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[10 320 300 20], ...
	'String',' ', ...
	'Style','popupmenu', ...
        'Callback',['stackudf(gcbf,''CommandStack'',[1 3])'], ...
	'Enable','off', ...
	'Tag','currentdata', ...
	'Value',1);
Handles.EntryAdd = uicontrol('Parent',Handles.Figure, ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[10 290 145 20], ...
	'String','add from file', ...
        'Callback',['stackudf(gcbf,''CommandStack'',[2 1])'], ...
	'Enable','off', ...
	'Tag','addentry');
Handles.EntryList = uicontrol('Parent',Handles.Figure, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
	'Position',[10 60 300 210], ...
	'String',' ', ...
	'Style','listbox', ...
	'Tag','entrylist', ...
	'Enable','off', ...
	'Value',1);
Handles.EntryMove = uicontrol('Parent',Handles.Figure, ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[10 270 145 20], ...
	'String','move current entry', ...
        'Callback',['stackudf(gcbf,''CommandStack'',[2 2])'], ...
	'Enable','off', ...
	'Tag','entrymove');
Handles.EntryDel = uicontrol('Parent',Handles.Figure, ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[10 40 145 20], ...
	'String','delete entry', ...
        'Callback',['stackudf(gcbf,''CommandStack'',[3 1])'], ...
	'Enable','off', ...
	'Tag','entrydel');
Handles.EntryEdit = uicontrol('Parent',Handles.Figure, ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[165 40 145 20], ...
	'String','edit entry', ...
        'Callback',['stackudf(gcbf,''CommandStack'',[3 2])'], ...
	'Enable','off', ...
	'Tag','entryedit');
Handles.Reset = uicontrol('Parent',Handles.Figure, ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[10 10 145 20], ...
	'String','reset', ...
        'Callback',['stackudf(gcbf,''CommandStack'',[4 1])'], ...
	'Tag','reset');
Handles.Accept = uicontrol('Parent',Handles.Figure, ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[165 10 145 20], ...
	'String','accept', ...
        'Callback',['stackudf(gcbf,''CommandStack'',[4 2])'], ...
	'Tag','accept');
Handles.AddAt = uicontrol('Parent',Handles.Figure, ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[165 290 145 20], ...
	'String',{'at top','above selected entry','below selected entry','at bottom'}, ...
	'Style','popupmenu', ...
	'Tag','Wentryadd', ...
	'Enable','off', ...
	'Value',1);
Handles.MoveTo = uicontrol('Parent',Handles.Figure, ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[165 270 145 20], ...
	'String',{'to top','one up','one down','to bottom'}, ...
	'Style','popupmenu', ...
	'Tag','Wentrymove', ...
	'Enable','off', ...
	'Value',1);
if nargout > 0, fig = Handles; end
