function Handles=ui_edit(Title),

XX=xx_constants;

GridColor1=75/255*[1 1 1];
GridColor2=100/255*[1 1 1];
GridCell=20;
AreaWidth=25;
AreaHeight=25;
ParameterWidth=0;
VirtualAreaWidth=100;
VirtualAreaHeight=100;
FigWidth=ParameterWidth+GridCell*AreaWidth+XX.Slider;
FigHeight=GridCell*AreaHeight+XX.Slider;

HSlidFcn=['set(gcbo,''value'',round(get(gcbo,''value''))); set(get(gcbo,''userdata''),''xlim'',get(gcbo,''value'')*',num2str(GridCell),'+1+[0 diff(get(get(gcbo,''userdata''),''xlim''))])'];
VSlidFcn=['set(gcbo,''value'',round(get(gcbo,''value''))); set(get(gcbo,''userdata''),''ylim'',get(gcbo,''value'')*',num2str(GridCell),'+1+[0 diff(get(get(gcbo,''userdata''),''ylim''))])'];

ss=get(0,'screensize');

Handles.Figure=figure('color',[0 0 0], ...
     'units','pixels', ...
     'renderer','zbuffer', ...
     'handlevisibility','off', ...
     'integerhandle','off', ...
     'position',[ss(3)-FigWidth-10 ss(4)-FigHeight-40 FigWidth FigHeight], ...
     'menubar','none', ...
     'numbertitle','off', ...
     'name',Title, ...
     'resize','off');


Handles.FileMenu=uimenu('label','&File', ...
        'parent',Handles.Figure, ...
	'Tag','filemenu');
Handles.FileLoad = uimenu('Parent',Handles.FileMenu, ...
	'Label','&Load', ...
        'Callback',['stackudf(gcbf,''CommandStack'',[4 1])'], ...
	'Tag','fileload');
Handles.FileSave = uimenu('Parent',Handles.FileMenu, ...
	'Label','&Save', ...
        'Callback',['stackudf(gcbf,''CommandStack'',[4 2])'], ...
	'Tag','filesave');
Handles.BackGround=axes('units','pixels', ...
     'position',[ParameterWidth+1 XX.Slider+1 GridCell*AreaWidth GridCell*AreaHeight], ...
     'color',[0 0 0], ...
     'xcolor',GridColor1, ...
     'ycolor',GridColor1, ...
     'box','on', ...
     'xticklabel','', ...
     'yticklabel','', ...
     'xtick',[], ...
     'ytick',[], ...
     'xlim',[1 GridCell*AreaWidth], ...
     'ylim',[1 GridCell*AreaHeight], ...
     'ticklength',[0 0], ...
     'hittest','off', ...
     'xgrid','off', ...
     'ygrid','off', ...
     'parent',Handles.Figure);
Handles.Grid=axes('units','pixels', ...
     'position',[ParameterWidth+1 XX.Slider+1 GridCell*AreaWidth GridCell*AreaHeight], ...
     'color',[0 0 0], ...
     'xcolor',GridColor1, ...
     'ycolor',GridColor1, ...
     'box','on', ...
     'xticklabel','', ...
     'yticklabel','', ...
     'xtick',(0:AreaWidth)*GridCell, ...
     'ytick',(0:AreaHeight)*GridCell, ...
     'xlim',[1 GridCell*AreaWidth], ...
     'ylim',[1 GridCell*AreaHeight], ...
     'ticklength',[0 0], ...
     'hittest','off', ...
     'gridlinestyle','-', ...
     'xgrid','on', ...
     'ygrid','on', ...
     'parent',Handles.Figure);
Handles.CoarseGrid=axes('units','pixels', ...
     'position',[ParameterWidth+1 XX.Slider+1 GridCell*AreaWidth GridCell*AreaHeight], ...
     'color','none', ...
     'xcolor',GridColor2, ...
     'ycolor',GridColor2, ...
     'box','on', ...
     'xticklabel','', ...
     'yticklabel','', ...
     'xtick',(0:5:AreaWidth)*GridCell, ...
     'ytick',(0:5:AreaHeight)*GridCell, ...
     'xlim',[1 AreaWidth*GridCell], ...
     'ylim',[1 AreaHeight*GridCell], ...
     'ticklength',[0 0], ...
     'hittest','off', ...
     'gridlinestyle','-', ...
     'xgrid','on', ...
     'ygrid','on', ...
     'parent',Handles.Figure);

Handles.PlotAxesMenu=uicontextmenu( ...
     'parent',Handles.Figure);
Handles.NewProcMenu=uimenu('parent',Handles.PlotAxesMenu, ...
     'label','new process', ...
     'checked','off', ...
     'separator','off', ...
     'enable','on');
uimenu('parent',Handles.PlotAxesMenu, ...
     'label','overview', ...
     'checked','off', ...
     'separator','on', ...
     'callback',['stackudf(gcbf,''CommandStack'',[1 3])'], ...
     'enable','on');
uimenu('parent',Handles.PlotAxesMenu, ...
     'label','done', ...
     'checked','off', ...
     'separator','on', ...
     'callback',['stackudf(gcbf,''CommandStack'',[1 2])'], ...
     'enable','on');

Handles.PlotAxes=axes('units','pixels', ...
     'position',[ParameterWidth+1 XX.Slider+1 AreaWidth*GridCell AreaHeight*GridCell], ...
     'color','none', ...
     'xcolor',GridColor2, ...
     'ycolor',GridColor2, ...
     'box','on', ...
     'xticklabel','', ...
     'yticklabel','', ...
     'xtick',[], ...
     'ytick',[], ...
     'xlim',[1 AreaWidth*GridCell], ...
     'ylim',[1 AreaHeight*GridCell], ...
     'ticklength',[0 0], ...
     'hittest','on', ...
     'uicontextmenu',Handles.PlotAxesMenu, ...
     'xgrid','off', ...
     'ygrid','off', ...
     'parent',Handles.Figure);

Handles.ProcessMenu=uicontextmenu('tag','ProcessMenu', ...
     'parent',Handles.Figure);
uimenu('parent',Handles.ProcessMenu, ...
     'checked','off', ...
     'label','move', ...
     'separator','off', ...
     'callback',['stackudf(gcbf,''CommandStack'',[2 1])'], ...
     'enable','on');
uimenu('parent',Handles.ProcessMenu, ...
     'checked','off', ...
     'label','edit', ...
     'separator','off', ...
     'callback',['stackudf(gcbf,''CommandStack'',[2 3])'], ...
     'enable','on');
uimenu('parent',Handles.ProcessMenu, ...
     'checked','off', ...
     'label','rename', ...
     'separator','off', ...
     'callback',['stackudf(gcbf,''CommandStack'',[2 6])'], ...
     'enable','on');
uimenu('parent',Handles.ProcessMenu, ...
     'checked','off', ...
     'label','input from ...', ...
     'separator','on', ...
     'callback',['stackudf(gcbf,''CommandStack'',[2 5])'], ...
     'enable','on');
uimenu('parent',Handles.ProcessMenu, ...
     'checked','off', ...
     'label','output to ...', ...
     'separator','off', ...
     'callback',['stackudf(gcbf,''CommandStack'',[2 7])'], ...
     'enable','on');
uimenu('parent',Handles.ProcessMenu, ...
     'checked','off', ...
     'label','delete', ...
     'separator','on', ...
     'callback',['stackudf(gcbf,''CommandStack'',[2 2])'], ...
     'enable','on');
uimenu('parent',Handles.ProcessMenu, ...
     'checked','off', ...
     'label','output process', ...
     'separator','on', ...
     'callback',['stackudf(gcbf,''CommandStack'',[2 4])'], ...
     'enable','on');

Handles.InputLinkMenu=uicontextmenu('tag','InputLinkMenu', ...
     'parent',Handles.Figure);
uimenu('parent',Handles.InputLinkMenu, ...
     'checked','off', ...
     'label','delete', ...
     'separator','off', ...
     'callback',['stackudf(gcbf,''CommandStack'',[3 1])'], ...
     'enable','on');

Handles.CornerButton=uicontrol('style','pushbutton',...
     'enable','inactive', ...
     'units','pixels', ...
     'callback','keyboard', ...
     'position',[ParameterWidth+AreaWidth*GridCell+1 1 XX.Slider XX.Slider], ...
     'parent',Handles.Figure);
uplim=max(1,VirtualAreaWidth-AreaWidth);
Handles.HorSlide=uicontrol('style','slider',...
     'units','pixels', ...
     'min',0, ...
     'max',uplim, ...
     'value',0, ...
     'enable','on', ...
     'userdata',Handles.PlotAxes, ...
     'Callback',HSlidFcn, ...
     'sliderstep',[1/uplim min(1,10/uplim)], ... 
     'position',[ParameterWidth+1 1 GridCell*AreaWidth XX.Slider], ...
     'parent',Handles.Figure);
uplim=max(1,VirtualAreaHeight-AreaHeight);
Handles.VerSlide=uicontrol('style','slider',...
     'units','pixels', ...
     'min',0, ...
     'max',uplim, ...
     'value',0, ...
     'enable','on', ...
     'userdata',Handles.PlotAxes, ...
     'Callback',VSlidFcn, ...
     'sliderstep',[1/uplim min(1,10/uplim)], ... 
     'position',[ParameterWidth+GridCell*AreaWidth+1 XX.Slider+1 XX.Slider GridCell*AreaHeight], ...
     'parent',Handles.Figure);