function [standard_name,deltares_name] = donarname2standardnames(code)

parameter_database = { ...
'Fluorescence_in_U_in_surface_water',                                       'sea_water_fluorescence',                'fluorescence'; ...
'Conductivity_in_mS/m_with_respect_to_20_degrees_celsius_in_surface_water', 'sea_water_electrical_conductivity',     'conductivity'; ...
'Irradiation_in_uE_in_air',                                                 'downwelling_longwave_radiance_in_air',  'air_radiance'; ...
'Irradiation_in_uE_in_surface_water',                                       'downwelling_radiance_in_sea_water',     'water_radiance'; ...
'Turbidity_in_NTU_in_surface_water',                                        'sea_water_turbidity',                   'turbidity';...
'Acidity_in_surface_water',                                                 'sea_water_ph_reported_on_total_scale',  'ph'; ...
'Salinity_in_surface_water',                                                'sea_water_salinity',                    'sea_water_salinity'; ...
'Temperature_in_oC_in_surface_water',                                       'sea_water_temperature',                 'temperature'; ...
}