# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for ExpandedQuantity
"""
from .ExpandEntityBase import ExpandEntityBase
from six import string_types

from . import client_support


class ExpandedQuantity(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type code: string_types
        :type definition: ExpandEntityBase
        :type name: string_types
        :type values: list[string_types]
        :rtype: ExpandedQuantity
        """

        return ExpandedQuantity(**kwargs)

    def __init__(self, json=None, **kwargs):
        if json is None and not kwargs:
            raise ValueError('No data or kwargs present')

        class_name = 'ExpandedQuantity'
        data = json or kwargs

        # set attributes
        data_types = [string_types]
        self.code = client_support.set_property('code', data, data_types, False, [], False, True, class_name)
        data_types = [ExpandEntityBase]
        self.definition = client_support.set_property(
            'definition', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.name = client_support.set_property('name', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.values = client_support.set_property('values', data, data_types, False, [], True, True, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
