# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for ExpandedStandard
"""
from .ExpandEntityBase import ExpandEntityBase
from six import string_types

from . import client_support


class ExpandedStandard(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type definition: ExpandEntityBase
        :type institute: string_types
        :type reference: string_types
        :type standardCode: string_types
        :type standardsType: string_types
        :rtype: ExpandedStandard
        """

        return ExpandedStandard(**kwargs)

    def __init__(self, json=None, **kwargs):
        if json is None and not kwargs:
            raise ValueError('No data or kwargs present')

        class_name = 'ExpandedStandard'
        data = json or kwargs

        # set attributes
        data_types = [ExpandEntityBase]
        self.definition = client_support.set_property(
            'definition', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.institute = client_support.set_property('institute', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.reference = client_support.set_property('reference', data, data_types, False, [], False, False, class_name)
        data_types = [string_types]
        self.standardCode = client_support.set_property(
            'standardCode', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.standardsType = client_support.set_property(
            'standardsType', data, data_types, False, [], False, False, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
