# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for ExpandedMeasurementPackage
"""
from .ExpandEntityBase import ExpandEntityBase
from .datetime - only import datetime - only
from six import string_types

from . import client_support


class ExpandedMeasurementPackage(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type attributetypes: list[string_types]
        :type changedate: datetime-only
        :type code: string_types
        :type definition: ExpandEntityBase
        :type description: string_types
        :type exchangesystems: list[string_types]
        :type name: string_types
        :type parameterpackage: string_types
        :type parameters: list[string_types]
        :type parametertypes: list[string_types]
        :type quantitytypes: list[string_types]
        :rtype: ExpandedMeasurementPackage
        """

        return ExpandedMeasurementPackage(**kwargs)

    def __init__(self, json=None, **kwargs):
        if json is None and not kwargs:
            raise ValueError('No data or kwargs present')

        class_name = 'ExpandedMeasurementPackage'
        data = json or kwargs

        # set attributes
        data_types = [string_types]
        self.attributetypes = client_support.set_property(
            'attributetypes', data, data_types, False, [], True, False, class_name)
        data_types = [datetime - only]
        self.changedate = client_support.set_property(
            'changedate', data, data_types, False, [], False, False, class_name)
        data_types = [string_types]
        self.code = client_support.set_property('code', data, data_types, False, [], False, True, class_name)
        data_types = [ExpandEntityBase]
        self.definition = client_support.set_property(
            'definition', data, data_types, False, [], False, False, class_name)
        data_types = [string_types]
        self.description = client_support.set_property(
            'description', data, data_types, False, [], False, False, class_name)
        data_types = [string_types]
        self.exchangesystems = client_support.set_property(
            'exchangesystems', data, data_types, False, [], True, False, class_name)
        data_types = [string_types]
        self.name = client_support.set_property('name', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.parameterpackage = client_support.set_property(
            'parameterpackage', data, data_types, False, [], False, False, class_name)
        data_types = [string_types]
        self.parameters = client_support.set_property(
            'parameters', data, data_types, False, [], True, False, class_name)
        data_types = [string_types]
        self.parametertypes = client_support.set_property(
            'parametertypes', data, data_types, False, [], True, False, class_name)
        data_types = [string_types]
        self.quantitytypes = client_support.set_property(
            'quantitytypes', data, data_types, False, [], True, False, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
