# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for Filter
"""
from six import string_types

from . import client_support


class Filter(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type comparer: string_types
        :type datatype: string_types
        :type fieldname: string_types
        :rtype: Filter
        """

        return Filter(**kwargs)

    def __init__(self, json=None, **kwargs):
        if json is None and not kwargs:
            raise ValueError('No data or kwargs present')

        class_name = 'Filter'
        data = json or kwargs

        # set attributes
        data_types = [string_types]
        self.comparer = client_support.set_property('comparer', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.datatype = client_support.set_property('datatype', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.fieldname = client_support.set_property('fieldname', data, data_types, False, [], False, True, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
