# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for MeasurementObject
"""
from six import string_types

from . import client_support


class MeasurementObject(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type code: string_types
        :type description: string_types
        :type organisation: string_types
        :rtype: MeasurementObject
        """

        return MeasurementObject(**kwargs)

    def __init__(self, json=None, **kwargs):
        if json is None and not kwargs:
            raise ValueError('No data or kwargs present')

        class_name = 'MeasurementObject'
        data = json or kwargs

        # set attributes
        data_types = [string_types]
        self.code = client_support.set_property('code', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.description = client_support.set_property(
            'description', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.organisation = client_support.set_property(
            'organisation', data, data_types, False, [], False, True, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
