# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for Method
"""
from six import string_types

from . import client_support


class Method(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type code: string_types
        :type literature: string_types
        :type methodtype: string_types
        :type methodtypename: string_types
        :type name: string_types
        :type organisation: string_types
        :rtype: Method
        """

        return Method(**kwargs)

    def __init__(self, json=None, **kwargs):
        if json is None and not kwargs:
            raise ValueError('No data or kwargs present')

        class_name = 'Method'
        data = json or kwargs

        # set attributes
        data_types = [string_types]
        self.code = client_support.set_property('code', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.literature = client_support.set_property(
            'literature', data, data_types, False, [], False, False, class_name)
        data_types = [string_types]
        self.methodtype = client_support.set_property(
            'methodtype', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.methodtypename = client_support.set_property(
            'methodtypename', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.name = client_support.set_property('name', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.organisation = client_support.set_property(
            'organisation', data, data_types, False, [], False, True, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
