function OUT = swan_name2shortname(IN)
%SWAN_NAME2SHORTNAME   find short name equivalent of SWAN output parameters
%
% OUT = SWAN_NAME2SHORTNAME(IN) finds short name equivalents of SWAN 
%                               output parameters based in 1st characters
%                               via conversion table.
%
% 1) Case-insensitive to input name, output name is UPPER CASE.
% 2) If name is not in table, input name is returned
% 3) In can be a cell array, output is a cell array.
%
%See also: SWAN_INPUT, SWAN_SPECTRUM, SWAN_TABLE, SWAN_DEFAULTS, SWAN_QUANTITY

if ischar(IN)
   IN = cellstr(IN);
end


for iname = 1:length(IN)

   longname = pad(IN{iname},6,' '); % make sure it's long enought to adress longname(1:6) BELOW
   
   if strcmpi(longname(1:3),'hsw'   ); OUT{iname}  = 'HSW'   ;elseif ... % before HS !!!
      strcmpi(longname(1:2),'hs'    ); OUT{iname}  = 'HS'    ;elseif ...
                                                                     ...     
      strcmpi(longname(1:3),'dir'   ); OUT{iname}  = 'DIR'   ;elseif ...
      strcmpi(longname(1:4),'pdir'  ); OUT{iname}  = 'PDIR'  ;elseif ...
      strcmpi(longname(1:4),'tdir'  ); OUT{iname}  = 'TDIR'  ;elseif ...
                                                                     ...     
      strcmpi(longname(1:4),'tm01'  ); OUT{iname}  = 'TM01'  ;elseif ...
      strcmpi(longname(1:5),'rtm01' ); OUT{iname}  = 'RTM01' ;elseif ...
      strcmpi(longname(1:3),'rtp'   ); OUT{iname}  = 'RTP'   ;elseif ...
      strcmpi(longname(1:3),'per'   ); OUT{iname}  = 'PER'   ;elseif ...
      strcmpi(longname(1:4),'rper'  ); OUT{iname}  = 'RPER'  ;elseif ...
                                                                     ...     
      strcmpi(longname(1:5),'tmm01' ); OUT{iname}  = 'TMM01' ;elseif ...
      strcmpi(longname(1:6),'rtmm01'); OUT{iname}  = 'RTMM01';elseif ...
      strcmpi(longname(1:4),'tm02'  ); OUT{iname}  = 'TM02'  ;elseif ...
      strcmpi(longname(1:4),'fspr'  ); OUT{iname}  = 'FSPR'  ;elseif ...
      strcmpi(longname(1:4),'dspr'  ); OUT{iname}  = 'DSPR'  ;elseif ...
                                                                     ...     
      strcmpi(longname(1:3),'dep'   ); OUT{iname}  = 'DEP'   ;elseif ...
      strcmpi(longname(1:3),'vel'   ); OUT{iname}  = 'VEL'   ;elseif ...
      strcmpi(longname(1:3),'frc'   ); OUT{iname}  = 'FRC'   ;elseif ...
      strcmpi(longname(1:4),'wind'  ); OUT{iname}  = 'WIND'  ;elseif ...
                                                                     ...     
      strcmpi(longname(1:2),'qb'    ); OUT{iname}  = 'QB'    ;elseif ...
      strcmpi(longname(1:3),'tra'   ); OUT{iname}  = 'TRA'   ;elseif ...
      strcmpi(longname(1:3),'for'   ); OUT{iname}  = 'FOR'   ;elseif ...
      strcmpi(longname(1:4),'ubot'  ); OUT{iname}  = 'UBOT'  ;elseif ...
      strcmpi(longname(1:4),'urms'  ); OUT{iname}  = 'URMS'  ;elseif ...
                                                                     ...     
      strcmpi(longname(1:6),'wlenmr'); OUT{iname}  = 'WLENMR';elseif ... % before WLEN !!!
      strcmpi(longname(1:6),'wlenmi'); OUT{iname}  = 'WLENMI';elseif ... % before WLEN !!!
      strcmpi(longname(1:6),'ki'    ); OUT{iname}  = 'KI'    ;elseif ... % before WLEN !!!
      strcmpi(longname(1:4),'wlen'  ); OUT{iname}  = 'WLEN'  ;elseif ...
                                                                     ...     
      strcmpi(longname(1:5),'steep' ); OUT{iname}  = 'STEEP' ;elseif ...
      strcmpi(longname(1:3),'dhs'   ); OUT{iname}  = 'DHS'   ;elseif ...
      strcmpi(longname(1:6),'drtm01'); OUT{iname}  = 'DRTM01';elseif ...
      strcmpi(longname(1:4),'leak'  ); OUT{iname}  = 'LEAK'  ;elseif ...
                                                                     ...     
      strcmpi(longname(1:2),'xp'    ); OUT{iname}  = 'XP'    ;elseif ...
      strcmpi(longname(1:2),'yp'    ); OUT{iname}  = 'YP'    ;elseif ...
      strcmpi(longname(1:4),'dist'  ); OUT{iname}  = 'DIST'  ;elseif ...
      strcmpi(longname(1:5),'setup' ); OUT{iname}  = 'SETUP' ;elseif ...
                                                                     ...     
      strcmpi(longname(1:5),'dissu' ); OUT{iname}  = 'DISSU' ;elseif ... % before DISS !!!
      strcmpi(longname(1:4),'diss'  ); OUT{iname}  = 'DISS'  ;elseif ...
      strcmpi(longname(1:4),'disb'  ); OUT{iname}  = 'DISB'  ;elseif ...
      strcmpi(longname(1:4),'disw'  ); OUT{iname}  = 'DISW'  ;elseif ...
      strcmpi(longname(1:4),'dism'  ); OUT{iname}  = 'DISM'  ;elseif ...
                                                                     ...     
      strcmpi(longname(1:4),'mudl'  ); OUT{iname}  = 'MUDL'  ;else   ...

      OUT{iname} = strtrim(longname); % remove whites added by padding to length=6
   
   end

end