maindir = openearthtoolsroot;

%% Gather all tutorial m-files
alldirs = sort(strread(genpath(maindir),'%s',-1,'delimiter',';'));
alldirs(~cellfun(@isempty,strfind(alldirs,'.svn')))=[];
tutorials = cell(size(alldirs,1),1);
for idr = 1:length(alldirs)
    fls = dir(fullfile(alldirs{idr},'*_tutorial*.m'));
    tutorials{idr} = {fls.name}';
end
id = ~cellfun(@isempty,tutorials);
alldirs(~id)=[];
tutorials(~id)=[];

%% publish mfiles (if not already published)
tutorialmaindir = fullfile(openearthtoolsroot,'tutorials');
tutorialdir = fullfile(tutorialmaindir,'html');

publishopts = struct(...
    'maxOutputLines',15,...
    'format','html',...
    'stylesheet',fullfile(openearthtoolsroot,'maintenance','tutorialGeneration','template','mxdom2tutorialhtmllocal.xsl'),...
    'catchError',true,...
    'outputDir',tutorialdir,...
    'useNewFigure',true,...
    'codeToEvaluate',[]);

cdtemp = cd;
htmlref = cell(size(alldirs));
openfigs = findobj('Type','figure');
for idr = 1:length(alldirs)
    htmlref{idr} = cell(size(tutorials{idr}));
    for itutorials = 1:length(tutorials{idr})
        %% look for html files with the same name
        [dum tutorialname] = fileparts(tutorials{idr}{itutorials});
        htmlfilesthere = which([tutorialname '.html'],'-all');
        id = strncmp(htmlfilesthere,tutorialdir,length(tutorialdir));
        if all(id)
            %% publish file, it is not published yet
            if strcmp(tutorialname(1),'_')
                %% rename the file, because a filename starting with _ won't work
                tutorialname = tutorialname(2:end);
                copyfile(which(tutorials{idr}{itutorials}),fullfile(tempdir,[tutorialname,'.m']));
                cd(tempdir);
            end
            publishopts.codeToEvaluate = ['evalinemptyworkspace(''' tutorialname ''');'];
            %% save reference
            
            htmlref{idr}{itutorials} = publish(tutorialname,publishopts);
            newfigs = findobj('type','figure');
            close(newfigs(~ismember(newfigs,openfigs)));
            
        else
            %% copy html to tutorialdir
            copyfile(htmlfilesthere{find(~id,1,'first')},fullfile(tutorialdir,[tutorialname,'.html']));
            imagesindir = cat(1,...
                dir(fullfile(fileparts(htmlfilesthere{find(~id,1,'first')}),'*.png')),...
                dir(fullfile(fileparts(htmlfilesthere{find(~id,1,'first')}),'*.gif')),...
                dir(fullfile(fileparts(htmlfilesthere{find(~id,1,'first')}),'*.bmp')),...
                dir(fullfile(fileparts(htmlfilesthere{find(~id,1,'first')}),'*.tiff')));
            for iim = 1:length(imagesindir)
                copyfile(fullfile(fileparts(htmlfilesthere{find(~id,1,'first')}),imagesindir(iim).name),...
                    fullfile(tutorialdir,imagesindir(iim).name));
            end
            %% save reference
            htmlref{idr}{itutorials} = fullfile(tutorialdir,[tutorialname,'.html']);
        end
    end
end
cd(cdtemp);

%% ToDO copy script files to html dir (already there, but should be done every time to include the
% newest version of the template

%% Create tutorial overview:
str = [...
    '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">',char(10),...
    '<html xmlns="http://www.w3.org/1999/xhtml">',char(10),...
    '<head>',char(10),...
    char(10),...
    '	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1"/>',char(10),...
    '	<title>Tutorial overview</title>',char(10),...
    char(10),...
    '	<link rel="stylesheet" href="html/script/jquery-treeview/jquery.treeview.css" />',char(10),...
    '   <link rel="stylesheet" href="html/script/css/custom-theme/jquery-ui-1.7.2.custom.css" />',char(10),...
    char(10),...
    '	<script src="html/script/js/jquery-1.3.2.min.js" type="text/javascript"></script>',char(10),...
    '	<script src="html/script/js/matlab2accordion.js" type="text/javascript"></script>',char(10),...
    '	<script src="html/script/js/jquery-ui-1.7.2.custom.min.js" type="text/javascript"></script>',char(10),...
    '	<script src="html/script/jquery-treeview/jquery.treeview.js" type="text/javascript"></script>',char(10),...
    char(10),...
    '	<script type="text/javascript">',char(10),...
    '	$(document).ready(function(){',char(10),...
    '		$(".maintree").treeview({});',char(10),...
    char(10),...
    '		// bind links in treeview',char(10),...
    '		bindlinks();',char(10),...
    '	})',char(10),...
    char(10),...
    '	function bindlinks()',char(10),...
    '		{',char(10),...
    '			$("[class=''file'']").each(function(i)',char(10),...
    '               {',char(10),...
    '               $(this).bind(''click'', {index:i, html:$(this).attr(''ref'')}, loadcontent);',char(10),...
    '				});',char(10),...
    '		}',char(10),...
    char(10),...
    '	function loadcontent(event)',char(10),...
    '		{',char(10),...
    '		$("#contentspanel").load(event.data.html,"html",function()',char(10),...
    '			{',char(10),...
    '			$("document").ajaxStop(linkimages());',char(10),...
    '			});',char(10),...
    '		}',char(10),...
    char(10),...
    '	function linkimages()',char(10),...
    '		{',char(10),...
    '		var images = $("img");',char(10),...
    '		images.each(function(i)',char(10),...
    '			{',char(10),...
    '			$(this).attr(''src'',"html/" + $(this).attr(''src''))',char(10),...
    '			});',char(10),...
    '		}',char(10),...
    char(10),...
    '	</script>',char(10),...
    char(10),...
    '	<style>',char(10),...
    '	#maintree {',char(10),...
    '		width:	15%;',char(10),...
    '		heigth: 100%;',char(10),...
    '       overflow: auto;',char(10),...
    '		float:	left;',char(10),...
    '		}',char(10),...
    char(10),...
    '	#contentspanel {',char(10),...
    '		width:	70%;',char(10),...
    '		height: 100%;',char(10),...
    '		float:	left;',char(10),...
    '       margin: 2px;',char(10),...
    '		}',char(10),...
    '	</style>',char(10),...
    char(10),...
    '	</head>',char(10),...
    '	<body>',char(10),...
    char(10),...
    '	<div id="maintree" class="ui-widget ui-widget-content ui-corner-all">',char(10),...
    '	<ul id="browser" class="filetree treeview maintree">',char(10)];

[alldirsstripped sid] = sort(strrep(alldirs,openearthtoolsroot,''));
htmlref = htmlref(sid);
tutorials = tutorials(sid);

id = strncmp(alldirsstripped,'applications',length('applications'));
idgeneral = find(~id);
idapplications = find(id);

%% general
str = cat(2,str,...
        '		<li><span class="folder">General</span>',char(10),...
        '			<ul>',char(10));
for idr = 1:length(idgeneral)
    dirid = idgeneral(idr);
    dirnames = strread(alldirsstripped{dirid},'%s',-1,'delimiter',[filesep filesep]);
    if length(dirnames) == 1
        for ifiles = 1:length(tutorials{dirid})
            [dum name] = fileparts(htmlref{dirid}{ifiles});
            str = cat(2,str,...
                '<li><a><span class="file" ref="html/',name,'.html">',name,'</span></a></li>',char(10));
        end
    else
        str = cat(2,str,...
            '				<li><span class="folder">', dirnames{end}, '</span>',char(10),...
            '					<ul>',char(10));
        for ifiles = 1:length(tutorials{dirid})
            [dum name] = fileparts(htmlref{dirid}{ifiles});
            str = cat(2,str,...
                '<li><a><span class="file" ref="html/',name,'.html">',name,'</span></a></li>',char(10));
        end
        str = cat(2,str,...
            '					</ul>',char(10),...
            '				</li>',char(10));
    end
end
str = cat(2,str,...
    '			</ul>',char(10),...
    '		</li>',char(10));

%% applications
str = cat(2,str,...
        '		<li><span class="folder">Applications</span>',char(10),...
        '			<ul>',char(10));
for idr = 1:length(idapplications)
    % fill application node
    dirid = idapplications(idr);
    dirnames = strread(alldirsstripped{dirid},'%s',-1,'delimiter',[filesep filesep]);

    str = cat(2,str,...
        '				<li><span class="folder">', dirnames{2}, '</span>',char(10),...
        '					<ul>',char(10));
    for ifiles = 1:length(tutorials{dirid})
        [dum name] = fileparts(htmlref{dirid}{ifiles});
        str = cat(2,str,...
            '<li><a><span class="file" ref="html/',name,'.html">',name,'</span></a></li>',char(10));
    end
    str = cat(2,str,...
        '					</ul>',char(10),...
        '				</li>',char(10));
end
str = cat(2,str,...
    '			</ul>',char(10),...
    '		</li>',char(10));

str = cat(2,str,...
    '	</div>',char(10),...
    char(10),...
    '	<div id="contentspanel" class="ui-widget">',char(10),...
    char(10),...
    '	</div>',char(10),...
    char(10),...
    '</body></html>');

fid = fopen(fullfile(tutorialmaindir,'tutorial_summary.html'),'w');
fprintf(fid,'%s',str);
fclose(fid);

winopen(fullfile(tutorialmaindir,'tutorial_summary.html'));