function refresh(Obj);

AllItems=handles(ob_ideas(Obj));
MainItem=AllItems(1);

UD=get(MainItem,'userdata');
Info=UD.Info;

ErrorMsg='';

% --------
%  Create / update object here
% --------
set(MainItem,'visible',OnOff(Info.Visible));
switch Info.Type,
case 'undefined',
  set(MainItem, ...
      'xlim',[0 1], ...
      'ylim',[0 1], ...
      'zlim',[0 1], ...
      'xtick',[], ...
      'ytick',[], ...
      'ztick',[], ...
      'dataaspectratiomode','auto', ...
      'view',[0 90], ...
      'box','on', ...
      'color','w');
  set(get(MainItem,'xlabel'),'string','');
  set(get(MainItem,'ylabel'),'string','');
  set(get(MainItem,'zlabel'),'string','');
case '2D',
  if ischar(Info.X.Lim),
    XLim=[0 1];
  else,
    XLim=Info.X.Lim;
  end;
  if ischar(Info.Y.Lim),
    YLim=[0 1];
  else,
    YLim=Info.Y.Lim;
  end;
  set(MainItem, ...
      'xlim',XLim, ...
      'ylim',YLim, ...
      'zlim',[0 1], ...
      'xtick',XLim(1)+(0:.1:1)*(XLim(2)-XLim(1)), ...
      'ytick',YLim(1)+(0:.1:1)*(YLim(2)-YLim(1)), ...
      'ztick',[], ...
      'xgrid',OnOff(Info.X.Grid), ...
      'ygrid',OnOff(Info.Y.Grid), ...
      'zgrid','off', ...
      'dataaspectratio',[1 1 1], ...
      'view',[0 90], ...
      'box','on', ...
      'color','w');
  set(get(MainItem,'xlabel'),'string',Info.X.Lbl);
  set(get(MainItem,'ylabel'),'string',Info.Y.Lbl);
  set(get(MainItem,'zlabel'),'string','');
case '3D',
  if ischar(Info.X.Lim),
    XLim=[0 1];
  else,
    XLim=Info.X.Lim;
  end;
  if ischar(Info.Y.Lim),
    YLim=[0 1];
  else,
    YLim=Info.Y.Lim;
  end;
  if ischar(Info.Z.Lim),
    ZLim=[0 1];
  else,
    ZLim=Info.Z.Lim;
  end;
  set(MainItem, ...
      'xlim',XLim, ...
      'ylim',YLim, ...
      'zlim',ZLim, ...
      'xtick',XLim(1)+(0:.1:1)*(XLim(2)-XLim(1)), ...
      'ytick',YLim(1)+(0:.1:1)*(YLim(2)-YLim(1)), ...
      'ztick',ZLim(1)+(0:.1:1)*(ZLim(2)-ZLim(1)), ...
      'xgrid',OnOff(Info.X.Grid), ...
      'ygrid',OnOff(Info.Y.Grid), ...
      'zgrid',OnOff(Info.Z.Grid), ...
      'dataaspectratio',[1 1 1], ...
      'box','on', ...
      'color','w');
  set(get(MainItem,'xlabel'),'string',Info.X.Lbl);
  set(get(MainItem,'ylabel'),'string',Info.Y.Lbl);
  set(get(MainItem,'zlabel'),'string',Info.Z.Lbl);
end;

if ~isempty(ErrorMsg),
  uiwait(msgbox(ErrorMsg,'modal'));
end;

UD.Name=UD.Info.Name;
set(MainItem,'userdata',UD);


function Str=OnOff(L),
if L,
  Str='on';
else,
  Str='off';
end;
