function MDW=ddb_initializeMDW

MDW.WaveFileInformation.FileVersion = '';

MDW.General.ProjectName     = '';
MDW.General.ProjectNr       = '';
MDW.General.Description1    = '';
MDW.General.Description2    = '';
MDW.General.Description3    = '';
MDW.General.OnlyInputVerify = '';
MDW.General.SimMode       = '';
MDW.General.TimeStep      = '';
MDW.General.DirConvention = '';
MDW.General.ReferenceDate = '';
MDW.General.ObstacleFile  = '';
MDW.General.TSeriesFile   = '';
MDW.General.TimePntBlock  = '';
MDW.General.TimePoint     = '';
MDW.General.WaterLevel    = '';
MDW.General.XVeloc        = '';
MDW.General.YVeloc        = '';
MDW.General.WindSpeed     = '';
MDW.General.WindDir       = '';
MDW.General.DirSpace      = '';
MDW.General.NDir          = '';
MDW.General.StartDir      = '';
MDW.General.EndDir        = '';
MDW.General.NFreq         = '';
MDW.General.FreqMin       = '';
MDW.General.FreqMax       = '';

MDW.Constants.Gravity       = '';
MDW.Constants.WaterDensity  = '';
MDW.Constants.NorthDir      = '';
MDW.Constants.MinimumDepth  = '';

MDW.Processes.GenModePhys   = '';
MDW.Processes.WaveSetup     = '';
MDW.Processes.Breaking      = '';
MDW.Processes.BreakAlpha    = '';
MDW.Processes.BreakGamma    = '';
MDW.Processes.Triads        = '';
MDW.Processes.TriadsAlpha   = '';
MDW.Processes.TriadsBeta    = '';
MDW.Processes.BedFriction   = '';
MDW.Processes.BedFriction   = '';
MDW.Processes.BedFricCoef   = '';
MDW.Processes.Diffraction   = '';
MDW.Processes.DiffracCoef   = '';
MDW.Processes.DiffracSteps  = '';
MDW.Processes.DiffracProp   = '';
MDW.Processes.WindGrowth    = '';
MDW.Processes.WhiteCapping  = '';
MDW.Processes.Quadruplets   = '';
MDW.Processes.Refraction    = '';
MDW.Processes.FreqShift     = '';
MDW.Processes.WaveForces    = '';

MDW.Numerics.DirSpaceCDD    = '';
MDW.Numerics.FreqSpaceCSS   = '';
MDW.Numerics.RChHsTm01      = '';
MDW.Numerics.RChMeanHs      = '';
MDW.Numerics.RChMeanTm01    = '';
MDW.Numerics.PercWet        = '';
MDW.Numerics.MaxIter        = '';

MDW.Output.TestOutputLevel  = '';
MDW.Output.TraceCalls       = '';
MDW.Output.UseHotFile       = '';
MDW.Output.MapWriteInterval = '';
MDW.Output.WriteCOM         = '';
MDW.Output.COMWriteInterval = '';
MDW.Output.AppendCOM        = '';
MDW.Output.LocationFile     = '';
MDW.Output.WriteTable       = '';
MDW.Output.WriteSpec1D      = '';
MDW.Output.WriteSpec2D      = '';

for id=1:10
    MDW.Domain(id).Grid           = '';
    MDW.Domain(id).BedLevelGrid   = '';
    MDW.Domain(id).BedLevel       = '';
    MDW.Domain(id).DirSpace       = '';
    MDW.Domain(id).NDir           = '';
    MDW.Domain(id).StartDir       = '';
    MDW.Domain(id).EndDir         = '';
    MDW.Domain(id).NFreq          = '';
    MDW.Domain(id).FreqMin        = '';
    MDW.Domain(id).FreqMax        = '';
    MDW.Domain(id).NestedInDomain = '';
    MDW.Domain(id).FlowBedLevel   = '';
    MDW.Domain(id).FlowWaterLevel = '';
    MDW.Domain(id).FlowVelocity   = '';
    MDW.Domain(id).FlowWind       = '';
    MDW.Domain(id).Output         = '';
end

for id=1:10
    MDW.Boundary(id).Name           = '';
    MDW.Boundary(id).Definition     = '';
    MDW.Boundary(id).Orientation    = '';
    MDW.Boundary(id).DistanceDir    = '';
    MDW.Boundary(id).StartCoordM    = '';
    MDW.Boundary(id).EndCoordM      = '';
    MDW.Boundary(id).StartCoordN    = '';
    MDW.Boundary(id).EndCoordN      = '';
    MDW.Boundary(id).StartCoordX    = '';
    MDW.Boundary(id).EndCoordX      = '';
    MDW.Boundary(id).StartCoordY    = '';
    MDW.Boundary(id).EndCoordY      = '';
    MDW.Boundary(id).SpectrumSpec   = '';
    MDW.Boundary(id).SpShapeType   = '';
    MDW.Boundary(id).PeakEnhancFac = '';
    MDW.Boundary(id).GaussSpread   = '';
    MDW.Boundary(id).PeriodType    = '';
    MDW.Boundary(id).DirSpreadType = '';
    for ii=1:10
        MDW.Boundary(id).List(ii).CondSpecAtDist = '';
        MDW.Boundary(id).List(ii).WaveHeight     = '';
        MDW.Boundary(id).List(ii).Period         = '';
        MDW.Boundary(id).List(ii).Direction      = '';
        MDW.Boundary(id).List(ii).DirSpreading   = '';
    end
    MDW.Boundary(id).WaveHeight     = '';
    MDW.Boundary(id).Period         = '';
    MDW.Boundary(id).Direction      = '';
    MDW.Boundary(id).DirSpreading   = '';
    MDW.Boundary(id).Spectrum       = '';
end

MDW.ObstacleFileInformation.PolygonFile = '';
MDW.Obstacle.Name         = '';
MDW.Obstacle.Type         = '';
MDW.Obstacle.TransmCoef   = '';
MDW.Obstacle.Height       = '';
MDW.Obstacle.Alpha        = '';
MDW.Obstacle.Beta         = '';
MDW.Obstacle.Reflections  = '';
MDW.Obstacle.ReflecCoef   = '';
