var kundo={org:null,base_url:"http://kundo.se",static_base_url:"http://static.kundo.se",lang:"sv",align:"right",top:"200px",image:null,user_name:null,user_email:null,open_startpage:!1,btn_type:1,embed_url:"/embed/landingpage/",image_url:"/images/tycktill-",btn_close_url:"/static/images/kundo-close-",close_text:{sv:"St\u00e4ng",en:"Close",da:"Luk",nb:"Lukk",de:"Schlie\u00dfen",fi:"Sulje","sv-fi":"St\u00e4ng"},old_browser:function(){var a=document.all&&/MSIE/.test(navigator.userAgent);return"BackCompat"==
document.compatMode&&a},third_party_cookies_disabled:function(){return-1!=navigator.userAgent.indexOf("Safari")&&-1==navigator.userAgent.indexOf("Chrome")},get_fixed_style:function(){return kundo.old_browser()?"absolute":"fixed"},obj_to_css:function(a){var b="",c;for(c in a)b+=c+": "+a[c]+"; ";return b},obj_to_url_params:function(a){var b="",c;for(c in a)b+=c+"="+a[c]+"&";return encodeURI(b.slice(0,-1))},obj_to_html:function(a,b,c){c=c||"";var e=-1!=" area base br col command embed hr img input keygen link meta param source track wbr ".indexOf(" "+
a+" "),d="",f;for(f in b)d+=f+'="'+b[f]+'"';d="<"+a+" "+d+">"+c;e||(d+="</"+a+">");return d},get_or_create_div:function(a){var b=document.getElementsByTagName("body")[0],c=document.getElementById(a);c||(c=document.createElement("div"),c.id=a,b.appendChild(c));return c},toggle_box:function(){if(kundo.old_browser()||kundo.third_party_cookies_disabled()||kundo.open_startpage)return!0;if(document.getElementById("kundo_container"))kundo.delete_frame();else{var a=kundo.get_or_create_div("kundo_container");
kundo.create_overlay(a);kundo.create_frame(a)}return!1},create_button:function(a){var b={display:"block",margin:"0",position:kundo.get_fixed_style(),top:kundo.top,"z-index":"99999"};b[kundo.align]=0;var c=kundo.image||kundo.static_base_url+kundo.image_url+kundo.btn_type+"-"+kundo.lang+"-"+kundo.align+".png",b={href:"http://kundo.se/org/"+kundo.org+"/",onclick:"return kundo.toggle_box()",style:kundo.obj_to_css(b)},c={alt:"",id:"kundo_feedback",src:c,style:kundo.obj_to_css({border:"0"})};a.innerHTML+=
kundo.obj_to_html("a",b,kundo.obj_to_html("img",c))},create_overlay:function(a){var b={background:"#000",bottom:"0",filter:"alpha(opacity=70)",left:"0","min-height":"600px",opacity:"0.7",position:kundo.get_fixed_style(),top:"0",width:"100%","z-index":"1000"};if(kundo.old_browser()){var c=Math.max(document.body.clientHeight,document.documentElement.clientHeight);b.height=c+"px"}b={id:"kundo_overlay",style:kundo.obj_to_css(b)};a.innerHTML+=kundo.obj_to_html("div",b)},get_close_button_html:function(){var a=
{style:kundo.obj_to_css({height:"36px",margin:"0 auto","max-width":"1000px",position:"relative",width:"90%","z-index":"100100"})},b={alt:"",id:"kundo_close",onclick:"kundo.delete_frame()",src:kundo.base_url+kundo.btn_close_url+kundo.lang+".gif",style:kundo.obj_to_css({cursor:"pointer",height:"26px",position:"absolute",right:"10px",width:"90px"}),title:kundo.close_text[kundo.lang]};return kundo.obj_to_html("div",a,kundo.obj_to_html("img",b))},create_frame:function(a){var b={bottom:"0",left:"0",height:"560px",
position:kundo.get_fixed_style(),right:0,"text-align":"center",top:"20px",width:"100%","z-index":"100000"},c={lang:kundo.lang};kundo.user_name&&kundo.user_email&&(c.name=kundo.user_name,c.useremail=kundo.user_email);if(kundo.metadata)for(var e in kundo.metadata)c[e]=kundo.metadata[e];b={style:kundo.obj_to_css(b)};c={frameborder:"no",id:"kundo_iframe",scrolling:"no",src:kundo.base_url+kundo.embed_url+kundo.org+"?"+kundo.obj_to_url_params(c),style:kundo.obj_to_css({background:"white",border:"none",
display:"block",height:"100%",margin:"0 auto","max-width":"1000px",width:"90%"})};a.innerHTML+=kundo.obj_to_html("div",b,kundo.get_close_button_html()+kundo.obj_to_html("iframe",c))},delete_frame:function(){var a=kundo.get_or_create_div("kundo_container");a.parentNode.removeChild(a)},init:function(){"https:"==document.location.protocol&&(kundo.static_base_url="https://static-ssl.kundo.se",kundo.base_url="https://kundo.se");var a="",b;for(b in _kundo)a=b.replace("-","_"),kundo[a]=_kundo[b];a=kundo.get_or_create_div("kundo_button_container");
kundo.create_button(a)}};kundo.init();
