function h=gelm_ml_edit(fig,cmdname,hInd,vInd,nLns,visible,enable,text1,cmd1);
if all(nargin~=[8 9]),
  error('Incorrect number of input parameters');
end;
coledit=gelm_col('edit');
if nargin==9,
  cmd1string=[cmdname,'(gcbf,',gui_str(cmd1),')'];
else,
  cmd1string='';
end;
vPos=gelm_vpos(vInd,nLns);
hPos=gelm_hpos(hInd,0);
h=uicontrol('visible',visible, ...
   'units','pixels','position',vPos+hPos, ...
   'style','edit','backgroundcolor',coledit, ...
   'horizontalalignment','left', ...
   'string',text1, ...
   'max',2,...
   'min',0,...
   'enable',enable, ...
   'callback',cmd1string, ...
   'parent',fig);
gelm_font(h);
