function h=gelm_popupmenu(fig,cmdname,hInd,vInd,visible,enable,text1,text2list,text2,cmd);
if all(nargin~=[9 10]),
  error('Incorrect number of input parameters');
end;
coltext=gelm_col('text');
coledit=gelm_col('edit');
if nargin==10,
  cmdstring=[cmdname,'(gcbf,',gui_str(cmd),')'];
else,
  cmdstring='';
end;
vPos=gelm_vpos(vInd);
hPos=gelm_hpos(hInd,2);
if isnumeric(text2),
  index=text2;
else,
  index=strmatch(text2,text2list,'exact');
end;
h(2)=uicontrol('visible',visible, ...
   'units','pixels','position',vPos+hPos, ...
   'style','popupmenu','backgroundcolor',coledit, ...
   'horizontalalignment','left', ...
   'string',text2list, ...
   'enable',enable, ...
   'value',index,...
   'callback',cmdstring, ...
   'parent',fig);
hPos=gelm_hpos(hInd,1);
vPos(4)=18;
h(1)=uicontrol('visible',visible, ...
   'units','pixels','position',vPos+hPos, ...
   'style','text','backgroundcolor',coltext, ...
   'horizontalalignment','right', ...
   'string',text1, ...
   'enable',enable, ...
   'parent',fig);
gelm_font(h);
