function h=gelm_edit(fig,cmdname,hInd,vInd,visible,enable,text1,text2,cmd1,cmd2);
if all(nargin~=[8 9 10]),
  error('Incorrect number of input parameters');
end;
coltext=gelm_col('text');
coledit=gelm_col('edit');
if nargin==10,
  cmd1string=[cmdname,'(gcbf,',gui_str(cmd1),')'];
  cmd2string=[cmdname,'(gcbf,',gui_str(cmd2),')'];
elseif nargin==9,
  cmd1string='';
  cmd2string=[cmdname,'(gcbf,',gui_str(cmd1),')'];
else,
  cmd1string='';
  cmd2string='';
end;
vPos=gelm_vpos(vInd);
hPos=gelm_hpos(hInd,2);
h(2)=uicontrol('visible',visible, ...
   'units','pixels','position',vPos+hPos, ...
   'style','edit','backgroundcolor',coledit, ...
   'horizontalalignment','left', ...
   'string',text2, ...
   'enable',enable, ...
   'callback',cmd2string, ...
   'parent',fig);
hPos=gelm_hpos(hInd,1);
vPos(4)=18;
h(1)=uicontrol('visible',visible, ...
   'units','pixels','position',vPos+hPos, ...
   'style','text','backgroundcolor',coltext, ...
   'horizontalalignment','right', ...
   'string',text1, ...
   'enable',enable, ...
   'buttondownfcn',cmd1string, ...
   'parent',fig);
gelm_font(h);
