function timsel=gui_seltim(timlist),

if isempty(timlist),
  timsel=[];
  return;
end;
Fig_Width=280;
Field_Height=22;
Margin=10;
Fig_Height=3*Margin+3*Field_Height;

ss = get(0,'ScreenSize');
swidth = ss(3);
sheight = ss(4);
left = (swidth-Fig_Width)/2;
bottom = (sheight-Fig_Height)/2;
rect = [left bottom Fig_Width Fig_Height];

fig=figure('menu','none');
set(fig,'units','pixels', ...
        'position',rect, ...
        'inverthardcopy','off', ...
        'resize','off', ...
        'color',get(0,'DefaultUicontrolBackgroundcolor'), ...
        'numbertitle','off', ...
        'closerequestfcn','', ...
        'handlevisibility','off', ...
        'name','Select time ...', ...
        'windowstyle','modal', ...
        'tag','Select Window');

txt1=uicontrol('style','text', ...
          'position',[Margin 2*Margin+2*Field_Height Fig_Width/3-Margin Field_Height-4], ...
          'string','Time:', ...
          'horizontalalignment','left', ...
          'value',1, ...
          'parent',fig');
pum=uicontrol('style','popupmenu', ...
          'position',[Fig_Width/3 2*Margin+2*Field_Height Fig_Width*2/3-Margin Field_Height], ...
          'string',logicalswitch(isempty(timlist),' ',timlist), ...
          'value',1, ...
          'parent',fig, ...
          'callback','set(gcbf,''userdata'',3)');
txt2=uicontrol('style','text', ...
          'position',[Margin 2*Margin+Field_Height Fig_Width/3-Margin Field_Height-4], ...
          'string','Index: 1', ...
          'horizontalalignment','left', ...
          'value',1, ...
          'parent',fig');
sld=uicontrol('style','slider', ...
          'position',[Fig_Width/3 2*Margin+Field_Height Fig_Width*2/3-Margin Field_Height], ...
          'min',1, ...
          'max',max(2,length(timlist)), ...
          'value',1, ...
          'sliderstep',min([1 10]/max(1,length(timlist)),[0.5 1]), ...
          'parent',fig, ...
          'enable',logicalswitch(length(timlist)<2,'off','on'), ...
          'callback','set(gcbf,''userdata'',2)');
con=uicontrol('style','pushbutton', ...
          'position',[Margin Margin Fig_Width-2*Margin Field_Height], ...
          'string','continue', ...
          'parent',fig, ...
          'callback','set(gcbf,''userdata'',1)');
gelm_font([txt1 txt2 pum sld con]);

done=0;
while ~done,
  waitfor(fig,'userdata');
  cmd=get(fig,'userdata');
  set(fig,'userdata',[]);
  switch cmd,
  case 1, %continue
    timsel=get(pum,'value');
    done=1;
  case 2, %slider moved
    timsel=round(get(sld,'value'));
    set(pum,'value',timsel);
    set(sld,'value',timsel);
    set(txt2,'string',['Index: ',gui_str(timsel)]);
  case 3, %popupmenu changed
    timsel=get(pum,'value');
    set(sld,'value',timsel);
    set(txt2,'string',['Index: ',gui_str(timsel)]);
  end;
end;
delete(fig);