%% documentation generator for McTools
% This script generates the documentation for the OpenEarthTools toolbox. 
% It contains several steps:
% 
% # Initialization of the main generation object
% # Specification of the items that appear in the start menu
% # Specification of the items that appear in the contents menu of the help navigator
% # Generation of the documentation
% 
% These steps are further elaborated below.

%% Initialization of the main generation object
% Initialize the documentation object including some general attributes (or
% specifications:
%
% * _name_ The name of the toolbox
% * _targetdir_ is the directory in which the info.xml (main file for the documentation) is placed.
% * _icon_ specifies the image that should be showed as an icon for this toolbox in the start menu
% * _help_location_ specifies the directory name of the location where toc (table of content) files are placed.
% * _helpcontentmainpage_ is the main html page for the highest level in the toc
% * _includesearch_ specifies whether a searchdatabase must be built for this help documentation
% * _includecontents_ specifies whether this toolbox must be incorporated in the help navigator
% * _includeindex_ specifies whether an index file (for the help navigator) must be generated as well
% * _type_ specifies that this is a toolbox
% * _verbose_ indicates whether we want the progress of the generation written to the command window
%

toolboxdoc = tbdocumentation(...
    'name','OpenEarthTools',...
    'targetdir',fullfile(openearthtoolsroot,'docs','OpenEarthDocs'),...
    'icon',which('DeltaresLogo16.PNG'),...
    'help_location','oethelpdocs',...
    'helpcontentmainpage','http://public.deltares.nl/display/OET',...
    'includesearch',false,...
    'includecontents',true,...
    'includeindex',false,...
    'type','toolbox',...
    'verbose','off');

%% Specification of the items that appear in the start menu
% List items have three attributes:
% 
% # _label_ specifies the name of the list item
% # _callback_ specifies the action that has to be performed when the user clicks the item.
% # _icon_ specifies the location of the icon that should be used for this list item.
%
% We have a couple of list items:
%
% # *Help* starts the help navigator
% # *Edit personal config* opens the OET personal config file
% # *Edit Subversion config* opens the subversion config file
% # *Product Page (Web)* starts the webbrowser at the OpenEarthTools website
% # *Repository* starts the webbrowser and goes to the repository

% The Help item
toolboxdoc.listitems(1) = tblistitem(...
    'label','Help',...
    'call','web http://public.deltares.nl/display/OET -helpbrowser',...
    'icon','book_mat');

% The  Edit personal config item
toolboxdoc.listitems(2) = tblistitem(...
    'label','Edit personal config',...
    'call','edit(fullfile(getenv(''APPDATA''), ''OET'', ''config''))',...
    'icon','pageicon');

% The Edit Subversion config item
toolboxdoc.listitems(3) = tblistitem(...
    'label','Edit Subversion config',...
    'call','edit(fullfile(getenv(''APPDATA''), ''Subversion'', ''config''))',...
    'icon','pageicon');

% The Product Page (Web) item
toolboxdoc.listitems(4) = tblistitem(...
    'label','Product Page (Web)',...
    'call','web http://public.deltares.nl/display/OET -browser;',...
    'icon','webicon');

% The repository item
toolboxdoc.listitems(5) = tblistitem(...
    'label','Repository',...
    'call','web https://repos.deltares.nl/repos/OpenEarthTools/trunk/matlab -browser;',...
    'icon','webicon');

%% Specification of the items that appear in the contents menu of the help navigator
% The table of contents in the help navigator has several parts all having 
% their own references to the OpenEarthTools wiki:
%
% * *Getting Started*
% * *OpenEarth Data*
% * *OpenEarth Models*
% * *OpenEarth Tools*
% * *OpenEarth Tutorials
% 
% First the main items are created. The various parts will be dealt with 
% individually below, except for Tips and Tricks. This is just one item
%

% Getting Started
toolboxdoc.contentitems(1) = tbcontentitem(...
    'name','Getting started / Joining OpenEarth',...
    'target','http://public.deltares.nl/display/OET/Join+OpenEarth',...
    'icon','greencircleicon',...
    'children',tbcontentitem);

% OpenEarthData
toolboxdoc.contentitems(2) = tbcontentitem(...
    'name','Data',...
    'target','http://public.deltares.nl/display/OET/Data',...
    'icon','pagesicon',...
    'children',tbcontentitem);

% OpenEarthModels
toolboxdoc.contentitems(3) = tbcontentitem(...
    'name','Models',...
    'target','http://public.deltares.nl/display/OET/Models',...
    'icon','pagesicon',...
    'children',tbcontentitem);

% OpenEarthTools
toolboxdoc.contentitems(4) = tbcontentitem(...
    'name','Tools',...
    'target','http://public.deltares.nl/display/OET/Tools',...
    'icon','pagesicon',...
    'children',tbcontentitem);

% Tutorials
toolboxdoc.contentitems(5) = tbcontentitem(...
    'name','Tutorials',...
    'target','http://public.deltares.nl/display/OET/OpenEarth+tutorials',...
    'icon','pagesicon',...
    'children',tbcontentitem);

%%
% _*OpenEarth Data*_
% This part contains of four references:
%
% # *Raw data repository*
% # *OpenDAP server*
% # *Data Standards* 
% # *Tutorials*
%

% Raw data repository
toolboxdoc.contentitems(2).children(1) = tbcontentitem(...
    'name','Raw data repository',...
    'target','http://repos.deltares.nl/repos/OpenEarthRawData/trunk/',...
    'icon','reficon');

% OpenDAP server
toolboxdoc.contentitems(2).children(2) = tbcontentitem(...
    'name','OpenDAP server',...
    'target','http://dtvirt5.deltares.nl:8080/thredds/catalog/opendap/catalog.html',...
    'icon','reficon');

% Data Standards
toolboxdoc.contentitems(2).children(3) = tbcontentitem(...
    'name','Data Standards',...
    'target','http://public.deltares.nl/display/OET/Data+Collection+Protocol',...
    'icon','pageicon');

% Tutorials
toolboxdoc.contentitems(2).children(4) = tbcontentitem(...
    'name','Tutorials',...
    'target','http://public.deltares.nl/display/OET/Data+tutorials',...
    'icon','pageicon');

%%
% _*OpenEarth Models*_
% This part contains references to model descriptions etc.:
%
% # *Models repository*
%

% Models repository
toolboxdoc.contentitems(3).children(1) = tbcontentitem(...
    'name','Models repository',...
    'target','http://repos.deltares.nl/repos/OpenEarthModels/trunk/',...
    'icon','reficon');

%%
% _*OpenEarth Tools*_
% This part has one main page and also lists the sprint sessions:
%
% # *Tools repository* 
% # *Tools standards*
% # *Toolbox tutorials*
%

% Tools repository
toolboxdoc.contentitems(4).children(1) = tbcontentitem(...
    'name','Tools repository',...
    'target','http://repos.deltares.nl/repos/OpenEarthTools/trunk/',...
    'icon','reficon');

% Tools standards
toolboxdoc.contentitems(4).children(2) = tbcontentitem(...
    'name','Tools standards',...
    'target','http://public.deltares.nl/display/OET/OpenEarth+tools+conventions',...
    'icon','pagesicon',...
    'children',tbcontentitem);
toolboxdoc.contentitems(4).children(2).children(1) = tbcontentitem(...
    'name','Matlab style guide',...
    'target','http://www.mathworks.com/matlabcentral/fileexchange/2529',...
    'icon','matlabicon');
toolboxdoc.contentitems(4).children(2).children(2) = tbcontentitem(...
    'name','Python style guide',...
    'target','http://www.python.org/dev/peps/pep-0008/',...
    'icon','webicon');

%% Toolbox tutorials
toolboxdoc.contentitems(4).children(3) = tbcontentitem(...
    'name','Toolbox tutorials',...
    'target','http://public.deltares.nl/display/OET/OpenEarth+tutorials',...
    'icon','pagesicon');
toolboxdoc.contentitems(4).children(3).children = tbcontentitem(...
    'name','general tutorials',...
    'target','html/dir_generaltutorials.html',...
    'icon','pagesicon');
toolboxdoc.contentitems(4).children(3).children(2) = tbcontentitem(...
    'name','application tutorials',...
    'target','html/dir_applicationtutorials.html',...
    'icon','pagesicon');

%% Load and copy tutorials
load(fullfile(openearthtoolsroot,'tutorials','tutorials_listed.mat'))
tmp = tempname;
mkdir(tmp);
copyfile(fullfile(openearthtoolsroot,'tutorials','html','*'),...
    tmp);
s = strread(genpath(tmp),'%s','delimiter',';');
s(cellfun(@isempty,strfind(s,'.svn')))=[];
for iii = 1:length(s)
    if isdir(s{iii});
       rmdir(s{iii},'s')
    end
end
if ~isdir(fullfile(openearthtoolsroot,'docs','OpenEarthDocs','oethelpdocs','html'))
    mkdir(fullfile(openearthtoolsroot,'docs','OpenEarthDocs','oethelpdocs','html'));
end
copyfile(fullfile(tmp,'*'),...
    fullfile(openearthtoolsroot,'docs','OpenEarthDocs','oethelpdocs','html'),'f');

%% general tutorials
% create dir_generalstr to build a html page with the contents of the general dir
dir_generalstr = ['%% General tutorials',char(10),...
    '%',char(10),...
    '% <html>',char(10),...
    '% <style>',char(10),...
    '% .notediv {',char(10),...
    '%   background-color:   #D8E4F1;',char(10),...
    '%   border:             solid; ',char(10),...
    '%   border-width:       1px;  ',char(10),...
    '%   padding:            10px;',char(10),...
    '%   }',char(10),...
    '% </style>',char(10),...
    '% </html>',char(10),...
    '%' ,char(10),...
    '% <html>',char(10),...
    '%  <ul>',char(10)];

alldirs = unique(cat(1,applicationfolders(:,1),generalfolders(:,1)));
alldirs(:,2:3)=cell(size(alldirs,1),2);

% General tutorials
for igenfile = 1:size(generaltutorials,1)
    if igenfile==1
        toolboxdoc.contentitems(4).children(3).children(1).children = tbcontentitem(...
            'name',strrep(generaltutorials{igenfile,1},'&','&#38'),...
            'target',strrep(fullfile('html',generaltutorials{igenfile,2}),'&','_and_'),...
            'icon','pageicon');
    else
        toolboxdoc.contentitems(4).children(3).children(1).children(igenfile) = tbcontentitem(...
            'name',strrep(generaltutorials{igenfile,1},'&','&#38'),...
            'target',fullfile('html',strrep(generaltutorials{igenfile,2},'&','_and_')),...
            'icon','pageicon');
    end
    dir_generalstr = cat(2,dir_generalstr,...
        ['%   <li><a href="',generaltutorials{igenfile,2} ,'">',generaltutorials{igenfile,1} ,'</a></li>',char(10)]);
end
dir_generalstr = cat(2,dir_generalstr,...
    ['%  </ul>',char(10),...
    '% </html>',char(10),...
    '%',char(10)]);

dirnames = sort(unique(generalfolders(:,1)));
id = nan(length(dirnames),1);
for idirs = 1:length(dirnames)
    id(idirs) = length(toolboxdoc.contentitems(4).children(3).children(1).children)+1;
    toolboxdoc.contentitems(4).children(3).children(1).children(id(idirs)) = tbcontentitem(...
        'name',strrep(strrep(dirnames{idirs},'_',' '),'&','&#38'),...
        'target',strrep(['html/' 'dir_' dirnames{idirs} '.html'],'&','_and_'),...
        'icon','pagesicon');
    fls = sortrows(generalfolders(strcmp(generalfolders(:,1),dirnames{idirs}),:),2);
    
    dir_generalstr = cat(2,dir_generalstr,...
        ['% <html>',char(10),...
        '% <div class="notediv">',char(10),...
        '%   <strong><p>', strrep(dirnames{idirs},'_',' '), '</p></strong>',char(10),...
        '%   <ul>',char(10)]);
    dir_id = strcmp(alldirs(:,1),dirnames{idirs});
    alldirs{dir_id,2} = ['dir_' dirnames{idirs}];
    alldirs{dir_id,3} = [...
        '%% ', dirnames{idirs} ' tutorials' ,char(10),...
        '%' ,char(10),...
        '% <html>',char(10),...
        '% <ul>',char(10)];
   
    for ifiles = 1:size(fls,1)
        if ifiles==1
            toolboxdoc.contentitems(4).children(3).children(1).children(id(idirs)).children = tbcontentitem(...
                'name',fls{ifiles,2},...
                'target',strrep(fullfile('html',fls{ifiles,3}),'&','_and_'),...
                'icon','pageicon');
        else
            toolboxdoc.contentitems(4).children(3).children(1).children(id(idirs)).children(ifiles) = tbcontentitem(...
                'name',fls{ifiles,2},...
                'target',strrep(fullfile('html',fls{ifiles,3}),'&','_and_'),...
                'icon','pageicon');
        end
        dir_generalstr = cat(2,dir_generalstr,...
            ['%   <li><a href="',fls{ifiles,3} ,'">',fls{ifiles,2} ,'</a></li>',char(10)]);
        alldirs{dir_id,3} = cat(2,alldirs{dir_id,3},...
            ['%   <li><a href="',fls{ifiles,3} ,'">',fls{ifiles,2} ,'</a></li>',char(10)]);
    end
    dir_generalstr = cat(2,dir_generalstr,...
        ['%   </ul>',char(10),...
        '% </div>',char(10),...
        '% </html>',char(10),...
        '% ',char(10)]);
    alldirs{dir_id,3} = cat(2,alldirs{dir_id,3},...
        ['%  </ul>',char(10),...
        '% </html>',char(10),...
        '% ',char(10)]);
end

% applications
dir_applicationstr = ['%% Application tutorials',char(10),...
    '%',char(10),...
    '% <html>',char(10),...
    '% <style>',char(10),...
    '% .notediv {',char(10),...
    '%   background-color:   #D8E4F1;',char(10),...
    '%   border:             solid; ',char(10),...
    '%   border-width:       1px;  ',char(10),...
    '%   padding:            10px;',char(10),...
    '%   }',char(10),...
    '% </style>',char(10),...
    '% </html>',char(10),...
    '%' ,char(10)];

dirnames = sort(unique(applicationfolders(:,1)));
id = nan(length(dirnames),1);
for idirs = 1:length(dirnames)
    if idirs==1
        toolboxdoc.contentitems(4).children(3).children(2).children = tbcontentitem(...
            'name',strrep(strrep(dirnames{idirs},'_',' '),'&','&#38'),...
            'target',strrep(['html/' 'dir_' dirnames{idirs} '.html'],'&','_and_'),...
            'icon','pagesicon');
    else
        toolboxdoc.contentitems(4).children(3).children(2).children(idirs) = tbcontentitem(...
            'name',strrep(strrep(dirnames{idirs},'_',' '),'&','&#38'),...
            'target',strrep(['html/' 'dir_' dirnames{idirs} '.html'],'&','_and_'),...
            'icon','pagesicon');
    end
    
    dir_applicationstr = cat(2,dir_applicationstr,...
        ['% <html>',char(10),...
        '% <div class="notediv">',char(10),...
        '%   <strong><p>', strrep(dirnames{idirs},'_',' '), '</p></strong>',char(10),...
        '%   <ul>',char(10)]);
    dir_id = strcmp(alldirs(:,1),dirnames{idirs});
    alldirs{dir_id,2} = ['dir_' dirnames{idirs}];
    alldirs{dir_id,3} = [...
        '%% ', dirnames{idirs} ' tutorials' ,char(10),...
        '%' ,char(10),...
        '% <html>',char(10),...
        '%  <ul>',char(10)];

    fls = sortrows(applicationfolders(strcmp(applicationfolders(:,1),dirnames{idirs}),:),2);
    for ifiles = 1:size(fls,1)
        if ifiles==1
            toolboxdoc.contentitems(4).children(3).children(2).children(idirs).children = tbcontentitem(...
                'name',fls{ifiles,2},...
                'target',strrep(fullfile('html',fls{ifiles,3}),'&','_and_'),...
                'icon','pageicon');
        else
            toolboxdoc.contentitems(4).children(3).children(2).children(idirs).children(ifiles) = tbcontentitem(...
                'name',fls{ifiles,2},...
                'target',strrep(fullfile('html',fls{ifiles,3}),'&','_and_'),...
                'icon','pageicon');
        end
        dir_applicationstr = cat(2,dir_applicationstr,...
            ['%   <li><a href="',fls{ifiles,3} ,'">',fls{ifiles,2} ,'</a></li>',char(10)]);
        alldirs{dir_id,3} = cat(2,alldirs{dir_id,3},...
            ['%   <li><a href="',fls{ifiles,3} ,'">',fls{ifiles,2} ,'</a></li>',char(10)]);
    end
    dir_applicationstr = cat(2,dir_applicationstr,...
        ['%   </ul>',char(10),...
        '% </div>',char(10),...
        '% </html>',char(10),...
        '% ',char(10)]);
    alldirs{dir_id,3} = cat(2,alldirs{dir_id,3},...
        ['%  </ul>',char(10),...
        '% </html>',char(10),...
        '% ',char(10)]);
end

%% Generate dir html files
alldirs = cat(1,alldirs,{'general','dir_generaltutorials',dir_generalstr;...
    'applications','dir_applicationtutorials',dir_applicationstr});
publishtemplate = which('mxdom2tutorialhtmllocal.xsl');
outputhtmldir = fullfile(openearthtoolsroot,'docs','OpenEarthDocs','oethelpdocs','html');

cdtemp = cd;

for ii=1:size(alldirs,1)
    publishopts = publishconfigurations([alldirs{ii,2} '.html'],publishtemplate,outputhtmldir,true);

    tmpdir = tempname;
    mkdir(tmpdir);
    cd(tmpdir);
    
    fid = fopen(strrep(fullfile(tmpdir,[alldirs{ii,2} '.m']),'&','_and_'),'w');
    fprintf(fid,'%s',alldirs{ii,3});
    fclose(fid);
    
    publish(strrep(alldirs{ii,2},'&','_and_'),publishopts);
    
    cd(cdtemp);
    rmdir(tmpdir,'s');
end

%% Generation of the documentation
% Execute the makedocumentation method of the tbtoolbox object. This
% invokes the generation of the necessery info.xml and helptoc.xml.
toolboxdoc = toolboxdoc.makedocumentation;

buildhelpjar(fullfile(toolboxdoc.targetdir,toolboxdoc.help_location));
rmdir(fullfile(toolboxdoc.targetdir,toolboxdoc.help_location,'backup'),'s');
builddocsearchdb(fullfile(toolboxdoc.targetdir,toolboxdoc.help_location));