function inp=sfincs_initialize_input

inp.mmax=0;
inp.nmax=0;
inp.dx=10;
inp.dy=10;
inp.x0=0;
inp.y0=0;
inp.rotation=0;
inp.tref=datestr(floor(now),'yyyymmdd HHMMSS');
inp.tstart=datestr(floor(now),'yyyymmdd HHMMSS');
inp.tstop=datestr(floor(now+1),'yyyymmdd HHMMSS');
inp.dtout=600;
inp.dthisout=600;
inp.dtwnd=1800;
inp.alpha=0.75;
inp.manning=0.04;
inp.manning_land=0.04;
inp.manning_sea=0.04;
inp.rgh_lev_land=0;
inp.zsini=0;
inp.qinf=0;
inp.rhoa=1.25;
inp.rhow=1024;
inp.cd_nr=0;

inp.depfile='sfincs.dep';
inp.mskfile='sfincs.msk';
inp.geomskfile='sfincs.gms';
inp.indexfile='sfincs.ind';
inp.cstfile='';
inp.bndfile='sfincs.bnd';
inp.bzsfile='sfincs.bzs';
inp.bzifile='';
inp.bwvfile='';
inp.bhsfile='';
inp.btpfile='';
inp.bwdfile='';
inp.srcfile='';
inp.disfile='';
inp.hmaxfile='hmax.dat';
inp.hmaxgeofile='hmaxgeo.dat';
inp.zsfile='zs.dat';
inp.vmaxfile='vmax.dat';
inp.spwfile='';
inp.wndfile='';
inp.precipfile='';
inp.obsfile='';
inp.manningfile='';

inp.inputformat='bin';
inp.outputformat='bin';

