%GETWATERBASE2NC_TIME_DIRECT_PLOT   plot netCDF file
%
%   plot and load netCDf file generated by GETWATERBASE2NC_TIME_DIRECT
%
%See also: GETWATERBASE2NC_TIME_DIRECT

   OPT.substance_code = 'id1';
   OPT.station_code   = 'DENHDR';
   OPT.timeframe      = '196101010000-200801010000'
   outputfile         = ['http://dtvirt5.deltares.nl:8080/thredds/dodsC/opendap/rijkswaterstaat/waterbase.nl/sea_surface_height/',...
                          OPT.substance_code,'-',...
                          OPT.station_code,'-',...
                          OPT.timeframe,'_time_direct.nc'];
   
   [D,M]=nc_cf_stationTimeSeries(outputfile,'sea_surface_height')

%%EOF