%ODV2META   script to test ODVRREAD, ODVDISP, ODVPLOT
%
% plots all CTDCAST files in a directory one by one.
%
%See web : <a href="http://odv.awi.de">odv.awi.de</a>
%See also: ODVREAD, ODVDISP, ODVPLOT

% $Id$
% $Date$
% $Author$
% $Revision$
% $HeadURL
% $Keywords:

OPT.directory = 'D:\checkouts\OpenEarthRawData\NIOZ\usergd30d98-data_centre630-260409_result\';
OPT.prefix    = 'result_CTDCAST';
OPT.mask      = '*.txt';
OPT.pause     = 0;

%% File loop

   OPT.files     = dir([OPT.directory,filesep,OPT.prefix,'*',OPT.mask])
   
   clear A
   
   A.lon         = repmat(nan,[1 length(OPT.files)]);
   A.lat         = repmat(nan,[1 length(OPT.files)]);
   A.datenum_min = repmat(nan,[1 length(OPT.files)]);
   A.datenum_max = repmat(nan,[1 length(OPT.files)]);
   A.n           = repmat(nan,[1 length(OPT.files)]);

for ifile=1:length(OPT.files)
   
   OPT.filename = OPT.files(ifile).name;
	
   disp(['Processing ',num2str(ifile),'/',num2str(length(OPT.files)),': ',filename(OPT.filename)])

%% 0 Read raw data

   D         = odvread([OPT.directory,filesep,OPT.filename]);
   
   A.filename{ifile}    = OPT.filename;
   A.lon(ifile)         = D.lon;
   A.lat(ifile)         = D.lat;
   A.datenum_min(ifile) = min(D.data.datenum);
   A.datenum_max(ifile) = max(D.data.datenum);
   A.n(ifile)           = length(D.data.datenum);
   A.bot_depth(ifile)   = D.bot_depth;
   
   if OPT.pause
   pausedisp
   end
       
end % ifile       

%% Plot distribution in space

   figure(1)
   load m_coasts
   plot      (A.lon,A.lat,'.')
   OPT.cticks = 10.^[0:1:2];
   caxis     (log10([OPT.cticks([1 end])]))
   plotc     (A.lon,A.lat,log10(A.n))
   [ax,h]=colorbarwithtitle('n [#]',log10(OPT.cticks));
   set(ax,'yticklabel',num2str(OPT.cticks'))
   hold on
   plot      (ncst(:,1),ncst(:,2),'k')
   axislat   (52)
   axis([min(A.lon) max(A.lon) min(A.lat) max(A.lat)])%axis      ([-5 10 48 60])
   grid       on
   tickmap   ('ll')
   box        on
   print2screensize([OPT.directory,filesep,'inventory_space.png'])

%% Plot distribution in time

   figure(2)
   
   t = A.datenum_min;t(t==0)=nan;% remove 0's from datenum
   H.edges = floor(min(t)):1:ceil(max(t));
   [H.n,H.bin]=histc(A.datenum_min,H.edges)
   bar(H.edges,H.n,'histc')
   datetick('x')
   grid on
   ylabel('n[#]')
   print2screensize([OPT.directory,filesep,'inventory_time.png'])

%% Save

   units.filename    = 'string';
   units.lon         = 'degrees_east';
   units.lat         = 'degrees_north';
   units.nt          = '#';
   units.datenum_min = 'days since 0000 00:00';
   units.datenum_max = 'days since 0000 00:00';
   units.bot_depth   = 'm';
   
   A.filename = char(A.filename);

   header = {'Generated by $Id$',...
             ['This file has been created with struct2xls.m > xlswrite.m @ ',datestr(now)]};

   struct2xls([OPT.directory,filesep,'inventory.xls'],A,'units',units,'header',header)

