%ODV2META   extract meta inform from all ODV files in one directory, plot it, and export to Excel table
%
%  reads standard meta info from all ODV files 
%  a directory, make a plan view plot and saves table to excel file.
%  The following <keyword,value> pairs have been implemented:
%
%   * directory_nc   directory where to put the nc data to (default [])
%   * mask           file mask (default '*.nc')
%   * basename       name of *.png and *.xls ot output files (default '_inventory')
%
%See web : <a href="http://odv.awi.de">odv.awi.de</a>
%See also: ODVDISP

OPT.directory    = 'F:\checkouts\OpenEarthTools\matlab\applications\OceanDataView\usergd30d98-data_centre630-260409_result\';
OPT.mask         = '*.txt';
OPT.basename     = '_inventory';
OPT.datestr      = 'yyyy-mm-dd HH:MM:SS';

%% File loop to get meta-data
%------------------

OPT.files     = dir([OPT.directory,filesep,OPT.mask])

for ifile=1:length(OPT.files)

   disp([num2str(ifile),'/',num2str(length(OPT.files))])

    OPT.filename = OPT.files(ifile).name;

    D = odvread([OPT.directory,filesep,OPT.filename]);
    
    files(ifile).cruise     = D.data.cruise{1};
    files(ifile).station_id = D.data.station{1};
    files(ifile).datenum    = D.data.datenum(1);
    files(ifile).lon        = D.data.lon(1);
    files(ifile).lat        = D.data.lat(1);
    files(ifile).nt         = sum(~isnan(D.data.datenum));
           
end % ifile       

%% Reorganize meta-data
%------------------

   A.filename    = {OPT.files.name};
   A.lat         = [files.lat];
   A.lon         = [files.lon];
   A.nt          = [files.nt];
   A.datenum     = [files.datenum];
   A.datestr     = datestr(A.datenum);
   
   A.station_id  = {files.station_id};
   if isnumeric(A.station_id{1})
   A.station_id = num2str(cell2mat(A.station_id)');
   else
   A.station_id = char   (A.station_id); % cell2  char
   end

   units.filename    = 'string';
   units.lat         ='degrees_north';
   units.lon         = 'degrees_east';
   units.nt          = '# of observations';
   units.datenum     = 'days since 0000-00-00 00:00:00';
   units.datestr     = OPT.datestr;
   units.station_id  = 'string';

% Plot locations
%--------------------
   TMP = figure;
   plot   (A.lon,A.lat,'ko','linewidth',2)
   hold    on
   plotc  (A.lon,A.lat,A.nt,'o','linewidth',2)
   axislat(52)
   tickmap('ll')
   caxis  ([min(A.nt) max(A.nt)])
   colorbarwithtitle('n [#]')
   grid    on
   hold    on
   title  ({mktex(OPT.directory),['# stations: ',num2str(length(OPT.files))]})
   
   print2screensize([OPT.directory,filesep,OPT.basename,'.png'])

% Save all meta-data
%--------------------
   A.filename   = char(A.filename);
   
   header = {'Generated by $Id$',...
             ['This file has been created with struct2xls.m > xlswrite.m @ ',datestr(now)]};
   
   struct2xls([OPT.directory,filesep,OPT.basename,'.xls'],A,'units',units,'header',header)
