function varargout = nc_cf_grid_mapping(epsg,varargin)
%NC_CF_GRID_MAPPING   get CF mapping attributes from epsg code
%
%    S        = nc_cf_grid_mapping(epsg)
%   [S,<WKT>] = nc_cf_grid_mapping(epsg)
%
% where struct S can be used as the set of attributes 
% of the grid_mapping variable as described in
% http://cf-pcmdi.llnl.gov/documents/cf-conventions/1.4/cf-conventions.html#grid-mappings-and-projections
% http://cf-pcmdi.llnl.gov/documents/cf-conventions/1.4/cf-conventions.html#appendix-grid-mappings
%
% where WKT is the well-known-text representation.
%
% Example:
%
%    S = nc_cf_grid_mapping(23031) % 'ED50 / UTM zone 31N'
%    nc.Name         = 'crs';
%    nc.Nctype       = nc_int;
%    nc.Dimension    = {};
%    nc.Attribute    = S;
%    nc_addvar(ncfile, nc);   
%
%see also: convertcoordinates, nc_cf_grid

%%  --------------------------------------------------------------------
%   Copyright (C) 2010 Deltares for Building with Nature
%
%       Gerben de Boer
%
%       gerben.deboer@deltares.nl	
%
%       Deltares
%       P.O. Box 177
%       2600 MH Delft
%       The Netherlands
%
%   This library is free software: you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation, either version 3 of the License, or
%   (at your option) any later version.
%
%   This library is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
%
%   You should have received a copy of the GNU General Public License
%   along with this library.  If not, see <http://www.gnu.org/licenses/>.
%   --------------------------------------------------------------------

% TO DO: fill WKT with parameters automatically

OPT.debug = 0;

[dummy,dummy,log] = convertcoordinates(1,1,'CS1.code',epsg,'CS2.code',4326);

if OPT.debug
   var2evalstr(log)
end

% TO DO: use Appendix F. Grid Mappings
% -------------------------
% . albers_conical_equal_area
% . azimuthal_equidistant
% . lambert_azimuthal_equal_area
% . lambert_conformal_conic
% . lambert_cylindrical_equal_area
% . latitude_longitude
% . mercator
% . orthographic
% . polar_stereographic
% . rotated_latitude_longitude
% . stereographic
% x transverse_mercator
% . vertical_perspective

if ~strcmpi(log.CS1.type,'geographic 2D'); % e.g. ED50 4230, WGS84 4326

   if strcmpi(log.proj_conv1.method.name,'Transverse Mercator') OPT.grid_mapping_name = 'transverse_mercator'
   else                                                         OPT.grid_mapping_name = '';
   end

   S = struct('Name', ...
       {'name',...
        'epsg', ...
        'epsg_name', ...
        'grid_mapping_name',...
        'semi_major_axis', ...
        'semi_minor_axis', ...
        'inverse_flattening', ...
        'latitude_of_projection_origin', ...
        'longitude_of_projection_origin', ...
        'false_easting', ...
        'false_northing', ...
        'scale_factor_at_projection_origin', ...
        'comment'}, ...
        'Value', ...
        {log.CS1.name,...
         epsg,     ...
         log.proj_conv1.method.name,     ...
         OPT.grid_mapping_name,     ...
         log.CS1.ellips.semi_major_axis, ...
         log.CS1.ellips.semi_minor_axis, ...
         log.CS1.ellips.inv_flattening,  ...
         log.proj_conv1.param.value(strcmp(log.proj_conv1.param.name,'Latitude of natural origin'    )),...
         log.proj_conv1.param.value(strcmp(log.proj_conv1.param.name,'Longitude of natural origin'   )),...
         log.proj_conv1.param.value(strcmp(log.proj_conv1.param.name,'False easting'                 )),...
         log.proj_conv1.param.value(strcmp(log.proj_conv1.param.name,'False northing'                )),...
         log.proj_conv1.param.value(strcmp(log.proj_conv1.param.name,'Scale factor at natural origin')),...
        'value is equal to EPSG code'});
else        

   S = struct('Name', ...
    {'name',...
     'epsg', ...
     'grid_mapping_name',...
     'semi_major_axis', ...
     'semi_minor_axis', ...
     'inverse_flattening', ...
     'comment'}, ...
     'Value', ...
     {log.CS2.name,...
      epsg,     ...
     'latitude_longitude',...
      log.CS2.ellips.semi_major_axis, ...
      log.CS2.ellips.semi_minor_axis, ...
      log.CS2.ellips.inv_flattening,  ...
     'value is equal to EPSG code'});
     
end

if OPT.debug
   var2evalstr(S)
end

if nargout==1

   varargout = {S}

else

   WKT = [];
   
   switch epsg
       case 28355 % GDA94 / MGA zone 55
           WKT = ['PROJCS["GDA94 / MGA zone 55",' char(10) ...
               '    GEOGCS["GDA94",' char(10) ...
               '        DATUM["Geocentric_Datum_of_Australia_1994",' char(10) ...
               '            SPHEROID["GRS 1980",6378137,298.257222101,' char(10) ...
               '                AUTHORITY["EPSG","7019"]],' char(10) ...
               '            TOWGS84[0,0,0,0,0,0,0],' char(10) ...
               '            AUTHORITY["EPSG","6283"]],' char(10) ...
               '        PRIMEM["Greenwich",0,' char(10) ...
               '            AUTHORITY["EPSG","8901"]],' char(10) ...
               '        UNIT["degree",0.01745329251994328,' char(10) ...
               '            AUTHORITY["EPSG","9122"]],' char(10) ...
               '        AUTHORITY["EPSG","4283"]],' char(10) ...
               '    UNIT["metre",1,' char(10) ...
               '        AUTHORITY["EPSG","9001"]],' char(10) ...
               '    PROJECTION["Transverse_Mercator"],' char(10) ...
               '    PARAMETER["latitude_of_origin",0],' char(10) ...
               '    PARAMETER["central_meridian",147],' char(10) ...
               '    PARAMETER["scale_factor",0.9996],' char(10) ...
               '    PARAMETER["false_easting",500000],' char(10) ...
               '    PARAMETER["false_northing",10000000],' char(10) ...
               '    AUTHORITY["EPSG","28355"],' char(10) ...
               '    AXIS["Easting",EAST],' char(10) ...
               '    AXIS["Northing",NORTH]]'];
       case 28992
           WKT = ['PROJCS["Amersfoort / RD New",' char(10) ...
               '    GEOGCS["Amersfoort",' char(10) ...
               '        DATUM["Amersfoort",' char(10) ...
               '            SPHEROID["Bessel 1841",6377397.155,299.1528128,' char(10) ...
               '                AUTHORITY["EPSG","7004"]],' char(10) ...
               '            AUTHORITY["EPSG","6289"]],' char(10) ...
               '        PRIMEM["Greenwich",0,' char(10) ...
               '            AUTHORITY["EPSG","8901"]],' char(10) ...
               '        UNIT["degree",0.01745329251994328,' char(10) ...
               '            AUTHORITY["EPSG","9122"]],' char(10) ...
               '        AUTHORITY["EPSG","4289"]],' char(10) ...
               '    UNIT["metre",1,' char(10) ...
               '        AUTHORITY["EPSG","9001"]],' char(10) ...
               '    PROJECTION["Oblique_Stereographic"],' char(10) ...
               '    PARAMETER["latitude_of_origin",52.15616055555555],' char(10) ...
               '    PARAMETER["central_meridian",5.38763888888889],' char(10) ...
               '    PARAMETER["scale_factor",0.9999079],' char(10) ...
               '    PARAMETER["false_easting",155000],' char(10) ...
               '    PARAMETER["false_northing",463000],' char(10) ...
               '    AUTHORITY["EPSG","28992"],' char(10) ...
               '    AXIS["X",EAST],' char(10) ...
               '    AXIS["Y",NORTH]]'];
       case 29902
           WKT = ['PROJCS["TM65 / Irish Grid",' char(10) ...
           '    GEOGCS["TM65",' char(10) ...
           '        DATUM["TM65",' char(10) ...
           '            SPHEROID["Airy Modified 1849",6377340.189,299.3249646,' char(10) ...
           '                AUTHORITY["EPSG","7002"]],' char(10) ...
           '            AUTHORITY["EPSG","6299"]],' char(10) ...
           '        PRIMEM["Greenwich",0,' char(10) ...
           '            AUTHORITY["EPSG","8901"]],' char(10) ...
           '        UNIT["degree",0.01745329251994328,' char(10) ...
           '            AUTHORITY["EPSG","9122"]],' char(10) ...
           '        AUTHORITY["EPSG","4299"]],' char(10) ...
           '    UNIT["metre",1,' char(10) ...
           '        AUTHORITY["EPSG","9001"]],' char(10) ...
           '    PROJECTION["Transverse_Mercator"],' char(10) ...
           '    PARAMETER["latitude_of_origin",53.5],' char(10) ...
           '    PARAMETER["central_meridian",-8],' char(10) ...
           '    PARAMETER["scale_factor",1.000035],' char(10) ...
           '    PARAMETER["false_easting",200000],' char(10) ...
           '    PARAMETER["false_northing",250000],' char(10) ...
           '    AUTHORITY["EPSG","29902"],' char(10) ...
           '    AXIS["Easting",EAST],' char(10) ...
           '    AXIS["Northing",NORTH]]'];
   end

   varargout = {S,WKT}

end
