function varargout = nc_cf_standard_names(varargin)
%NC_CF_STANDARD_NAMES  Routine facilitates adding variables that are part of standard-name glossaries
%
%   Routine facilitates adding variables that are part of standard-name glossaries (CF-1.4, OE-1.0, VO-1.0).
%   Works with both the Maltab and SNC netcdf libraries.   
%
%   Syntax:
%      nc_cf_standard_names(varargin)
%
%   Example:
%
%      nc_cf_standard_names('outputfile', outputfile, ...
%                           'varname',   {'x'}, ...
%                           'cf_standard_name', {'projection_x_coordinate'}, ...
%                           'dimension', {'time'})
%
%   Standard names supported:
%        (CF-1.4) 'altitude'
%        (CF-1.4) 'depth'
%        (CF-1.4) 'latitude'
%        (CF-1.4) 'longitude'
%        (CF-1.4) 'projection_x_coordinate'
%        (CF-1.4) 'projection_y_coordinate'
%        (CF-1.4) 'sea_surface_swell_wave_mean_period_from_variance_spectral_density_first_frequency_moment'
%        (CF-1.4) 'sea_surface_swell_wave_significant_height'
%        (CF-1.4) 'sea_surface_swell_wave_to_direction'
%        (CF-1.4) 'sea_surface_wave_zero_upcrossing_period'
%        (CF-1.4) 'sea_surface_wave_mean_period_from_variance_spectral_density_first_frequency_moment'
%        (CF-1.4) 'sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment'
%        (CF-1.4) 'sea_surface_wave_significant_height'
%        (CF-1.4) 'sea_surface_wave_to_direction'
%        (CF-1.4) 'sea_surface_wind_wave_mean_period_from_variance_spectral_density_first_frequency_moment'
%        (CF-1.4) 'sea_surface_wind_wave_significant_height'
%        (CF-1.4) 'sea_surface_wind_wave_to_direction'
%        (CF-1.4) 'wind_speed'
%        (CF-1.4) 'wind_to_direction'
%        (CF-1.4) 'sea_water_x_velocity'
%        (CF-1.4) 'sea_water_y_velocity'
%        (CF-1.4) 'northward_sea_water_velocity'
%        (CF-1.4) 'eastward_sea_water_velocity'
%        (CF-1.4) 'direction_of_sea_water_velocity'
%        (CF-1.4) 'radial_sea_water_velocity_away_from_instrument'
%        (CF-1.4) 'mass_concentration_of_suspended_matter_in_sea_water'
%        (CF-1.4) 'water_surface_height_above_reference_datum'
%        (CF-1.4) 'water_surface_reference_datum_altitude'
%
%   See also nc_cf_standard_names_generate

%% Copyright notice
%   --------------------------------------------------------------------
%   Copyright (C) 2009 Van Oord
%       Mark van Koningsveld
%
%       mrv@vanoord.com
%
%       Watermanweg 64
%       POBox 8574
%       3009 AN Rotterdam
%       Netherlands
%
%   This library is free software: you can redistribute it and/or
%   modify it under the terms of the GNU Lesser General Public
%   License as published by the Free Software Foundation, either
%   version 2.1 of the License, or (at your option) any later version.
%
%   This library is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%   Lesser General Public License for more details.
%
%   You should have received a copy of the GNU Lesser General Public
%   License along with this library. If not, see <http://www.gnu.org/licenses/>.
%   --------------------------------------------------------------------

% This tools is part of VOTools which is the internal clone of <a href="http://OpenEarth.Deltares.nl">OpenEarthTools</a>.
% OpenEarthTools is an online collaboration to share and manage data and
% programming tools in an open source, version controlled environment.
% Sign up to recieve regular updates of this function, and to contribute
% your own tools.

%% Version <http://svnbook.red-bean.com/en/1.5/svn.advanced.props.special.keywords.html>
% Created: 13 Nov 2009
% Created with Matlab version: 7.7.0.471 (R2008b)

% $Id$
% $Date$
% $Author$
% $Revision$
% $HeadURL$
% $Keywords: $

%% settings

% defaults
fillValues.double =  typecast(uint8([0    0    0    0    0    0  158   71]),'DOUBLE');            
fillValues.float  =  typecast(uint8([                    0    0  240  124]),'SINGLE');
fillValues.int    =  typecast(uint8([                    1    0    0  128]),'INT32' );
fillValues.short  =  typecast(uint8([                              1  128]),'INT16' );
fillValues.byte   =  typecast(uint8(                                  129 ),'INT8'  );
fillValues.char   =  char(0);

OPT = struct(...
    'nc_library',       'snc', ...                           % snc or matlab 
    'ncid',             '', ...                              % nectdf id (only for matlab library)
    'outputfile',       {[]}, ...                            % name of the nc file. 
    'varname',          {{{'test1'};{'test2'}}}, ...         % variable name
    'cf_standard_name', {{{'test1'};{'test2'}}}, ...         % cf (climate forecasting) standard name
    'dimension',        {{{'test1'};{'test2'}}}, ...	     % dimension names					
    'dimid',            [], ...                              % dimension id's for use with matlab nc library only
    ...                                                      %   It is (a little) faster to indicate dimid's than dimension names
    'timezone',         '+01:00' , ...                       % timezone
    'deflate',          false , ...                          % only for netcdf4 files, internally deflates (compresses) variables in NC file
    'additionalAtts',   {[]}, ...                            % append these attributes to the default attributes. Must be in form
    ...                                                      %    {'name1','name2','name3';'value1','value2','value3'}
    'fillValues',       fillValues ...                       % fill values for different variable classes     
    ); 

% overrule default settings by property pairs, given in varargin
OPT = setproperty(OPT, varargin{:});

%% check some basic input properties
if size(OPT.cf_standard_name,1) ~= size(OPT.dimension,1)
    error('nc_cf_standard_names:argChk', 'Input arguments not of equal length')
end

switch OPT.nc_library
    case 'snc'
        if isempty(OPT.outputfile)
            error('nc_cf_standard_names:outputChk',  'No outputfilename indicated')
        end
    case 'matlab'
        if isempty(OPT.ncid)
            error('nc_cf_standard_names:outputChk',  'No ncid indicated')
        end
    otherwise
        error('nc_cf_standard_names:outputChk',  'unknown nc_library, only snc and matlab are supported')
end

%% one by one add each variable
for i = 1:size(OPT.cf_standard_name,1)
    switch OPT.cf_standard_name{i}
        case 'altitude'
            % add variable: altitude
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'altitude', 'altitude', 'm', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'depth'
            % add variable: depth
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'depth', 'depth', 'm', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'latitude'
            % add variable: latitude
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'double', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'latitude', 'latitude', 'degree_north', OPT.fillValues.double} ...
                   ) ...
                );
 
        case 'longitude'
            % add variable: longitude
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'double', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'longitude', 'longitude', 'degree_east', OPT.fillValues.double} ...
                   ) ...
                );
 
        case 'projection_x_coordinate'
            % add variable: projection_x_coordinate
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'double', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'projection_x_coordinate', 'x-coordinate', 'm', OPT.fillValues.double} ...
                   ) ...
                );
 
        case 'projection_y_coordinate'
            % add variable: projection_y_coordinate
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'double', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'projection_y_coordinate', 'y-coordinate', 'm', OPT.fillValues.double} ...
                   ) ...
                );
 
        case 'sea_surface_swell_wave_mean_period_from_variance_spectral_density_first_frequency_moment'
            % add variable: sea_surface_swell_wave_mean_period_from_variance_spectral_density_first_frequency_moment
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'sea_surface_swell_wave_mean_period_from_variance_spectral_density_first_frequency_moment', 'Mean wave period T-10 (Swell)', 's', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'sea_surface_swell_wave_significant_height'
            % add variable: sea_surface_swell_wave_significant_height
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'sea_surface_swell_wave_significant_height', 'Significant wave height (Swell)', 'm', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'sea_surface_swell_wave_to_direction'
            % add variable: sea_surface_swell_wave_to_direction
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'sea_surface_swell_wave_to_direction', 'Mean wave direction Theta (Swell)', 'degree', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'sea_surface_wave_zero_upcrossing_period'
            % add variable: sea_surface_wave_zero_upcrossing_period
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'sea_surface_wave_zero_upcrossing_period', 'Mean period time Tz', 's', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'sea_surface_wave_mean_period_from_variance_spectral_density_first_frequency_moment'
            % add variable: sea_surface_wave_mean_period_from_variance_spectral_density_first_frequency_moment
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'sea_surface_wave_mean_period_from_variance_spectral_density_first_frequency_moment', 'Mean wave period (1st frequency moment)', 's', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment'
            % add variable: sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment', 'Mean wave period (2nd frequency moment)', 's', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'sea_surface_wave_significant_height'
            % add variable: sea_surface_wave_significant_height
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'sea_surface_wave_significant_height', 'Significant wave height (Sea and Swell)', 'm', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'sea_surface_wave_to_direction'
            % add variable: sea_surface_wave_to_direction
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'sea_surface_wave_to_direction', 'Mean wave direction Theta (Sea and Swell)', 'degree', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'sea_surface_wind_wave_mean_period_from_variance_spectral_density_first_frequency_moment'
            % add variable: sea_surface_wind_wave_mean_period_from_variance_spectral_density_first_frequency_moment
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'sea_surface_wind_wave_mean_period_from_variance_spectral_density_first_frequency_moment', 'Mean wave period T-10 (Sea)', 's', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'sea_surface_wind_wave_significant_height'
            % add variable: sea_surface_wind_wave_significant_height
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'sea_surface_wind_wave_significant_height', 'Significant wave height (Sea)', 'm', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'sea_surface_wind_wave_to_direction'
            % add variable: sea_surface_wind_wave_to_direction
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'sea_surface_wind_wave_to_direction', 'Mean wave direction Theta (Sea)', 'degree', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'wind_speed'
            % add variable: wind_speed
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'wind_speed', 'Wind speed', 'm/s', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'wind_to_direction'
            % add variable: wind_to_direction
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'wind_to_direction', 'Wind direction', 'degree', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'sea_water_x_velocity'
            % add variable: sea_water_x_velocity
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'sea_water_x_velocity', 'Sea water x velocity', 'm/s', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'sea_water_y_velocity'
            % add variable: sea_water_y_velocity
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'sea_water_y_velocity', 'Sea water y velocity', 'm/s', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'northward_sea_water_velocity'
            % add variable: northward_sea_water_velocity
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'northward_sea_water_velocity', 'Sea water northward velocity', 'm/s', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'eastward_sea_water_velocity'
            % add variable: eastward_sea_water_velocity
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'eastward_sea_water_velocity', 'Sea water eastward velocity', 'm/s', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'direction_of_sea_water_velocity'
            % add variable: direction_of_sea_water_velocity
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'direction_of_sea_water_velocity', 'Sea water velocity direction', 'degree', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'radial_sea_water_velocity_away_from_instrument'
            % add variable: radial_sea_water_velocity_away_from_instrument
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'radial_sea_water_velocity_away_from_instrument', 'Sea water velocity direction', 'm/s', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'mass_concentration_of_suspended_matter_in_sea_water'
            % add variable: mass_concentration_of_suspended_matter_in_sea_water
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'mass_concentration_of_suspended_matter_in_sea_water', 'Mass concentration of suspended matter in sea water', 'kg/m3', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'water_surface_height_above_reference_datum'
            % add variable: water_surface_height_above_reference_datum
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'float', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'water_surface_height_above_reference_datum', 'Water surface height above reference datum', 'm', OPT.fillValues.float} ...
                   ) ...
                );
 
        case 'water_surface_reference_datum_altitude'
            % add variable: water_surface_reference_datum_altitude
            Variable = struct(...
               'Name',       OPT.varname{i} , ...
               'Nctype',    'char', ... 
               'Dimension', {OPT.dimension(i,:)}, ... 
               'Attribute', struct( ... 
                   'Name', ... 
                   {'standard_name', 'long_name', 'units', '_FillValue'}, ...
                   'Value', ... 
                   {'water_surface_reference_datum_altitude', 'Water surface referernce datum altitude', 'm', OPT.fillValues.char} ...
                   ) ...
                );
 
    end

    % append additional attributes
    for jj = 1:size(OPT.additionalAtts,2)
        Variable.Attribute(end+1).Name  = OPT.additionalAtts{1,jj};
        Variable.Attribute(end+0).Value = OPT.additionalAtts{2,jj};
    end
    
    % add variable to output file
    switch OPT.nc_library
        case 'snc'
            nc_addvar(OPT.outputfile, Variable);
            varargout = {[]};
        case 'matlab'
            varid = netcdf_addvar(OPT.ncid, Variable );
            if OPT.deflate
                netcdf.defVarDeflate(OPT.ncid,varid,false,true,2);
            end
            varargout = {varid};
    end
end
