%extract meta-data from dynamic catalog to populate meta-data in static catalog
%
%See also: nc_cf_harvest

%% GRIDS   
%  This static catalog is hosted at as test at:
%  http://dtvirt5.deltares.nl:8080/thredds/rijkswaterstaat_kustlidar_catalog1.html
   
%   ncdir    = 'http://dtvirt5.deltares.nl:8080/thredds/catalog/opendap/rijkswaterstaat/kustlidar/catalog.html';
%   xmldir   =            'F:\opendap.deltares.nl\thredds\dodsC\opendap\rijkswaterstaat\kustlidar\';
%
%   disp(['Crawling ...',last_subdir(ncdir,1)])
%
%   ncfiles = sort(opendap_catalog(ncdir));
%   M       = nc_cf_harvest(ncfiles,'flat',0);
%   
%   nc_cf_harvest2xml([xmldir,'rijkswaterstaat_kustlidar_catalog1.xml'],M,...
%   'ID'                     ,'rijkswaterstaat/kustlidar',...
%   'name'                   ,'kustlidar',...
%   'publisher.name'         ,'Rijkswaterstaat',...
%   'publisher.contact.url'  ,'http://www.rws.nl',...
%   'publisher.contact.email','info@helpdeskwater.nl',...
%   'dataType'               ,'GRID',...
%   'documentation.summary'  ,'5 x 5 m2 grids of Lidar data',...
%   'documentation.title'    ,'Rijkswaterstaat',...
%   'documentation.url'      ,'http://www.rws.nl/water/scheepvaartberichten_waterdata/monitoring_meetsystemen/')
   
%% TIMESERIES

   d.name    = 'etmgeg'; 
   d.url     = 'http://www.knmi.nl/klimatologie/daggegevens/download.html';
   
   d.name    = 'potwind';
   d.url     = 'http://www.knmi.nl/klimatologie/onderzoeksgegevens/potentiele_wind/';

   ncdir    = ['http://dtvirt5.deltares.nl:8080/thredds/catalog/opendap/knmi/',d.name,'/catalog.html'];
   xmldir   =            ['F:\opendap.deltares.nl\thredds\dodsC\opendap\knmi\',d.name,'\'];

   disp(['Crawling ...',last_subdir(ncdir,1)])

   ncfiles = sort(opendap_catalog(ncdir));
   M       = nc_cf_harvest(ncfiles,'flat',0);
   
   nc_cf_harvest2xml([xmldir,d.name,'_catalog1.xml'],M,...
   'ID'                     ,['knmi/',d.name],...
   'name'                   ,d.name,...
   'publisher.name'         ,'KNMI',...
   'publisher.contact.url'  ,'http://www.knmi.nl',...
   'publisher.contact.email','',...
   'dataType'               ,'Station',...
   'documentation.summary'  ,'platform with meteo time series',...
   'documentation.title'    ,'KNMI',...
   'documentation.url'      ,d.url)
