%extract meta-data from dynamic catalog to populate meta-data in static catalog
%
%See also: nc_harvest

   ncdir    = 'http://dtvirt5.deltares.nl:8080/thredds/catalog/opendap/rijkswaterstaat/kustlidar/catalog.html';

   disp(['Crawling ...',last_subdir(ncdir,1)])

   ncfiles = opendap_catalog(ncdir);
   M       = nc_harvest(ncfiles,'flat',0);

   nc_harvest2xml([ncdir    ,'rijkswaterstaat_kustlidar_catalog1.xml'],M,...
   'ID'                     ,'rijkswaterstaat/kustlidar',...
   'name'                   ,'kustlidar',...
   'publisher.name'         ,'Rijkswaterstaat',...
   'publisher.contact.url'  ,'http://www.rws.nl',...
   'publisher.contact.email','info@helpdeskwater.nl',...
   'dataType'               ,'GRID',...
   'documentation.summary'  ,'5 x 5 m2 grids of Lidar data',...
   'documentation.title'    ,'Rijkswaterstaat',...
   'documentation.url'      ,'http://www.rws.nl/water/scheepvaartberichten_waterdata/monitoring_meetsystemen/')
   
% The static catalog is hosted at as test at:
% http://dtvirt5.deltares.nl:8080/thredds/rijkswaterstaat_kustlidar_catalog1.html
