# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Blueprint
import handlers


eco_api = Blueprint('eco_api', __name__)


@eco_api.route('/eco/institutes', methods=['GET'])
def eco_institutes_get():
    """
    It is handler for GET /eco/institutes
    """
    return handlers.eco_institutes_getHandler()


@eco_api.route('/eco/institutes/filters', methods=['GET'])
def eco_institutes_filters_get():
    """
    It is handler for GET /eco/institutes/filters
    """
    return handlers.eco_institutes_filters_getHandler()


@eco_api.route('/eco/measurements', methods=['GET'])
def eco_measurements_get():
    """
    It is handler for GET /eco/measurements
    """
    return handlers.eco_measurements_getHandler()


@eco_api.route('/eco/measurements/geojson', methods=['GET'])
def eco_measurements_geojson_get():
    """
    It is handler for GET /eco/measurements/geojson
    """
    return handlers.eco_measurements_geojson_getHandler()


@eco_api.route('/eco/measurements/filters', methods=['GET'])
def eco_measurements_filters_get():
    """
    It is handler for GET /eco/measurements/filters
    """
    return handlers.eco_measurements_filters_getHandler()


@eco_api.route('/eco/methods', methods=['GET'])
def eco_methods_get():
    """
    It is handler for GET /eco/methods
    """
    return handlers.eco_methods_getHandler()


@eco_api.route('/eco/methods/expand', methods=['GET'])
def eco_methods_expand_get():
    """
    It is handler for GET /eco/methods/expand
    """
    return handlers.eco_methods_expand_getHandler()


@eco_api.route('/eco/methods/filters', methods=['GET'])
def eco_methods_filters_get():
    """
    It is handler for GET /eco/methods/filters
    """
    return handlers.eco_methods_filters_getHandler()


@eco_api.route('/eco/parameterpackages', methods=['GET'])
def eco_parameterpackages_get():
    """
    It is handler for GET /eco/parameterpackages
    """
    return handlers.eco_parameterpackages_getHandler()


@eco_api.route('/eco/parameterpackages/expand', methods=['GET'])
def eco_parameterpackages_expand_get():
    """
    It is handler for GET /eco/parameterpackages/expand
    """
    return handlers.eco_parameterpackages_expand_getHandler()


@eco_api.route('/eco/parameterpackages/filters', methods=['GET'])
def eco_parameterpackages_filters_get():
    """
    It is handler for GET /eco/parameterpackages/filters
    """
    return handlers.eco_parameterpackages_filters_getHandler()


@eco_api.route('/eco/taxongroups', methods=['GET'])
def eco_taxongroups_get():
    """
    It is handler for GET /eco/taxongroups
    """
    return handlers.eco_taxongroups_getHandler()


@eco_api.route('/eco/taxongroups/filters', methods=['GET'])
def eco_taxongroups_filters_get():
    """
    It is handler for GET /eco/taxongroups/filters
    """
    return handlers.eco_taxongroups_filters_getHandler()


@eco_api.route('/eco/measurementpackages', methods=['GET'])
def eco_measurementpackages_get():
    """
    It is handler for GET /eco/measurementpackages
    """
    return handlers.eco_measurementpackages_getHandler()


@eco_api.route('/eco/measurementpackages/expand', methods=['GET'])
def eco_measurementpackages_expand_get():
    """
    It is handler for GET /eco/measurementpackages/expand
    """
    return handlers.eco_measurementpackages_expand_getHandler()


@eco_api.route('/eco/measurementpackages/filters', methods=['GET'])
def eco_measurementpackages_filters_get():
    """
    It is handler for GET /eco/measurementpackages/filters
    """
    return handlers.eco_measurementpackages_filters_getHandler()


@eco_api.route('/eco/exchangesystems', methods=['GET'])
def eco_exchangesystems_get():
    """
    It is handler for GET /eco/exchangesystems
    """
    return handlers.eco_exchangesystems_getHandler()


@eco_api.route('/eco/exchangesystems/filters', methods=['GET'])
def eco_exchangesystems_filters_get():
    """
    It is handler for GET /eco/exchangesystems/filters
    """
    return handlers.eco_exchangesystems_filters_getHandler()


@eco_api.route('/eco/monitoringnetworks', methods=['GET'])
def eco_monitoringnetworks_get():
    """
    It is handler for GET /eco/monitoringnetworks
    """
    return handlers.eco_monitoringnetworks_getHandler()


@eco_api.route('/eco/monitoringnetworks/expand', methods=['GET'])
def eco_monitoringnetworks_expand_get():
    """
    It is handler for GET /eco/monitoringnetworks/expand
    """
    return handlers.eco_monitoringnetworks_expand_getHandler()


@eco_api.route('/eco/monitoringnetworks/filters', methods=['GET'])
def eco_monitoringnetworks_filters_get():
    """
    It is handler for GET /eco/monitoringnetworks/filters
    """
    return handlers.eco_monitoringnetworks_filters_getHandler()


@eco_api.route('/eco/organisations', methods=['GET'])
def eco_organisations_get():
    """
    It is handler for GET /eco/organisations
    """
    return handlers.eco_organisations_getHandler()


@eco_api.route('/eco/organisations/filters', methods=['GET'])
def eco_organisations_filters_get():
    """
    It is handler for GET /eco/organisations/filters
    """
    return handlers.eco_organisations_filters_getHandler()


@eco_api.route('/eco/organisations/expand', methods=['GET'])
def eco_organisations_expand_get():
    """
    It is handler for GET /eco/organisations/expand
    """
    return handlers.eco_organisations_expand_getHandler()


@eco_api.route('/eco/parameters', methods=['GET'])
def eco_parameters_get():
    """
    It is handler for GET /eco/parameters
    """
    return handlers.eco_parameters_getHandler()


@eco_api.route('/eco/parameters/expand', methods=['GET'])
def eco_parameters_expand_get():
    """
    It is handler for GET /eco/parameters/expand
    """
    return handlers.eco_parameters_expand_getHandler()


@eco_api.route('/eco/parameters/filters', methods=['GET'])
def eco_parameters_filters_get():
    """
    It is handler for GET /eco/parameters/filters
    """
    return handlers.eco_parameters_filters_getHandler()


@eco_api.route('/eco/projects', methods=['GET'])
def eco_projects_get():
    """
    It is handler for GET /eco/projects
    """
    return handlers.eco_projects_getHandler()


@eco_api.route('/eco/projects/filters', methods=['GET'])
def eco_projects_filters_get():
    """
    It is handler for GET /eco/projects/filters
    """
    return handlers.eco_projects_filters_getHandler()


@eco_api.route('/eco/quantities', methods=['GET'])
def eco_quantities_get():
    """
    It is handler for GET /eco/quantities
    """
    return handlers.eco_quantities_getHandler()


@eco_api.route('/eco/quantities/expand', methods=['GET'])
def eco_quantities_expand_get():
    """
    It is handler for GET /eco/quantities/expand
    """
    return handlers.eco_quantities_expand_getHandler()


@eco_api.route('/eco/quantities/filters', methods=['GET'])
def eco_quantities_filters_get():
    """
    It is handler for GET /eco/quantities/filters
    """
    return handlers.eco_quantities_filters_getHandler()


@eco_api.route('/eco/standards', methods=['GET'])
def eco_standards_get():
    """
    It is handler for GET /eco/standards
    """
    return handlers.eco_standards_getHandler()


@eco_api.route('/eco/standards/filters', methods=['GET'])
def eco_standards_filters_get():
    """
    It is handler for GET /eco/standards/filters
    """
    return handlers.eco_standards_filters_getHandler()


@eco_api.route('/eco/notes', methods=['GET'])
def eco_notes_get():
    """
    It is handler for GET /eco/notes
    """
    return handlers.eco_notes_getHandler()


@eco_api.route('/eco/notes/filters', methods=['GET'])
def eco_notes_filters_get():
    """
    It is handler for GET /eco/notes/filters
    """
    return handlers.eco_notes_filters_getHandler()


@eco_api.route('/eco/parametertypes', methods=['GET'])
def eco_parametertypes_get():
    """
    It is handler for GET /eco/parametertypes
    """
    return handlers.eco_parametertypes_getHandler()


@eco_api.route('/eco/parametertypes/filters', methods=['GET'])
def eco_parametertypes_filters_get():
    """
    It is handler for GET /eco/parametertypes/filters
    """
    return handlers.eco_parametertypes_filters_getHandler()


@eco_api.route('/eco/taxontypes', methods=['GET'])
def eco_taxontypes_get():
    """
    It is handler for GET /eco/taxontypes
    """
    return handlers.eco_taxontypes_getHandler()


@eco_api.route('/eco/taxontypes/filters', methods=['GET'])
def eco_taxontypes_filters_get():
    """
    It is handler for GET /eco/taxontypes/filters
    """
    return handlers.eco_taxontypes_filters_getHandler()


@eco_api.route('/eco/units', methods=['GET'])
def eco_units_get():
    """
    It is handler for GET /eco/units
    """
    return handlers.eco_units_getHandler()


@eco_api.route('/eco/units/filters', methods=['GET'])
def eco_units_filters_get():
    """
    It is handler for GET /eco/units/filters
    """
    return handlers.eco_units_filters_getHandler()


@eco_api.route('/eco/compartments', methods=['GET'])
def eco_compartments_get():
    """
    It is handler for GET /eco/compartments
    """
    return handlers.eco_compartments_getHandler()


@eco_api.route('/eco/compartments/expand', methods=['GET'])
def eco_compartments_expand_get():
    """
    It is handler for GET /eco/compartments/expand
    """
    return handlers.eco_compartments_expand_getHandler()


@eco_api.route('/eco/compartments/filters', methods=['GET'])
def eco_compartments_filters_get():
    """
    It is handler for GET /eco/compartments/filters
    """
    return handlers.eco_compartments_filters_getHandler()


@eco_api.route('/eco/measurementobjects', methods=['GET'])
def eco_measurementobjects_get():
    """
    It is handler for GET /eco/measurementobjects
    """
    return handlers.eco_measurementobjects_getHandler()


@eco_api.route('/eco/measurementobjects/geojson', methods=['GET'])
def eco_measurementobjects_geojson_get():
    """
    It is handler for GET /eco/measurementobjects/geojson
    """
    return handlers.eco_measurementobjects_geojson_getHandler()


@eco_api.route('/eco/measurementobjects/expand', methods=['GET'])
def eco_measurementobjects_expand_get():
    """
    It is handler for GET /eco/measurementobjects/expand
    """
    return handlers.eco_measurementobjects_expand_getHandler()


@eco_api.route('/eco/measurementobjects/filters', methods=['GET'])
def eco_measurementobjects_filters_get():
    """
    It is handler for GET /eco/measurementobjects/filters
    """
    return handlers.eco_measurementobjects_filters_getHandler()
