%BCA2BCT_TEST     test script for BCA2BCT
%
%See also: BCA2BCT, BCT2BCA

H.period      = datenum(1999,05,06,0,[180:60:206040],0);
H.refdate     = datenum(1999,05,06);
H.latitude    = 52;

H.ncomponents = 35; % CHECK BCA FILE MANUALLY
bca2bct(['.\bct2bca_test\bct2bca_',         num2str(H.latitude),'noa0.bca'],...
        ['.\bct2bca_test\TMP_cas_t_predic_',num2str(H.latitude),'noa0.bct'],...
         '.\bct2bca_test\bca.bnd',H.period,...
                                  H.ncomponents,...
                                  H.refdate,'latitude',H.latitude);
                                  
H.ncomponents = 36; % CHECK BCA FILE MANUALLY
bca2bct(['.\bct2bca_test\bct2bca_',         num2str(H.latitude),'.bca'],...
        ['.\bct2bca_test\TMP_cas_t_predic_',num2str(H.latitude),'.bct'],...
         '.\bct2bca_test\bca.bnd',H.period,...
                                  H.ncomponents,...
                                  H.refdate,'latitude',H.latitude);                                  