function h=gelm_list(fig,cmdname,hInd,vInd,nLns,multisel,visible,enable,text1,cmd1);
if all(nargin~=[9 10]),
  error('Incorrect number of input parameters');
end;
coledit=gelm_col('edit');
if nargin==10,
  cmd1string=[cmdname,'(gcbf,',gui_str(cmd1),')'];
else,
  cmd1string='';
end;
vPos=gelm_vpos(vInd,nLns);
hPos=gelm_hpos(hInd,0);
h=uicontrol('visible',visible, ...
   'units','pixels','position',vPos+hPos, ...
   'style','listbox','backgroundcolor',coledit, ...
   'horizontalalignment','left', ...
   'max',logicalswitch(multisel,2,1),...
   'min',0,...
   'enable',enable, ...
   'callback',cmd1string, ...
   'parent',fig);
gelm_font(h);
set(h,'string',text1);
