function h=gelm_radiobutton(fig,cmdname,hInd,vInd,visible,enable,text1,cmd);
if all(nargin~=[7 8]),
  error('Incorrect number of input parameters');
end;
coltext=gelm_col('text');
if nargin==8,
  cmdstring=[cmdname,'(gcbf,',gui_str(cmd),')'];
else,
  cmdstring='';
end;
vPos=gelm_vpos(vInd);
hPos=gelm_hpos(0,hInd);
vPos(4)=18;
h=uicontrol('visible',visible, ...
   'units','pixels','position',vPos+hPos, ...
   'style','radiobutton','backgroundcolor',coltext, ...
   'horizontalalignment','left', ...
   'string',text1, ...
   'enable',enable, ...
   'buttondownfcn',cmdstring, ...
   'parent',fig);
gelm_font(h);
