function h=gelm_pushbutton(fig,cmdname,hInd,vInd,visible,enable,text1,cmd);
if all(nargin~=[7 8]),
  error('Incorrect number of input parameters');
end;
vPos=gelm_vpos(vInd);
hPos=gelm_hpos(hInd,0);
if nargin==8,
  cmdstring=[cmdname,'(gcbf,',gui_str(cmd),')'];
else,
  cmdstring='';
end;
h=uicontrol('visible',visible, ...
   'units','pixels','position',vPos+hPos, ...
   'style','pushbutton', ...
   'horizontalalignment','center', ...
   'string',text1, ...
   'enable',enable, ...
   'callback',cmdstring, ...
   'parent',fig);
gelm_font(h);
