function h=gelm_color(fig,cmdname,hInd,vInd,visible,enable,text1,color,cmd);
if all(nargin~=[8 9]),
  error('Incorrect number of input parameters');
end;
coltext=gelm_col('text');
if nargin==9,
  if strcmp(enable,'on'),
    cmdstring=[cmdname,'(gcbf,',gui_str(cmd),')'];
  else,
    cmdstring='';
  end;
else,
  cmdstring='';
end;
vPos=gelm_vpos(vInd);
hPos=gelm_hpos(hInd,2);
hPos(2)=hPos(2)+4;
hPos(4)=hPos(4)-8;
if 1, % Version 5.1: isunix,
  cb_or_bdf='callback';
  activestyle='pushbutton';
else,
  cb_or_bdf='buttondownfcn';
  activestyle='text';
end;
h(2)=uicontrol('visible',visible, ...
   'units','pixels', ...
   'position',vPos+hPos, ...
   'style',logicalswitch(isunix,'pushbutton','frame'), ...
   'backgroundcolor',color, ...
   'enable',enable, ...
   cb_or_bdf,cmdstring, ...
   'parent',fig);
hPos=gelm_hpos(hInd,1);
vPos(4)=18;
h(1)=uicontrol('visible',visible, ...
   'units','pixels', ...
   'position',vPos+hPos, ...
   'style',logicalswitch(isempty(cmdstring),'text',activestyle), ...
   'backgroundcolor',coltext, ...
   'horizontalalignment','right', ...
   'string',text1, ...
   cb_or_bdf,cmdstring, ...
   'enable',enable, ...
   'parent',fig);
gelm_font(h);
