function stochast = prob_quadratic_RS_concave_stochast_test()

stochast = struct(...
    'Name', {
        'U1'...
        'U2'...
    },...
    'Distr', {
        @norm_inv...
        @norm_inv...
    },...
    'Params', {
        {0 1}...
        {0 1}...
    },...
    'propertyName', {
        true...
        true...
    } ...
);