function handles=muppet_plotInteractivePolyline(handles,i,j,k)

plt=handles.figures(i).figure.subplots(j).subplot;
nr=plt.datasets(k).dataset.number;
data=handles.datasets(nr).dataset;
opt=plt.datasets(k).dataset;

usd=[i,j,k];

if opt.fillclosedpolygons
    facecolor=colorlist('getrgb','color',opt.fillcolor);
else
    facecolor='none';
end

h=gui_polyline('plot','x',data.x,'y',data.y,'tag','interactivepolyline','marker','o', ...
    'changecallback',@muppet_changeInteractivePolygon,'axis',gca, ...
    'markersize',opt.markersize,'markeredgecolor',colorlist('getrgb','color',opt.markeredgecolor), ...
    'markerfacecolor',colorlist('getrgb','color',opt.markerfacecolor), ...
    'linewidth',opt.linewidth,'linecolor',colorlist('getrgb','color',opt.linecolor),'linestyle',opt.linestyle, ...
    'facecolor',facecolor, ...
    'arrowthickness',opt.arrowthickness,'headthickness',opt.headthickness,'headlength',opt.headlength, ...
    'nrheads',opt.nrheads,'userdata',usd, ...
    'type',opt.polylinetype,'closed',0);

handles.figures(i).figure.subplots(j).subplot.datasets(k).dataset.handle=h;
