classdef example_classdef < oop.inspectable
    properties (Constant,Hidden)
        % Code template generated by calling metaprop.Template(metaprop.example_classdef)
        metaprops = metaprop.Construct(?metaprop.example_classdef,{
            'Date',@metaprop.date,{
                'Category','When'
                'Description','Date field'
                }
            'Number',@metaprop.doubleScalar,{
                'Category','What'
                'Description','A single double precision number greater than 1'
                'Attributes',{'>',1}
                }
            'Position',@metaprop.doubleRow,{
                'Category','What'
                'Description','4 element row vector'
                }
            });
    end
    properties
        Date = now()
        Number = 2
        Position = [1 2 3 4]
    end
    methods
        %% construcor
        function self = example_classdef
        end
        
        %% setter methods
        function set.Date  (self,value); self.metaprops.Date  .Check(value); self.Date   = value; end
        function set.Number(self,value); self.metaprops.Number.Check(value); self.Number = value; end
    end
end