% EXAMPLE_CLASSDEF a very simple class definition that works with metaprops
classdef example_classdef < oop.inspectable
    %% the block with meta props is first, so the details of the properies is immediatly visible
    % All properties decripeb by metaprops must be properties of the class
    properties (Constant,Hidden)
        % Code template generated by calling metaprop.Template('metaprop.example_classdef')
        metaprops = metaprop.Construct(mfilename('class'),{
            'Date',@metaprop.date,{
                'Category','When'
                'Description','Date field'
                }
            'Number',@metaprop.doubleScalar,{
                'Category','What'
                'Description','A single double precision number greater than 1'
                'Attributes',{'>',1}
                }
            'Position',@metaprop.doubleRow,{
                'Category','What'
                'Description','4 element row vector'
                }
            'Array',@metaprop.doubleArray2D,{
                'Category','What'
                'Description','5x5 array'
                }
            });
    end
    %% Declaration of the properties, these are the same as 
    properties
        Date = now()
        Number = 2
        Position = [1 2 3 4]
        Array = magic(5);
    end
    methods
        %% construcor
        function self = example_classdef
        end
        
        %% setter methods
        function set.Date  (self,value); self.metaprops.Date  .Check(value); self.Date   = value; end
        function set.Number(self,value); self.metaprops.Number.Check(value); self.Number = value; end
        function set.Array (self,value); self.metaprops.Array .Check(value); self.Array  = value; end
    end
end