function File = open(diafile,varargin)
%OPEN  scan internal blocks of DONAR dia file + aggregate into variables
%
% File = donar.open(diafile) opens a file and returns contents
% in structure File, where subfield Blocks contains meta-data per 
% internal block, and subfield Variables contains an aggregation
% of the blocks into unique variables. The DONAR codes are resolved
% for international nomenclature.
%
% 300 Mb files into 4000 blocks
% can take up to 10 min to open. For thsi reason a cache file is stored
% after each donar.open call, and this is used any next call. Set
% keyword cache to 0 to prevent writng and reading a cache (default 1).
%
% Example:
% 
%  File            = donar.open(diafile)
% [data, metadata] = donar.read(File,1,6) % 1st variable, residing in 6th column
%
%See also: open, read, disp

OPT.disp  = 100;
OPT.cache = 1;

OPT = setproperty(OPT,varargin);

cachefile = strrep(diafile,'.dia','_info.mat');
if exist(cachefile) & OPT.cache
   File        = load(cachefile);
   disp('Loading cache generated by a previous donar.open() call.')
else
   File.Blocks = donar.scan_file(diafile);
   if OPT.cache
   save(cachefile,'-struct','File')
   disp('Stored  cache for faster opening in future donar.open() call.')
   end
end

File.Filename = diafile;

% donar.scan_file
File.Variables = donar.merge_headers(File.Blocks);

if OPT.disp > 0
   disp([mfilename,' # of blocks = ',num2str(length(File.Blocks))])
   disp([mfilename,' # of values = ',num2str(sum([File.Blocks.nval]))])  
   disp([mfilename,' # of parameters = ',num2str(length(File.Variables))])  
end
