function [longname, cf_name] = resolve_ehd(code,varargin)
%RESOLVE_EHD convert donar units code to english long_name, CF UDUNITS units,...
%
%   [longname,cf_udunits] = resolve_ehd(code)
%
% Example: resolve_ehd('doC') = 'decidegree_Celsius'
%
% To be applied to field EHD{2} from donar.read_header().
%
%see also: resolve_wns, convert_units, 
% http://www.unidata.ucar.edu/software/udunits/udunits-2/udunits2.html#Introduction
% http://coastwatch.pfeg.noaa.gov/erddap/convert/units.html

% TO DO : add BODC SeaDataNet P6

if isnumeric(code)
   code = num2str(code);
end

DB = { ...
    '%'      ,'.01' ,'percent'; ...
    '/d'     ,'1/day','per day'; ...
    '/h'     ,'1/hour','per hour'; ...
    '/h/km'  ,'1/hour/km','per hour per kilometer'; ...
    '/km2'   ,'km^-2','per square kilometre'; ...
    '/l'     ,nan   ,'per litre'; ...
    '/m'     ,'m^-1','per metre'; ...
    '/m2'    ,'m^-2','per square metre'; ...
    '/mg'    ,nan   ,'per milligram'; ...
    '/ml'    ,nan   ,'per millilitre'; ...
    '1/m'    ,'1/m' ,'coefficient per meter'; ...
    'a'      ,nan   ,'year'; ...
    'B'      ,nan   ,'Beaufort'; ...
    'Bq/kg'  ,nan   ,'Becquerels per kilogram'; ...
    'Bq/m3'  ,nan   ,'Becquerels per cubic metre'; ...
    'c/s'    ,nan   ,'Counts per second'; ...
    'cm'     ,nan   ,'centimetre'; ...
    'cm/s'   ,nan   ,'centimetres per second'; ...
    'cm2'    ,nan   ,'square centimetre'; ...
    'cm2/Hz' ,nan   ,'square centimetres per Hertz'; ...
    'cm2s'   ,nan   ,'square centimetre second'; ...
    'coC'    ,nan   ,'centigrade Celsius'; ...
    'd'      ,nan   ,'day'; ...
    'dB'     ,nan   ,'Decibel'; ...
    'dBar'   ,nan   ,'deciBar'; ...
    'DIMSLS' ,'1'   ,'Dimensionless'; ...
    'dm'     ,nan   ,'decimetre'; ...
    'dm/s'   ,nan   ,'decimetres per second'; ...
    'dm3/s'  ,nan   ,'cubic decimetres per second'; ...
    'doC'    ,'decidegree_Celsius','decigrade Celsius'; ...
    'ds'     ,nan   ,'decisecond'; ...
    'FINDX'  ,nan   ,'F-index'; ...
    'FTU'    ,nan   ,'Formazine Turbidity Units'; ...
    'g'      ,'g'   ,'gram'; ...
    'g/a'    ,nan   ,'grams per year'; ...
    'g/d'    ,nan   ,'grams per day'; ...
    'g/kg'   ,nan   ,'grams per kilogram'; ...
    'g/m2'   ,nan   ,'grams per square metre'; ...
    'g/m3'   ,nan   ,'grams per cubic metre'; ...
    'g/s'    ,nan   ,'grams per second'; ...
    'graad'  ,nan   ,'degree'; ...
    'h'      ,nan   ,'hour'; ...
    'hPa'    ,nan   ,'hectoPascal'; ...
    'Hz'     ,nan   ,'Hertz'; ...
    'j'      ,'year','Year'; ...
    'JTU'    ,nan   ,'Jackson Turbidity Units'; ...
    'kg'     ,nan   ,'kilogram'; ...
    'kg/a'   ,nan   ,'kilograms per year'; ...
    'kg/km2' ,nan   ,'kilogram per quare meter'; ...
    'kg/m3'  ,nan   ,'kilograms per cubic metre'; ...
    'KHz'    ,nan   ,'kiloHertz'; ...
    'l'      ,nan   ,'litre'; ...
    'm'      ,nan   ,'metre'; ...
    'm/s'    ,nan   ,'metres per second'; ...
    'm2'     ,'m^2' ,'square metre'; ...
    'm3'     ,'m^3' ,'Cubic metre'; ...
    'm3/a'   ,nan   ,'cubic metres per year'; ...
    'm3/d'   ,nan   ,'cubic metres per day'; ...
    'm3/h'   ,nan   ,'cubic metres per hour'; ...
    'm3/s'   ,nan   ,'cubic metres per second'; ...
    'mBq/l'  ,nan   ,'milliBecquerels per litre'; ...
    'meq/l'  ,nan   ,'milli equivalent per liter'; ...
    'mg/g'   ,nan   ,'milligrams per gram'; ...
    'mg/kg'  ,nan   ,'milligrams per kilogram'; ...
    'mg/l'   ,'mg/l','milligrams per litre'; ...
    'mg/ml'  ,'mg/ml' ,'milligram per liter'; ...
    'mHz'    ,nan   ,'milliHertz'; ...
    'min'    ,nan   ,'minute'; ...
    'MJ/s'   ,nan   ,'megaJoule per second'; ...
    'ml'     ,nan   ,'per millilitre'; ...
    'ml/l'   ,nan   ,'millilitres per litre'; ...
    'mm'     ,'mm'  ,'millimetre'; ...
    'mm/h'   ,nan   ,'mm per hour'; ...
    'mm2'    ,nan   ,'square millimetre'; ...
    'mm3/l'  ,nan   ,'cubic millimetres per litre'; ...
    'mmol/l' ,nan   ,'millimol per liter'; ...
    'mnd'    ,nan   ,'month'; ...
    'mS/m'   ,'mS/m','milliSiemens per metre'; ...
    'ng/g'   ,nan   ,'nangram per liter'; ...
    'ng/kg'  ,nan   ,'nanongrams per kilogram'; ...
    'ng/l'   ,nan   ,'nanongrams per litre'; ...
    'ng/ml'  ,nan   ,'nanongrams per millilitre'; ...
    'nmol/mg',nan   ,'nanomol per milligram'; ...
    'NTU'    ,'NTU' ,'Nephelometric Turbidity Units'; ...
    'oC'     ,'degree_Celsius','degrees Celsius'; ...
    'oD'     ,nan   ,'German hardness grade'; ...
    'Pa'     ,nan   ,'Pascal'; ...
    'pmol/mg',nan   ,'picomol per milligram'; ...
    'PROMLE' ,'.001','PROMILLE'; ...
    'PtCo'   ,nan   ,'Pt-Co scale'; ...
    's'      ,nan   ,'second'; ...
    'S/m'    ,nan   ,'Siemens per metre'; ...
    't/a'    ,nan   ,'tons per year'; ...
    'tds'    ,nan   ,'Tonnes dry matter'; ...
    'TEQ'    ,nan   ,'Toxity Equivalents'; ...
    'TU'     ,nan   ,'Toxic Units'; ...
    'U'      ,'1'   ,'Unit'; ...
    'uE'     ,'microEinstein','microEinstein'; ... % An einstein is a unit defined as the energy in one mole (6.022×10^23) of photons, Avogadro's number times the energy of one photon of light
    'ug/g'   ,nan   ,'micrograms per gram'; ...
    'ug/kg'  ,nan   ,'micrograms per kilogram'; ...
    'ug/l'   ,nan   ,'micrograms per litre'; ...
    'um'     ,nan   ,'micrometre'; ...
    'um2'    ,nan   ,'square micrometre'; ...
    'us'     ,nan   ,'microsecond'; ...
};

cf_name       = DB{strcmpi(DB(:,1),code),2};
longname      = DB{strcmpi(DB(:,1),code),3};

%if isnan(udunits)
%   warning(['Not implemented yet:',code])
%end
