function Sout=multiline(Sin,varargin)
%MULTILINE Converts a string containing LineFeeds to a char matrix.
%   StrMat=MULTILINE(StrWithLF)
%   converts the input string with linefeeds (as generated by e.g.
%   the FPRINTF command when using \n in the format string) into
%   char matrix.
%
%   StrMat=MULTILINE(StrWithLF,cArray)
%   splits the input string at the characters listed in cArray.
%   Enter \n for char(10):linefeed and \t for char(9):tab.
%
%   ClStr=MULTILINE(...,'cell')
%   converts the input string into a cell string instead of a char
%   matrix.
%
%   For example
%
%      Str=multiline(sprintf('%i\n',1:10:31))
%
%   gives the 4 x 2 char matrix
%
%      Str = 1
%            11
%            21
%            31
%
%   See also CELLSTR, STR2MAT.

%   Copyright 2000-2009 Deltares, the Netherlands
%   http://www.delftsoftware.com
%   $Id$


error(sprintf('Missing p-file for %s, contact supplier of code.',mfilename))
