mte = mtestengine(...
    'maindir',fullfile(mctoolsroot,'matlab','applications','DUROS'),...
    'template','oet',...
    'targetdir',fullfile(mctoolsroot,'matlab','applications','DUROS','testbank','temptestresult'),...
    'recursive',true);

mte.catalogueTests;

mte.runAndPublish;