% mte = mtestengine(...
%     'maindir',fullfile(mctoolsroot,'matlab','applications','DUROS'),...
%     'template','oet',...
%     'targetdir',fullfile(mctoolsroot,'matlab','applications','DUROS','testbank','temptestresult'),...
%     'recursive',true);

mte = mtestengine(...
    'maindir',fullfile(openearthtoolsroot,'applications','DUROS'),...
    'template','oet',...
    'targetdir',fullfile(mctoolsroot,'matlab','applications','DUROS','testbank','temptestresult'),...
    'recursive',true);

mte.catalogueTests;

mte.tests(end+1) = mtest('roundoff_test');
mte.tests(end+1) = mtest('getCumVolume_test');
mte.tests(end+1) = mtest('getG_test');
mte.tests(end+1) = mtest('getBoundaryProfile_test');
mte.tests(end+1) = mtest('getParabolicProfile_test');
mte.maindir = 'f:\';

mte.runAndPublish;