function Handles=legend(Obj,Info),
Handles=[];

Position=Info.Pos;
Label=Info.Name;
FontSize=Info.Prm.FontSize;
xUnit=Info.Prm.xUnit;
yUnit=Info.Prm.yUnit;
Legend=Info.Legend;

H=handles(ob_ideas(Obj));
if isempty(H),
  Handles=[];
  return;
end;
ObjOptions=get(H(1),'userdata');

switch ObjOptions.Info.CMode,
case 'continuous',
  
  Handles=text(Position(1),Position(2),Label, ...
            'parent',Legend, ...
            'horizontalalignment','left', ...
            'verticalalignment','top', ...
            'fontunits','normalized', ...
            'fontsize',FontSize);
  
  CRange=md_clrmngr(tag(Obj));
  NColors=CRange(2)-CRange(1)+1;
  
  x=Position(1)+Position(3)*[0:NColors]/NColors; x=[x;x];
  y=Position(2)-FontSize*[1.2;1.8]*ones(1,NColors+1);
  Handles(2)=surface(x, ...
      y, ...
      ones(2,NColors+1), ...
      CRange(1):CRange(2), ...
      'facecolor','flat', ...
      'edgecolor','none', ...
      'cdatamapping','direct', ...
      'parent',Legend, ...
      'clipping','off');
  
  x=Position(1)+Position(3)*[0 0 1 1];
  y=Position(2)-FontSize*[1.2 1.8 1.8 1.2];
  Handles(3)=patch(x, ...
      y, ...
      2*ones(1,4), ...
      NaN, ...
      'facecolor','flat', ...
      'cdatamapping','direct', ...
      'parent',Legend, ...
      'clipping','off');
  
  Str=sprintf('%2.2f',ObjOptions.CLim(1));    
  Handles(4)=text(Position(1),Position(2)-2*FontSize,Str, ...
            'parent',Legend, ...
            'horizontalalignment','left', ...
            'verticalalignment','top', ...
            'fontunits','normalized', ...
            'fontsize',FontSize);
  
  Str=sprintf('%2.2f',ObjOptions.CLim(2));    
  Handles(5)=text(Position(1)+Position(3),Position(2)-2*FontSize,Str, ...
            'parent',Legend, ...
            'horizontalalignment','right', ...
            'verticalalignment','top', ...
            'fontunits','normalized', ...
            'fontsize',FontSize);

case 'classified',
  switch length(ObjOptions.Info.CThresholds),
  case 0,
    Handles=text(Position(1)+3*xUnit,Position(2),Label, ...
              'parent',Legend, ...
              'horizontalalignment','left', ...
              'verticalalignment','top', ...
              'fontunits','normalized', ...
              'fontsize',FontSize);
    
    CRange=md_clrmngr(tag(Obj));
    
    x=Position(1)+2*xUnit*[0.2 0.2 0.8 0.8];
    y=Position(2)-2*yUnit*[0.2 0.8 0.8 0.2];
    Handles(2)=patch(x,y,ones(1,4), ...
        CRange(1), ...
        'facecolor','flat', ...
        'edgecolor','none', ...
        'cdatamapping','direct', ...
        'parent',Legend, ...
        'clipping','off');
  otherwise,
    Handles=text(Position(1),Position(2),Label, ...
              'parent',Legend, ...
              'horizontalalignment','left', ...
              'verticalalignment','top', ...
              'fontunits','normalized', ...
              'fontsize',FontSize);
    
    CRange=md_clrmngr(tag(Obj));
    NColors=length(ObjOptions.Info.CThresholds)+1;
    
    x=Position(1)+Position(3)*[0:NColors]/NColors; x=[x;x];
    y=Position(2)-FontSize*[1.2;1.8]*ones(1,NColors+1);
    col=CRange(1)+(1:NColors)-1;
    col(isnan(ObjOptions.Info.CClassColors(:,1)))=NaN;
    
    Handles(2)=surface(x, ...
        y, ...
        ones(2,NColors+1), ...
        col, ...
        'facecolor','flat', ...
        'edgecolor','none', ...
        'cdatamapping','direct', ...
        'parent',Legend, ...
        'clipping','off');
    
    x=Position(1)+Position(3)*[0 0 1 1];
    y=Position(2)-FontSize*[1.2 1.8 1.8 1.2];
    Handles(3)=patch(x, ...
        y, ...
        2*ones(1,4), ...
        NaN, ...
        'facecolor','flat', ...
        'cdatamapping','direct', ...
        'parent',Legend, ...
        'clipping','off');
    % don't print '-\infty' and '\infty'
    for i=1:NColors-1,
      Str=sprintf('%2.2f',ObjOptions.Info.CThresholds(i));    
      Handles(3+i)=text(Position(1)+Position(3)*i/NColors,Position(2)-2*FontSize,Str, ...
              'parent',Legend, ...
              'horizontalalignment','center', ...
              'verticalalignment','top', ...
              'fontunits','normalized', ...
              'fontsize',FontSize);
    end;
  end;
end;