function h=gelm_text2(fig,cmdname,hInd,vInd,visible,enable,text1,text2,cmd1,cm2);
if all(nargin~=[8 9 10]),
  error('Incorrect number of input parameters');
end;
coltext=gelm_col('text');
if nargin==10,
  cmd1string=[cmdname,'(gcbf,',gui_str(cmd1),')'];
  cmd2string=[cmdname,'(gcbf,',gui_str(cmd2),')'];
elseif nargin==9,
  cmd1string='';
  cmd2string=[cmdname,'(gcbf,',gui_str(cmd1),')'];
else,
  cmd1string='';
  cmd2string='';
end;
vPos=gelm_vpos(vInd);
hPos=gelm_hpos(hInd,2);
vPos(4)=18;
if 1, % Version 5.1: isunix,
  cb_or_bdf='callback';
  activestyle='pushbutton';
else,
  cb_or_bdf='buttondownfcn';
  activestyle='text';
end;
h(2)=uicontrol('visible',visible, ...
   'units','pixels', ...
   'position',vPos+hPos, ...
   'style',logicalswitch(isempty(cmd2string),'text',activestyle), ...
   'backgroundcolor',coltext, ...
   'horizontalalignment','left', ...
   'string',text2, ...
   'enable',enable, ...
   cb_or_bdf,cmd2string, ...
   'parent',fig);
hPos=gelm_hpos(hInd,1);
h(1)=uicontrol('visible',visible, ...
   'units','pixels', ...
   'position',vPos+hPos, ...
   'style',logicalswitch(isempty(cmd1string),'text',activestyle), ...
   'backgroundcolor',coltext, ...
   'horizontalalignment','right', ...
   'string',text1, ...
   'enable',enable, ...
   cb_or_bdf,cmd1string, ...
   'parent',fig);
gelm_font(h);
