function h=gelm_text3(fig,cmdname,hInd,vInd,visible,enable,text1,text2,text3,cmd1,cmd2);
if all(nargin~=[9 10 11]),
  error('Incorrect number of input parameters');
end;
coltext=gelm_col('text');
if nargin==11,
  cmd3string=[cmdname,'(gcbf,',gui_str(cmd2),')'];
  cmd2string=[cmdname,'(gcbf,',gui_str(cmd1),')'];
  cmd1string='';
elseif nargin==10,
  cmd3string=[cmdname,'(gcbf,',gui_str(cmd1),')'];
  cmd2string='';
  cmd1string='';
else,
  cmd3string='';
  cmd2string='';
  cmd1string='';
end;
vPos=gelm_vpos(vInd);
hPos=gelm_hpos(hInd,2);
vPos(4)=18;
if 1, % Version 5.1: isunix,
  cb_or_bdf='callback';
  activestyle='pushbutton';
else,
  cb_or_bdf='buttondownfcn';
  activestyle='text';
end;
h(3)=uicontrol('visible',visible, ...
   'units','pixels', ...
   'position',vPos+hPos, ...
   'style',logicalswitch(isempty(cmd3string),'text',activestyle), ...
   'backgroundcolor',coltext, ...
   'horizontalalignment','left', ...
   'string',text3, ...
   'enable',enable, ...
   cb_or_bdf,cmd3string, ...
   'parent',fig);
hPos=gelm_hpos(hInd,4);
h(2)=uicontrol('visible',visible, ...
   'units','pixels', ...
   'position',vPos+hPos, ...
   'style',logicalswitch(isempty(cmd2string),'text',activestyle), ...
   'backgroundcolor',coltext, ...
   'horizontalalignment','right', ...
   'string',text2, ...
   'enable',enable, ...
   cb_or_bdf,cmd2string, ...
   'parent',fig);
hPos=gelm_hpos(hInd,3);
h(1)=uicontrol('visible',visible, ...
   'units','pixels', ...
   'position',vPos+hPos, ...
   'style',logicalswitch(isempty(cmd1string),'text',activestyle), ...
   'backgroundcolor',coltext, ...
   'horizontalalignment','left', ...
   'string',text1, ...
   'enable',enable, ...
   cb_or_bdf,cmd1string, ...
   'parent',fig);
gelm_font(h);
