function h=gelm_popupmenu1(fig,cmdname,hInd,vInd,visible,enable,text1list,text1,cmd);
if all(nargin~=[8 9]),
  error('Incorrect number of input parameters');
end;
coledit=gelm_col('edit');
if nargin==9,
  cmdstring=[cmdname,'(gcbf,',gui_str(cmd),')'];
else,
  cmdstring='';
end;
vPos=gelm_vpos(vInd);
hPos=gelm_hpos(hInd,0);
h=uicontrol('visible',visible, ...
   'units','pixels','position',vPos+hPos, ...
   'style','popupmenu','backgroundcolor',coledit, ...
   'horizontalalignment','left', ...
   'string',text1list, ...
   'enable',enable, ...
   'value',strmatch(text1,text1list,'exact'),...
   'callback',cmdstring, ...
   'parent',fig);
gelm_font(h);
