function h=gelm_popupcolor(fig,ax,cmdname,hInd,vInd,visible,enable,text1,text2list,text2,cmd);
if all(nargin~=[10 11]),
  error('Incorrect number of input parameters');
end;
coltext=gelm_col('text');
coledit=gelm_col('edit');
if nargin==11,
  cmdstring=[cmdname,'(gcbf,',gui_str(cmd),')'];
else,
  cmdstring='';
end;
vPos=gelm_vpos(vInd);
hPos=gelm_hpos(hInd,2);
Pos=hPos+vPos;
% position of color patch
cPos(4)=Pos(4); % height = characteristic height
cPos(3)=Pos(4); % width  = height
cPos(2)=Pos(2); % vertical offset unchanged
cPos(1)=Pos(1)+Pos(3)-cPos(3); % only right part of Pos

cPos(4)=cPos(2)+cPos(4)-4;
cPos(3)=cPos(1)+cPos(3);
cPos(2)=cPos(2)+4;
cPos(1)=cPos(1)+4;
if ischar(text2),
  color='none';
else,
  color=text2;
  text2='colorspec';
end;
h(3:4)=line( ...
   [cPos(1)   cPos(1)   cPos(3)   cPos(3)   cPos(1)   cPos(3)   cPos(1)   cPos(3)  ], ...
   [cPos(2)   cPos(4)   cPos(4)   cPos(2)   cPos(2)   cPos(4)   cPos(4)   cPos(2)  ], ...
   'color',[0 0 0], ...
   'visible',visible, ...
   'parent',ax); % draw cross
h(4)=patch( ...
   [cPos(1)   cPos(3)   cPos(3)   cPos(1)  ], ...
   [cPos(2)   cPos(2)   cPos(4)   cPos(4)  ], ...
   [1         1         1         1        ], ...
   1, ...
   'parent',ax, ...
   'facecolor',color, ...
   'visible',visible, ...
   'buttondownfcn',cmdstring);
Pos(3)=Pos(3)-Pos(4); % only left part of Pos
h(2)=uicontrol('visible',visible, ...
   'units','pixels','position',Pos, ...
   'style','popupmenu','backgroundcolor',coledit, ...
   'horizontalalignment','left', ...
   'string',text2list, ...
   'enable',enable, ...
   'value',strmatch(text2,text2list,'exact'),...
   'callback',cmdstring, ...
   'parent',fig);
hPos=gelm_hpos(hInd,1);
vPos(4)=18;
h(1)=uicontrol('visible',visible, ...
   'units','pixels','position',vPos+hPos, ...
   'style','text','backgroundcolor',coltext, ...
   'horizontalalignment','right', ...
   'string',text1, ...
   'enable',enable, ...
   'parent',fig);
gelm_font(h(1:2));
