function ddb_saveParams(handles)

T           = handles.model.xbeach.domain.tstop;
d50         = 0.0003;

xbModel = xb_generate_model(...
    'waves', ...
        {'Hm0', 1,...
        'Tp', 10,...
        'duration', T,...
        's', 20}, ...
    'tide',...
        { 'front', [0 1],...
        'back', [0 1],...
        'time', [0 T]}, ...
    'bathy',...
        {'x', handles.model.xbeach.domain.GridX',...
        'y', handles.model.xbeach.domain.GridY',...
        'rotate', false, ...
        'crop', false, ...
        'optimize', false, ...,...
        'z', handles.model.xbeach.domain.Depth'}, ...
    'settings', ...
        {'outputformat', 'netcdf', ...
        'random',0,...
        'thetanaut',handles.model.xbeach.domain.thetanaut,...
        'thetamin',handles.model.xbeach.domain.thetamin,...
        'thetamax',handles.model.xbeach.domain.thetamax,...
        'CFL', handles.model.xbeach.domain.CFL,...
        'dtheta',handles.model.xbeach.domain.dtheta,...
        'front', 'abs_2d', ...
        'back', 'abs_2d', ...
        'tstop', T, ...
        'tstart', 0,...
        'tintg', T/100,... 
	    'tintm', T/5,... 
        'D50', d50,...
        'D90', d50*1.5,...        
        'morfac', 1....
        'morstart', 0, ...
        'avalanching', handles.model.xbeach.domain.avalanching, ...
        'swave', handles.model.xbeach.domain.swave, ...
        'lwave', handles.model.xbeach.domain.lwave, ...
        'morphology', handles.model.xbeach.domain.morphology, ...
        'sedtrans', handles.model.xbeach.domain.sedtrans, ...
        'flow', handles.model.xbeach.domain.flow, ...
        'rho', handles.model.xbeach.domain.rho,...
        'g', handles.model.xbeach.domain.g,...
        'meanvar',          {'zb', 'zs', 'H'} ,...
        'globalvar',        {'zb', 'zs', 'H'}})      

    %% D. Write model input to dir
    xb_write_input('params.txt', xbModel);