function H=qp_uifigure(Name,closecom,tag,pos,callbackfcn)
%QP_UIFIGURE QP_UIFIGURE.

%   Copyright 2000-2008 Deltares, the Netherlands
%   http://www.delftsoftware.com
%   $Id$

Inactive=qp_settings('UIInActiveColor');%[0.5 0.5 1];%
%
if nargin<5
    callbackfcn='d3d_qp';
end
%
uicontrolfont = qp_fontsettings('DefaultUicontrolFont');
%
%Force onscreen:
%MATLAB 6: movegui(H,'onscreen')
screensize=get(0,'screensize');
pos(1:2)=max(pos(1:2),0);
pos(1:2)=min(pos(1:2),screensize(3:4)-pos(3:4)-[0 70]);
% -[0 70] added such that toolbar, menu and window title will be on screen
% also in R13 compiled mode
%
if ~isempty(closecom)
    closecom=sprintf('%s %s',callbackfcn,closecom);
end
%
H = figure('Visible','off', ...
    'DefaultUicontrolBackgroundColor',Inactive, ...
    'DefaultUicontrolForegroundColor',qp_settings('UIForeGroundColor'), ...
    uicontrolfont, ...
    'Units','pixels', ...
    'Color',Inactive, ...
    'IntegerHandle','off', ...
    'MenuBar','none', ...
    'Name',Name, ...
    'CloseRequestFcn',closecom, ...
    'NumberTitle','off', ...
    'Resize','off', ...
    'Position',pos, ...
    'Handlevisibility','off', ...
    'Tag',tag);
setappdata(H,'WL_UserInterface',1)
if versionnumber >= 7
    set(H,'WindowStyle','normal','DockControls','off')
end
