function ClsNames=ui_labels(OClsNames)
% UI_LABELS User interface to edit a list of label strings
%
%      NewLabels=ui_labels(OldLabels)
%
%      OldLabels should be a cell array of strings (cellstr),
%      or a string matrix. The output is always a cellstr.

% Nov 26th, 1999 - H.R.A. Jagers, WL | Delft Hydraulics

if ~iscellstr(OClsNames) & ~(ischar(OClsNames) & (ndim(OClsNames)==2)),
  error('Cell string expected as input');
else,
  OClsNames=cellstr(OClsNames);
  if isempty(OClsNames),
    ClsNames=OClsNames;
    return;
  end;
end;


ss=get(0,'screensize');

fig = figure('Color',[0.8 0.8 0.8], ...
	'HandleVisibility','off', ...
	'IntegerHandle','off', ...
	'MenuBar','none', ...
	'Name','Class manager', ...
	'NumberTitle','off', ...
	'Position',[20 ss(4)-285 230 235], ...
	'Resize','off', ...
	'Tag','Class manager for Matlab (c)');

lb = uicontrol('Parent',fig, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
	'Max',1, ...
	'Position',[10 60 210 165], ...
	'String',{''}, ...
	'Style','listbox', ...
	'Tag','varlist', ...
	'Value',1, ...
        'callback','set(gcbf,''userdata'',4)');
b = uicontrol('Parent',fig, ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'Position',[10 10 100 20], ...
	'String','reset', ...
	'Tag','reset', ...
        'callback','set(gcbf,''userdata'',3)');
b = uicontrol('Parent',fig, ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'Position',[120 10 100 20], ...
	'String','accept', ...
	'Tag','accept', ...
        'Callback','set(gcbf,''userdata'',2)');
ed = uicontrol('Parent',fig, ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'Style','edit', ...
	'Backgroundcolor',[1 1 1], ...
	'horizontalalignment','left', ...
	'Position',[10 35 210 20], ...
	'String','', ...
	'Tag','refresh', ...
        'Callback','set(gcbf,''userdata'',1)');
        
ClsNames=OClsNames;
NClsNames=ClsNames;
for i=1:length(ClsNames),
  NClsNames{i}=[sprintf('%3i: ',i) ClsNames{i}];
end;
set(lb,'string',NClsNames);
set(ed,'string',ClsNames{1});
while 1,
  if isempty(get(fig,'userdata')),
    waitfor(fig,'userdata');
  end;
  if ~ishandle(fig),
    break;
  end;
  Cmd=get(fig,'userdata');
  set(fig,'userdata',[]);
  if length(Cmd)==1,
    switch Cmd,
    case 1, % edit
      N=get(lb,'value');
      ClsNames{N}=get(ed,'string');
      NClsNames{N}=[sprintf('%3i: ',N) ClsNames{N}];
      nextval=min(N+1,length(ClsNames));
      set(lb,'string',NClsNames,'value',nextval);
      set(ed,'string',ClsNames{nextval});
    case 2, % accept
      break;
    case 3, % reset
      N=get(lb,'value');
      ClsNames{N}=OClsNames{N};
      NClsNames{N}=[sprintf('%3i: ',N) ClsNames{N}];
      set(lb,'string',NClsNames);
      set(ed,'string',ClsNames{N});
    case 4, % select
      N=get(lb,'value');
      set(ed,'string',ClsNames{N});
    end;
  end;
end;
delete(fig);

