function fig=xx_ui_ini(varargin),

XX=xx_constants;

%if isunix,
%  fontsize=12;
%else,
%  fontsize=8;
%end;

fig=figure('visible','off', ...
           'menu','none', ...
           'units','pixels', ...
           'color',XX.Clr.LightGray, ...
           'renderer','zbuffer', ...
           'inverthardcopy','off', ...
           'closerequestfcn','', ...
           'resize','off', ...
           'integerhandle','off', ...
           'numbertitle','off', ...
           'handlevisibility','off', ...
           'name','', ...
           'tag','IDEAS - GUI', ...
           'defaultuicontrolbackgroundcolor',XX.Clr.LightGray, ...
           varargin{:});

%           'defaulttextfontunits','pixels', ...
%           'defaulttextfontsize',fontsize, ...
%           'defaultuicontrolfontunits','pixels', ...
%           'defaultuicontrolfontsize',fontsize, ...
