function ncgen_mainFcn_test






readFcn     = @(OPT,writeFcn,fns) ncgen_readFcn_surface_xyz(OPT,writeFcn,fns);
writeFcn    = @(OPT,data,meta)    ncgen_writeFcn_surface(OPT,data,meta);
OPT         = ncgen_mainFcn(readFcn,writeFcn,'main.path_src',2);

dimstruct        = nccreateDimstruct('Name','x','Length',100);
dimstruct(end+1) = nccreateDimstruct('Name','y','Length',100);
dimstruct(end+1) = nccreateDimstruct('Name','time','Unlimited',true);
dimstruct(end+1) = nccreateDimstruct('Name','dim16','Length',16);
dimstruct(end+1) = nccreateDimstruct('Name','nSourcefiles','Unlimited',true,'Length',inf);
varstruct        = nccreateVarstruct_standardnames_cf('projection_x_coordinate',...
    'Name','x',...
    'Dimensions',{'x'});
varstruct(end+1) = nccreateVarstruct_standardnames_cf('projection_y_coordinate',...
    'Name','y',...
    'Dimensions',{'y'});
varstruct(end+1) = nccreateVarstruct_standardnames_cf('altitude',...
    'Name','z',...
    'Dimensions',{'x','y','time'},...
    'DeflateLevel',1,...
    'Datatype','double',...
    'scale_factor',[],...
    'add_offset',[]);
varstruct(end+1) = nccreateVarstruct_standardnames_cf('time',...
    'Name','time',...
    'Dimensions',{'time'},...
    'add_offset',datenum('1970-01-01 00:00:00'),...
    'Datatype','uint16',...
    'units',sprintf('days since %s ',datestr(0,31)));
varstruct(end+1) = nccreateVarstruct(...
    'Name','source_file_hash',...
    'Datatype','uint16',...
    'Dimensions',{'dim16','nSourcefiles'},...
    'Attributes',{'definition', 'MD5 hash of source files from which netcdf is generated'});


OPT.write.schema = nccreateSchema(dimstruct,varstruct);
var2evalstr(OPT)





OPT         = ncgen_mainFcn(readFcn,writeFcn,kmlFcn,OPT);
%%
OPT         = ncgen_mainFcn(readFcn,writeFcn,kmlFcn,'read.xid',2);

var2evalstr(OPT)

OPT.read.xis
