function OK = KML2kmz_test(varargin)
%KML2kmz_test   test for KML2kmz
%
%See also: KML2kmz

   % try various char /  cellstr combinations
   
   disp(['To generate data for ',mfilename,' :'])
   KMLcolorbar_test

   KML2kmz( KML_testdir('KMLcolorbar_test_2.kml'),...
            KML_testdir('KMLcolorbar_test_2_hor_bot.png'),...
            KML_testdir('KMLcolorbar_test_2_hor_top.png'),...
            KML_testdir('KMLcolorbar_test_2_ver_lft.png'),...
            KML_testdir('KMLcolorbar_test_2_ver_rgt.png'));

   KML2kmz({KML_testdir('KMLcolorbar_test_2.kml'),...
            KML_testdir('KMLcolorbar_test_2_hor_bot.png'),...
            KML_testdir('KMLcolorbar_test_2_hor_top.png'),...
            KML_testdir('KMLcolorbar_test_2_ver_lft.png'),...
            KML_testdir('KMLcolorbar_test_2_ver_rgt.png')});

   KML2kmz({KML_testdir('KMLcolorbar_test_2.kml'),...
            KML_testdir('KMLcolorbar_test_2_hor_bot.png'),...
            KML_testdir('KMLcolorbar_test_2_hor_top.png'),...
            KML_testdir('KMLcolorbar_test_2_ver_lft.png')},...
            KML_testdir('KMLcolorbar_test_2_ver_rgt.png')); %

   KML2kmz( KML_testdir('KMLcolorbar_test_2.kml'),... %
           {KML_testdir('KMLcolorbar_test_2_hor_bot.png'),...
            KML_testdir('KMLcolorbar_test_2_hor_top.png'),...
            KML_testdir('KMLcolorbar_test_2_ver_lft.png'),...
            KML_testdir('KMLcolorbar_test_2_ver_rgt.png')});

   KML2kmz( KML_testdir('KMLcolorbar_test_2.kml'),...%
            KML_testdir('KMLcolorbar_test_2_hor_bot.png'),...%
           {KML_testdir('KMLcolorbar_test_2_hor_top.png'),...
            KML_testdir('KMLcolorbar_test_2_ver_lft.png'),...
            KML_testdir('KMLcolorbar_test_2_ver_rgt.png')});

   KML2kmz({KML_testdir('KMLcolorbar_test_2.kml'),...
            KML_testdir('KMLcolorbar_test_2_hor_bot.png'),...
            KML_testdir('KMLcolorbar_test_2_hor_top.png')},...
            KML_testdir('KMLcolorbar_test_2_ver_lft.png'),...%
            KML_testdir('KMLcolorbar_test_2_ver_rgt.png'));%

   KML2kmz( KML_testdir('KMLcolorbar_test_2.kml'),...
            KML_testdir('KMLcolorbar_test_2_hor_bot.png'),...
            KML_testdir('KMLcolorbar_test_2_hor_top.png'),...
           {KML_testdir('KMLcolorbar_test_2_ver_lft.png'),...
            KML_testdir('KMLcolorbar_test_2_ver_rgt.png')});

   KML2kmz( KML_testdir('KMLcolorbar_test_2.kml'),...
            KML_testdir('KMLcolorbar_test_2_hor_bot.png'),...
            KML_testdir('KMLcolorbar_test_2_hor_top.png'),...
            KML_testdir('KMLcolorbar_test_2_ver_lft.png'),...
           {KML_testdir('KMLcolorbar_test_2_ver_rgt.png')});

   % check error check  
   try
      KML2kmz('a.kml','a.kml')
      OK = 0;
   catch
      OK = 1;
   end
   
