function varargout = KMLcolorbar(varargin)
%KMLCOLORBAR   make KML colorbar
%
%   kmlstring = kmlcolorbar(<keyword,value>) returns kml formatted string
%               kmlcolorbar(<keyword,value>) saves to kml file
%
% For the <keyword,value> pairs and their defaults call
%
%    OPT = KMLsurf()
%
% keyword 'colorbarlocation' specifies where to put colorbars. The first 
% colorbar in the list is shown by default, the other can be ticked. Useful 
% when multiple parameters with different colormaps are shown together in GE.
% Default: {'W'}, options: {'N','NNE','ENE','E','ESE','SSE','S','SSW','WSW','W','WNW','NNW'}
%
%See also: GOOGLEPLOT

%   --------------------------------------------------------------------
%   Copyright (C) 2009 Deltares for Building with Nature
%       Gerben de Boer
%
%       g.j.deboer@deltares.nl	
%
%       Deltares
%       P.O. Box 177
%       2600 MH Delft
%       The Netherlands
%
%   This library is free software: you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation, either version 3 of the License, or
%   (at your option) any later version.
%
%   This library is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
%
%   You should have received a copy of the GNU General Public License
%   along with this library.  If not, see <http://www.gnu.org/licenses/>.
%   --------------------------------------------------------------------

% This tool is part of <a href="http://OpenEarth.nl">OpenEarthTools</a>.
% OpenEarthTools is an online collaboration to share and manage data and 
% programming tools in an open source, version controlled environment.
% Sign up to recieve regular updates of this function, and to contribute 
% your own tools.

% $Id$
% $Date$
% $Author$
% $Revision$
% $HeadURL$
% $Keywords: $

%% Options

   OPT.colorMap           = [];
   OPT.clim               = [];

   OPT.bgcolor            = [100 155 100];  % background color to be made transparent
   OPT.fontrgb            = [1 1 1]; % white as Google letters
   OPT.name               = 'colorbar';
   OPT.fileName           = 'KMLcolorbar';
   OPT.colorbarlocation   = {'W'}; %{'N','E','S','W'}; %{'N','NNE','ENE','E','ESE','SSE','S','SSW','WSW','W','WNW','NNW'};
   OPT.halo               = 1;       % for colorbar add halo of pixels with different color as fontrgb
   OPT.halorgb            = [0 0 0]; % black as Google letters
   
   if nargin==0
     varargout = OPT;
     return
   end

   [OPT, Set, Default] = setProperty(OPT, varargin);   
   
%% make colorbar pngs as separate files

   [PATHSTR,NAME,EXT] = fileparts(OPT.fileName);
   
   if length((intersect({'NNW','N','NNE'},OPT.colorbarlocation)))>0   
   OPT.orientation        = 'horizontal';
   OPT.verticalalignment  = 'top';
   OPT.tipmargin          = 0.05; % prevent overlap between S and E colorbars
   OPT.alignmargin        = 0.03;
   OPT.thickness          = 0.013;
   OPT.fileName           = [fullfile(PATHSTR,NAME),'_hor_top'];
   KML_colorbar(OPT)
   end

   if length((intersect({'SSE','S','SSW'},OPT.colorbarlocation)))>0   
   OPT.orientation        = 'horizontal';
   OPT.verticalalignment  = 'bottom';
   OPT.tipmargin          = 0.05; % prevent overlap between S and E colorbars
   OPT.alignmargin        = 0.03;
   OPT.thickness          = 0.013;
   OPT.fileName           = [fullfile(PATHSTR,NAME),'_hor_bot'];
   KML_colorbar(OPT)
   end
    
   if length((intersect({'ENE','E','ESE'},OPT.colorbarlocation)))>0   
   OPT.orientation        = 'vertical';
   OPT.horizonalalignment = 'right';
   OPT.tipmargin          = 0.15; % prevent overlap with time ruler, google logo and N-rose
   OPT.alignmargin        = 0.01;
   OPT.thickness          = 0.01;
   OPT.fileName           = [fullfile(PATHSTR,NAME),'_ver_rgt'];
   KML_colorbar(OPT)
   end

   if length((intersect({'WSW','W','WNW'},OPT.colorbarlocation)))>0   
   OPT.orientation        = 'vertical';
   OPT.horizonalalignment = 'left';
   OPT.tipmargin          = 0.15; % prevent overlap with time ruler, google logo and N-rose
   OPT.alignmargin        = 0.01;
   OPT.thickness          = 0.01;
   OPT.fileName           = [fullfile(PATHSTR,NAME),'_ver_lft'];
   KML_colorbar(OPT)
   end

   OPT.fileName          =  fullfile(PATHSTR,NAME);

%% make associated kml code

   colorbarstring = sprintf([...
   '<Folder>\n'...
   ' <name>%s</name>\n'...
   ' <open>1</open>\n'],...
   OPT.name);
   
   if length((intersect({'S'},OPT.colorbarlocation)))>0
   
   loc  = 'S';
   bool = num2str(strcmpi(loc,OPT.colorbarlocation{1}));
   
   colorbarstring = [colorbarstring sprintf([...
   '  <Folder>\n'...
   '  <name>S</name>\n'...
   '  <ScreenOverlay>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x="1" y="1" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'],...
   bool,bool,.....
   [NAME,'_hor_bot'])];
   end
   if length((intersect({'SSW'},OPT.colorbarlocation)))>0
   
   loc  ='SSW';
   bool = num2str(strcmpi(loc,OPT.colorbarlocation{1}));
   
   colorbarstring = [colorbarstring sprintf([...
   '  <Folder>\n'...
   '  <name>SSW</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0." y="0.02" xunits="fraction" yunits="fraction"/>\n'... 
   '   <screenXY  x="0." y="0.02" xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x=".4" y="0.80" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'],...
   bool,bool,.....
   [NAME,'_hor_bot'])];
   end
   if length((intersect({'SSE'},OPT.colorbarlocation)))>0
   
   loc  ='SSE';
   bool = num2str(strcmpi(loc,OPT.colorbarlocation{1}));
   
   colorbarstring = [colorbarstring sprintf([...
   '  <Folder>\n'...
   '  <name>SSE</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="1." y="0.02" xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="1." y="0.02" xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x=".4" y="0.80" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'],...
   bool,bool,.....
   [NAME,'_hor_bot'])];
   end
   if length((intersect({'E'},OPT.colorbarlocation)))>0
   
   loc  ='E';
   bool = num2str(strcmpi(loc,OPT.colorbarlocation{1}));
   
   colorbarstring = [colorbarstring sprintf([...
   '<!--############################-->\n'...
   '  <Folder>\n'...
   '  <name>E</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x="1" y="1" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'],...
   bool,bool,.....
   [NAME,'_ver_rgt'])];
   end
   if length((intersect({'ENE'},OPT.colorbarlocation)))>0
   
   loc  ='ENE';
   bool = num2str(strcmpi(loc,OPT.colorbarlocation{1}));
   
   colorbarstring = [colorbarstring sprintf([...
   '  <Folder>\n'...
   '  <name>ENE</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0.99" y="1"    xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="0.99" y="1"    xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x="0.80" y="0.40" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'],...
   bool,bool,.....
   [NAME,'_ver_rgt'])];
   end
   if length((intersect({'ESE'},OPT.colorbarlocation)))>0
   
   loc  ='ESE';
   bool = num2str(strcmpi(loc,OPT.colorbarlocation{1}));
   
   colorbarstring = [colorbarstring sprintf([...
   '  <Folder>\n'...
   '  <name>ESE</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0.99" y="0"    xunits="fraction" yunits="fraction"/>\n'... 
   '   <screenXY  x="0.99" y="0"    xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x="0.80" y="0.40" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'],...
   bool,bool,.....
   [NAME,'_ver_rgt'])];
   end
   if length((intersect({'N'},OPT.colorbarlocation)))>0
   
   loc  ='N';
   bool = num2str(strcmpi(loc,OPT.colorbarlocation{1}));
   
   colorbarstring = [colorbarstring sprintf([...
   '<!--############################-->\n'...
   '  <Folder>\n'...
   '  <name>N</name>\n'...
   '  <ScreenOverlay>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x="1" y="1" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n',...
   '  </Folder>\n'],...
   bool,bool,.....
   [NAME,'_hor_top'])];
   end
   if length((intersect({'NNW'},OPT.colorbarlocation)))>0
   
   loc  ='NNW';
   bool = num2str(strcmpi(loc,OPT.colorbarlocation{1}));
   
   colorbarstring = [colorbarstring sprintf([...
   '  </Folder>\n'...
   '  <Folder>\n'...
   '  <name>NNW</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0." y="0.92" xunits="fraction" yunits="fraction"/>\n'... 
   '   <screenXY  x="0." y="0.92" xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x=".4" y="0.80" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'],...
   bool,bool,.....
   [NAME,'_hor_top'])];
   end
   if length((intersect({'NNE'},OPT.colorbarlocation)))>0
   
   loc  ='NNE';
   bool = num2str(strcmpi(loc,OPT.colorbarlocation{1}));
   
   colorbarstring = [colorbarstring sprintf([...
   '  <Folder>\n'...
   '  <name>NNE</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="1." y="0.98" xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="1." y="0.98" xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x=".4" y="0.80" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'],...
   bool,bool,.....
   [NAME,'_hor_top'])];
   end
   if length((intersect({'W'},OPT.colorbarlocation)))>0
   
   loc  ='W';
   bool = num2str(strcmpi(loc,OPT.colorbarlocation{1}));
   
   colorbarstring = [colorbarstring sprintf([...
   '<!--############################-->\n'...
   '  <Folder>\n'...
   '  <name>W</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>%s</visibility>\n'... 
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x="1" y="1" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'],...
   bool,bool,.....
   [NAME,'_ver_lft'])];
   end
   if length((intersect({'WNW'},OPT.colorbarlocation)))>0
   
   loc  ='WNW';
   bool = num2str(strcmpi(loc,OPT.colorbarlocation{1}));
   
   colorbarstring = [colorbarstring sprintf([...
   '  <Folder>\n'...
   '  <name>WNW</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0.01" y="1"    xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="0.01" y="1"    xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x="0.80" y="0.40" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'],...
   bool,bool,.....
   [NAME,'_ver_lft'])];
   end
   if length((intersect({'WSW'},OPT.colorbarlocation)))>0
   
   loc  ='WSW';
   bool = num2str(strcmpi(loc,OPT.colorbarlocation{1}));
   
   colorbarstring = [colorbarstring sprintf([...
   '  <Folder>\n'...
   '  <name>WSW</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>%s</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0.01" y="0"    xunits="fraction" yunits="fraction"/>\n'... 
   '   <screenXY  x="0.01" y="0"    xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x="0.80" y="0.40" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'],...
   bool,bool,.....
   [NAME,'_ver_lft'])];
   end

   colorbarstring = [colorbarstring sprintf([...
   '</Folder>'],...
   OPT.name)];

%% finish 

   if nargout==1
      varargout = {colorbarstring};
   else
      OPT.fid    = fopen([OPT.fileName,'.kml'],'w');
      OPT_header = struct(...
          'name',OPT.name,...
          'open',0);
      output = [KML_header(OPT_header) colorbarstring KML_footer];
      fprintf(OPT.fid,'%s',output);
      fclose(OPT.fid);
   end

%% EOF

