function varargout = KMLcolorbar(varargin)
%KMLCOLORBAR   make KML colorbar
%
%   kmlstring = kmlcolorbar(<keyword,value>) returns kml formatted string
%               kmlcolorbar(<keyword,value>) saves to kml file
%
%See also: GOOGLEPLOT

%   --------------------------------------------------------------------
%   Copyright (C) 2009 Deltares for Building with Nature
%       Gerben de Boer
%
%       g.j.deboer@deltares.nl	
%
%       Deltares
%       P.O. Box 177
%       2600 MH Delft
%       The Netherlands
%
%   This library is free software: you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation, either version 3 of the License, or
%   (at your option) any later version.
%
%   This library is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
%
%   You should have received a copy of the GNU General Public License
%   along with this library.  If not, see <http://www.gnu.org/licenses/>.
%   --------------------------------------------------------------------

% This tool is part of <a href="http://OpenEarth.nl">OpenEarthTools</a>.
% OpenEarthTools is an online collaboration to share and manage data and 
% programming tools in an open source, version controlled environment.
% Sign up to recieve regular updates of this function, and to contribute 
% your own tools.

% $Id$
% $Date$
% $Author$
% $Revision$
% $HeadURL$
% $Keywords: $

% TO DO: add also W and N colorbars

%% Options

   OPT.colorMap           = [];
   OPT.clim               = [];

   OPT.bgcolor            = [100 155 100];  % background color to be made transparent
   OPT.fontcolor          = 'w';
   OPT.name               = 'colorbar';
   OPT.fileName           = 'KMLcolorbar';
   
   if nargin==0
     varargout = OPT;
     return
   end

   [OPT, Set, Default] = setProperty(OPT, varargin);   
   
%% make colorbar pngs

   [PATHSTR,NAME,EXT] = fileparts(OPT.fileName);
    
   OPT.orientation        = 'horizontal';
   OPT.verticalalignment  = 'bottom';
   OPT.tipmargin          = 0.05; % prevent overlap between S and E colorbars
   OPT.alignmargin        = 0.03;
   OPT.thickness          = 0.013;
   OPT.fileName           = [fullfile(PATHSTR,NAME),'hor_bot'];
   KML_colorbar(OPT)
    
   OPT.orientation        = 'horizontal';
   OPT.verticalalignment  = 'top';
   OPT.tipmargin          = 0.05; % prevent overlap between S and E colorbars
   OPT.alignmargin        = 0.03;
   OPT.thickness          = 0.013;
   OPT.fileName           = [fullfile(PATHSTR,NAME),'hor_top'];
   KML_colorbar(OPT)

   OPT.orientation        = 'vertical';
   OPT.horizonalalignment = 'right';
   OPT.tipmargin          = 0.15; % prevent overlap with time ruler, google logo and N-rose
   OPT.alignmargin        = 0.01;
   OPT.thickness          = 0.01;
   OPT.fileName           = [fullfile(PATHSTR,NAME),'ver_rgt'];
   KML_colorbar(OPT)

   OPT.orientation        = 'vertical';
   OPT.horizonalalignment = 'left';
   OPT.tipmargin          = 0.15; % prevent overlap with time ruler, google logo and N-rose
   OPT.alignmargin        = 0.01;
   OPT.thickness          = 0.01;
   OPT.fileName           = [fullfile(PATHSTR,NAME),'ver_lft'];
   KML_colorbar(OPT)

    OPT.fileName          =  fullfile(PATHSTR,NAME);

%% make associated kml code

   colorbarstring = sprintf([...
   '<Folder>\n'...
   ' <name>%s</name>\n'...
   ' <open>1</open>\n'...
   '  <Folder>\n'...
   '  <name>S</name>\n'...
   '  <ScreenOverlay>\n'...
   '  <visibility>0</visibility>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="0" y="0" xunit ="fraction" yunits="fraction"/>\n'...
   '   <size      x="1" y="1" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'...
   '  <Folder>\n'...
   '  <name>SSW</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0." y="0.02" xunits="fraction" yunits="fraction"/>\n'... 
   '   <screenXY  x="0." y="0.02" xunit ="fraction" yunits="fraction"/>\n'...
   '   <size      x=".4" y="0.80" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'...
   '  <Folder>\n'...
   '  <name>SSE</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="1." y="0.02" xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="1." y="0.02" xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x=".4" y="0.80" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'...
   '<!--############################-->\n'...
   '  <Folder>\n'...
   '  <name>E</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="0" y="0" xunit ="fraction" yunits="fraction"/>\n'...
   '   <size      x="1" y="1" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'...
   '  <Folder>\n'...
   '  <name>ENE</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0.99" y="1" xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="0.99" y="1" xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x="0.80" y="0.40" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'...
   '  <Folder>\n'...
   '  <name>ESE</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0.99" y="0" xunits="fraction" yunits="fraction"/>\n'... 
   '   <screenXY  x="0.99" y="0" xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x="0.80" y="0.40" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'...
   '<!--############################-->\n'...
   '<!--############################-->\n'...
   '  <Folder>\n'...
   '  <name>N</name>\n'...
   '  <ScreenOverlay>\n'...
   '  <visibility>0</visibility>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="0" y="0" xunit ="fraction" yunits="fraction"/>\n'...
   '   <size      x="1" y="1" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'...
   '  <Folder>\n'...
   '  <name>NNW</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0." y="0.92" xunits="fraction" yunits="fraction"/>\n'... 
   '   <screenXY  x="0." y="0.92" xunit ="fraction" yunits="fraction"/>\n'...
   '   <size      x=".4" y="0.80" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'...
   '  <Folder>\n'...
   '  <name>NNE</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="1." y="0.98" xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="1." y="0.98" xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x=".4" y="0.80" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'...
    '<!--############################-->\n'...
   '  <Folder>\n'...
   '  <name>W</name>\n'...
   '  <visibility>1</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>1</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0" y="0" xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="0" y="0" xunit ="fraction" yunits="fraction"/>\n'...
   '   <size      x="1" y="1" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'...
   '  <Folder>\n'...
   '  <name>WNW</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0.01" y="1" xunits="fraction" yunits="fraction"/>\n'...
   '   <screenXY  x="0.01" y="1" xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x="0.80" y="0.40" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'...
   '  <Folder>\n'...
   '  <name>WSW</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <ScreenOverlay>\n'...
   '  <name>colorbar</name>\n'...
   '  <visibility>0</visibility>\n'...
   '  <Icon><href>%s.png</href></Icon>\n'...
   '   <overlayXY x="0.01" y="0" xunits="fraction" yunits="fraction"/>\n'... 
   '   <screenXY  x="0.01" y="0" xunits="fraction" yunits="fraction"/>\n'...
   '   <size      x="0.80" y="0.40" xunits="fraction" yunits="fraction"/>\n'...
   '  </ScreenOverlay>\n'...
   '  </Folder>\n'...
   ' </Folder>'],...
   OPT.name,[NAME,'hor_bot'],[NAME,'hor_bot'],[NAME,'hor_bot'],...
            [NAME,'ver_rgt'],[NAME,'ver_rgt'],[NAME,'ver_rgt'],...
            [NAME,'hor_top'],[NAME,'hor_top'],[NAME,'hor_top'],...
            [NAME,'ver_lft'],[NAME,'ver_lft'],[NAME,'ver_lft']);

   if nargout==1
      varargout = {colorbarstring};
   else
      OPT.fid    = fopen([OPT.fileName,'.kml'],'w');
      OPT_header = struct(...
          'name',OPT.name,...
          'open',0);
      output = [KML_header(OPT_header) colorbarstring KML_footer];
      fprintf(OPT.fid,'%s',output);
      fclose(OPT.fid);
   end

%%

