function nan=KMLscatter_test
%KMLscatter_test test for KMLscatter
%
%See also: googlePlot, KMLscatter, scatter, plotc

KMLscatter(linspace(53.10,53.75,21),linspace(4.75,8,21),linspace(-1,4,21),...
   'filename','scatter_test.kml',...
  'long_name','mud',...
      'units','percentage',...
'description','mud content derived from sediment size distribution curves in <a href="http://www.waddenzee.nl/Sedimentatlas.729.0.html"> Sediment Atlas WaddenZee </a>.',...
    'kmlname','mud content',...
       'clim',[0 3])