function [X Y Z alfa propertyVar] = XBeach_GridOrientation(xw, yw, Zbathy, varargin)

%% default properties
OPT = struct(...
    'dx', 2,...
    'dy', 2,...
    'xori', 0,...
    'yori', 0,...
    'xend_y0', [max(max(xw)) 0],...
    'x_yend', [0 max(max(yw))]);
% ,...
%     'xmax', max(max(xw)),...
%     'ymin', 0,...
%     'ymax', max(max(yw)));
% apply custom properties
OPT = setProperty(OPT, varargin{:});

% propertyVar = {...
%     'dx', OPT.dx,...
%     'dy', OPT.dy,...
%     'xori', OPT.xori,...
%     'yori', OPT.yori};
    
%%
%% show data, for selection
% figure(1);
% scatter(xw,yw,5,Zbathy,'filled');
% axis([min(xw)-.5*(max(xw)-min(xw)) ...
%     max(xw)+.5*(max(xw)-min(xw)) ...
%     min(yw)-.5*(max(yw)-min(yw)) ...
%     max(yw)+.5*(max(yw)-min(yw)) ])
% axis equal
% colorbar
% hold on
% 
% % Loop, picking up the points.
% disp('Click grid corner x=0,y=0')
% disp('Then click point x=xn,y=0')
% disp('Finally click to select extent of y')
% [xi yi] = ginput(3);
% plot(xi,yi,'r-o')
% xi = [max(xw) min(xw) min(xw)];
% yi = [max(yw) max(yw) min(yw)];
% xori = xi(1);
% yori = yi(1);
alfa = atan2(OPT.xend_y0(2)-OPT.yori, OPT.xend_y0(1)-OPT.xori);
Xbathy = cos(alfa)*(xw-OPT.xori)+sin(alfa)*(yw-OPT.yori);
Ybathy = -sin(alfa)*(xw-OPT.xori)+cos(alfa)*(yw-OPT.yori);
xn = cos(alfa)*(OPT.xend_y0(1)-OPT.xori)+sin(alfa)*(OPT.xend_y0(2)-OPT.yori);
yn = -sin(alfa)*(OPT.x_yend(1)-OPT.xori)+cos(alfa)*(OPT.x_yend(2)-OPT.yori);
xx = (0:OPT.dx:xn)';
yy = 0:OPT.dy:yn;
X = repmat(xx, 1, length(yy));
Y = repmat(yy, length(xx), 1);
Z = griddata(Xbathy,Ybathy,Zbathy,X,Y);

propertyVar = {...
    'dx', OPT.dx,...
    'dy', OPT.dy,...
    'xori', OPT.xori,...
    'yori', OPT.yori};

