function [] = copyd3dfiles(varargin)
% COPYD3DFILES(sourcepath,finalpath) copies all the necessary Delft3D model
% files to undertake a Flow - Wave simulation onine. SOURCEPATH is a string
% with the path that contains the files to be copied. FINAPATH is a string
% with the destination path.

if nargin ~=2
  error('MATLAB:copyd3dfiles:InputsError','Incorrect numbar of input arguments.'); 
else
  sourcepath = varargin{1};
  finalpath = varargin{2};
end

d3d_exts = {'*.bcc', ...
    '*.bch', ...
    '*.bnd', ...
    '*.dep', ...
    '*.enc', ...
    '*.grd', ...
    '*.ini', ...
    '*.mdf', ...
    '*.mdw', ...
    '*.mor', ...
    '*.sed', ...
    '*.sh', ...
    '*.txt'};

warning off, mkdir(finalpath); warning on
for i=1:1:length(d3d_exts)
    copyfile([sourcepath ,d3d_exts{i}], [finalpath]); 
end
