% Extended file input/output.
%
% NEFIS files; viewer selector equivalent.
%   vs_use       - Open/scan NEFIS file.
%   vs_disp      - Display file contents.
%   vs_let       - Read data from file (groups as columns).
%   vs_get       - Read data from file (groups as cells).
%   vs_find      - Find element in file.
%   vs_diff      - Compare NEFIS file contents.
%   vs_type      - Show type of NEFIS file.
%
% Grid files
%
%   grid2d       - Read Grid2D input files. (beta version)
%   wldep        - Read/write depth file.
%   wlenc        - Read/write grid enclosure file.
%   wlgrid       - Read/write GRD/RGF grid file.
%
% Tekal files
%
%   landboundary - Read/write landboundary file.
%   tekal        - Read/write Tekal data files.
%   tkl          - Read Tekal pct files. (beta version)
%
% Other related to Delft3D:
%
%   bct_io       - Read/write Delft3D Boundary Cond. Table (BCT) files.
%   delft3d      - Read data from Delft3D-MOR out-file. (SG/SUN/PC only)
%   mor_diag     - Read Delft3D-MOR mor-diag file.
%   morf         - Read Delft3D-MOR morf file (plots process tree).
%   qnhls        - Read/write Quickin HLS files.
%   read_mlb     - Read Matlab files generated by Viewer Selecter Interactive.
%   samples      - Read/write sample file.
%   trirst       - Read/write TRISULA restart file.
%   thd_io       - Read/write Delft3D thin dam file.
%
% Other related to WL software:
%
%   arcgrid      - Read/write arcgrid files.
%   areafile     - Read/write area files.
%   aukepc       - Read AUKE/pc files.
%   delwaq       - Read Delwaq HIS and MAP file.
%   fls          - Read data from FLS mdf/inc/his/bin/crs files.
%   histek       - Convert FLS bin file into his file.
%   mapper       - Read mapper files.
%   sbkcsv       - Read Sobek CSV file.
%   swanobst     - Write a swan obstacle file.
%
% Other interesting file formats
%
%   arcinfo      - Read ARC/INFO trees and E00 files. (beta version)
%   avs          - Read data from AVS inp and fld files.
%   cfx          - Read CFX dmp, geo and fo files.
%   dxf          - Read/write Autocad DXF files. (beta version)
%   mike         - Read Mike11/21 data files. (beta version)
%   readxwd      - Read xwd image files.
%   waqua        - Read data from Waqua SDS file. (beta version)
%   waquaio      - High level reading from Waqua SDS file. (beta version)
%
% Binary file
%   binary       - Display contents of a binary file as in a HEX editor.
%
% For more info contact Bert Jagers
