function [OPT, Set, Default] =knmi_noaapc2kml(noaapcfile,varargin)
%KNMI_NOAAPC2KML   PRELIMINRARY FUNCTION to save NOAAPC file as tiled kml png (BETA!!!)
%
%   knmi_noaapc2kml(noaapcfile,<keyword,value>)
%
% Note: for surf you must change reversePoly if the grid cells are too 
%       dark during the day, and light during the night.
%
% Example:
%
%    knmi_noaapc2kml('K010590N.SST','clim',[9 16]);
%
%See also: KMLfig2png, knmi_noaapc_read

   OPT.clim    = [9 16];
   
   directory   = 'D:\KNMI\mom\1990_mom\5\';
   
   noaapcfiles = {'K010590N.SST',...
                  'K020590A.SST',...
                  'K020590M.SST',...
                  'K020590N.SST',...
                  'K030590A.SST',...
                  'K030590M.SST',...
                  'K030590N.SST',...
                  'K030590O.SST',...
                  'K040590A.SST',...
                  'K040590M.SST',...
                  'K040590N.SST',...
                  'K040590O.SST',...
                  'K050590M.SST',...
                  'K050590N.SST',...
                  'K050590O.SST',...
                  'K060590M.SST',...
                  'K060590N.SST',...
                  'K060590O.SST',...
                  'K070590N.SST',...
                  'K080590A.SST',...
                  'K080590M.SST'};
   
%   [OPT, Set, Default] =setProperty(OPT,varargin{:});
%   
%   if nargin==0
%      return
%   end

for ifile=1:length(noaapcfiles)

   noaapcfile = noaapcfiles{ifile};
   
   disp(['Processing ',num2str(ifile)])
   
   D = knmi_noaapc_read([directory,filesep,noaapcfile],'landmask',nan);
   
   h = pcolorcorcen(D.loncor,D.latcor,D.data);
   colorbarwithtitle([D.producttex,' [',D.unitstex,']'])
   KMLfig2png(h,'fileName',[filename(noaapcfile),'.kml'],...
                 'kmlName',[D.product,' [',D.units,'] ',datestr(D.datenum,'yyyy-mmm-dd HH-MM-SS')],...
                 'levels',3); % sufficient for 1 km resolution 
                 
end
   
%% vectgorized inage is bad idea:
%  TOOOOOOOOOOOOOOO BIG (180 MB for whole North Sea)
   
   %KMLpcolor(D.loncor,D.latcor,D.data,...
   %          'fileName',[filename(noaapcfile),'.kml'],...
   %       'reversePoly',OPT.reversePoly,...
   %              'clim',OPT.clim,...
   %           'kmlName',[D.product,' [',D.units,']']);

%%EOF