%%KNMI_POTWIND2NC_TEST This is a first test to get wind timeseries into netcdf

OPT.fillvalue = 0; % NaNs do not work in netcdf API
D             = knmi_potwind('potwind_210_1981.txt','variables',OPT.fillvalue)
outputfile    = [filename(D.filename),'.nc'];

nc_create_empty (outputfile)

nc_add_dimension(outputfile, 'time', length(D.datenum))

V = struct(...
    'Name'     , 'datenum', ...
    'Nctype'   , 'float', ...
    'Dimension', {{'time'}}, ...
    'Attribute', struct('Name', 'Units', 'Value', 'days') ...
    );
nc_addvar(outputfile, V);
% nc_attput(outputfile, 'timezone', '_FillValue', );
% nc_attput(outputfile, 'referencedate', '_FillValue', );

V = struct(...
    'Name'     , 'wind_speed', ...
    'Nctype'   , 'float', ...
    'Dimension', {{'time'}}, ...
    'Attribute', struct('Name', 'Units', 'Value', 'm s-1') ...
    );
nc_addvar(outputfile, V);

V = struct(...
    'Name'     , 'wind_to_direction', ...
    'Nctype'   , 'float', ...
    'Dimension', {{'time'}}, ...
    'Attribute', struct('Name', 'Units', 'Value', 'degrees') ...
    );
nc_addvar(outputfile, V);
nc_attput(outputfile, 'wind_to_direction', '_FillValue', OPT.fillvalue);

nc_varput(outputfile, 'datenum'           , D.datenum.*24.*3600);
nc_varput(outputfile, 'wind_speed'        , D.UP);
nc_varput(outputfile, 'wind_to_direction' , D.DD); % does not work with NaNs.

