clear classes
close all
fclose all
clear
clc

excl = {'.svn',...
    'IterationTool',...
    'Numerical_Integration',...
    'Prob2B',...
    'Postprocessing',...
    'SensitivityAnalysis',...
    'SimpleProfile',...
    'batch',...
    'getVolume',...
    'getVolumeFast',...
    'plotVolume',...
    '_test',...
    'getG',...
    'Polygon',...
    'checkCrossShoreProfile',...
    'erosionPoint',...
    'plotDuneErosion',...
    'getRetreatDistance',...
    'findCrossings',...
    'testbank'};
maindirs =     {'F:\OpenEarthTools\matlab\applications\DUROS\',...
    'F:\McTools\matlab\mc_applications\mc_ucit\getDuneErosion\'};


tbd = tbdocumentation(...
    'maindir',maindirs,...
    'exclude',excl,...
    'templatename','simple',...
    'verbose',true);

tbd.targetdir = 'F:\m2htmldoc\docs';

tbd.listitems(1) = tblistitem(...
    'label','Test item1',...
    'icon','DeltaresLogo16.PNG',...
    'call','disp(''It WORKED!!!!'');');
tbd.listitems(2) = tblistitem(...
    'label','Test item2',...
    'icon','DeltaresLogo16.PNG',...
    'call','web http://www.deltares.nl -browser');

tbd.contentitems(1) = tbcontentitem(...
    'name','Test link 1',...
    'target','http://public.deltares.nl',...
    'icon','greencircleicon');
tbd.contentitems(2) = tbcontentitem(...
    'name','Test blank',...
    'target','',...
    'icon','greencircleicon');
tbd.contentitems(2).children = tbcontentitem(...
    'name','Test blank sub',...
    'target','',...
    'icon','greencircleicon');
tbd.contentitems(3) = tbcontentitem(...
    'name','fcnref',...
    'target','',...
    'icon','greencircleicon');

tbd.makedocumentation;