%% documentation generator for McTools
% This script generates the documentation for the OpenEarthTools toolbox. 
% It contains several steps:
% 
% # Initialization of the main generation object
% # Specification of the items that appear in the start menu
% # Specification of the items that appear in the contents menu of the help navigator
% # Generation of the documentation
% 
% These steps are further elaborated below.

%% Initialization of the main generation object
% Initialize the documentation object including some general attributes (or
% specifications:
%
% * _name_ The name of the toolbox
% * _targetdir_ is the directory in which the info.xml (main file for the documentation) is placed.
% * _icon_ specifies the image that should be showed as an icon for this toolbox in the start menu
% * _help_location_ specifies the directory name of the location where toc (table of content) files are placed.
% * _helpcontentmainpage_ is the main html page for the highest level in the toc
% * _includesearch_ specifies whether a searchdatabase must be built for this help documentation
% * _includecontents_ specifies whether this toolbox must be incorporated in the help navigator
% * _includeindex_ specifies whether an index file (for the help navigator) must be generated as well
% * _type_ specifies that this is a toolbox
% * _verbose_ indicates whether we want the progress of the generation written to the command window
%

toolboxdoc = tbdocumentation(...
    'name','OpenEarthTools',...
    'targetdir',fullfile(openearthtoolsroot,'matlab','docs','OpenEarthDocs'),...
    'icon',which('DeltaresLogo16.PNG'),...
    'help_location','oethelpdocs',...
    'helpcontentmainpage','http://public.deltares.nl/display/OET',...
    'includesearch',false,...
    'includecontents',true,...
    'includeindex',false,...
    'type','toolbox',...
    'verbose','off');

%% Specification of the items that appear in the start menu
% List items have three attributes:
% 
% # _label_ specifies the name of the list item
% # _callback_ specifies the action that has to be performed when the user clicks the item.
% # _icon_ specifies the location of the icon that should be used for this list item.
%
% We have a couple of list items:
%
% # *Help* starts the help navigator
% # *Edit personal config* opens the OET personal config file
% # *Edit Subversion config* opens the subversion config file
% # *Product Page (Web)* starts the webbrowser at the OpenEarthTools website
% # *Repository* starts the webbrowser and goes to the repository

% The Help item
toolboxdoc.listitems(1) = tblistitem(...
    'label','Help',...
    'call','web http://public.deltares.nl/display/OET -helpbrowser',...
    'icon','book_mat');

% The  Edit personal config item
toolboxdoc.listitems(2) = tblistitem(...
    'label','Edit personal config',...
    'call','edit(fullfile(getenv(''APPDATA''), ''OET'', ''config''))',...
    'icon','pageicon');

% The Edit Subversion config item
toolboxdoc.listitems(3) = tblistitem(...
    'label','Edit Subversion config',...
    'call','edit(fullfile(getenv(''APPDATA''), ''Subversion'', ''config''))',...
    'icon','pageicon');

% The Product Page (Web) item
toolboxdoc.listitems(4) = tblistitem(...
    'label','Product Page (Web)',...
    'call','web http://public.deltares.nl/display/OET -browser;',...
    'icon','webicon');

% The repository item
toolboxdoc.listitems(5) = tblistitem(...
    'label','Repository',...
    'call','web https://repos.deltares.nl/repos/OpenEarthTools/trunk/matlab -browser;',...
    'icon','webicon');

%% Specification of the items that appear in the contents menu of the help navigator
% The table of contents in the help navigator has several parts all having 
% their own references to the OpenEarthTools wiki:
%
% * *Getting Started*
% * *OpenEarthTools particitants*
% * *OpenEarth Data*
% * *OpenEarth Models*
% * *OpenEarth Tools*
% * *OpenEarth Tutorials
% 
% First the main items are created. The various parts will be dealt with 
% individually below, except for Tips and Tricks. This is just one item
%

% Getting Started
toolboxdoc.contentitems(1) = tbcontentitem(...
    'name','Getting started / Joining OpenEarth',...
    'target','http://public.deltares.nl/display/OET/Join+OpenEarth',...
    'icon','greencircleicon',...
    'children',tbcontentitem);

% OpenEarthTools particitants
toolboxdoc.contentitems(2) = tbcontentitem(...
    'name','OpenEarthTools participants',...
    'target','http://public.deltares.nl/display/OET',...
    'icon','pagesicon',...
    'children',tbcontentitem);

% OpenEarthData
toolboxdoc.contentitems(3) = tbcontentitem(...
    'name','Data',...
    'target','http://public.deltares.nl/display/OET/Data',...
    'icon','pagesicon',...
    'children',tbcontentitem);

% OpenEarthModels
toolboxdoc.contentitems(4) = tbcontentitem(...
    'name','Models',...
    'target','http://public.deltares.nl/display/OET/Models',...
    'icon','pagesicon',...
    'children',tbcontentitem);

% OpenEarthTools
toolboxdoc.contentitems(5) = tbcontentitem(...
    'name','Tools',...
    'target','http://public.deltares.nl/display/OET/Tools',...
    'icon','pagesicon',...
    'children',tbcontentitem);

% Tutorials
toolboxdoc.contentitems(6) = tbcontentitem(...
    'name','Tutorials',...
    'target','http://public.deltares.nl/display/OET/OpenEarth+tutorials',...
    'icon','pagesicon',...
    'children',tbcontentitem);

%%
% _*OpenEarthTools Participants*_
% This part contains of references to all participants in OpenEarth:
%
% # *Deltares* 
% # *Delft University of Technology - Hydraulic Engineering section*
% # *Delft University of Technology - Fluid Mechanics section*
% # *UNESCO-IHE*
% # *Delft Cluster - Northsea and Coast*
% # *Building with Nature*
% # *Micore*
%

% Deltares
toolboxdoc.contentitems(2).children(1) = tbcontentitem(...
    'name','Deltares',...
    'target','http://www.deltares.nl',...
    'icon','webicon');

% TU HE
toolboxdoc.contentitems(2).children(2) = tbcontentitem(...
    'name','TU Delft - Hydraulic Engineering',...
    'target','http://www.hydraulicengineering.tudelft.nl',...
    'icon','webicon');

% TU FM
toolboxdoc.contentitems(2).children(3) = tbcontentitem(...
    'name','TU Delft - Fluid Mechanics',...
    'target','http://www.fluidmechanics.tudelft.nl',...
    'icon','webicon');

% IHE
toolboxdoc.contentitems(2).children(4) = tbcontentitem(...
    'name','UNESCO - IHE',...
    'target','http://www.unesco-ihe.org/',...
    'icon','webicon');

% Delft Cluster
toolboxdoc.contentitems(2).children(5) = tbcontentitem(...
    'name','Delft Cluser - Northsea and Coast',...
    'target','http://www.delftcluster.nl/',...
    'icon','webicon');

% Building with Nature
toolboxdoc.contentitems(2).children(6) = tbcontentitem(...
    'name','Building with Nature',...
    'target','http://www.ecoshape.nl/',...
    'icon','webicon');

% Micore
toolboxdoc.contentitems(2).children(7) = tbcontentitem(...
    'name','Micore',...
    'target','http://www.micore.eu',...
    'icon','webicon');

%%
% _*OpenEarth Data*_
% This part contains of four references:
%
% # *Raw data repository*
% # *OpenDAP server*
% # *Data Standards* 
% # *Tutorials*
%

% Raw data repository
toolboxdoc.contentitems(3).children(1) = tbcontentitem(...
    'name','Raw data repository',...
    'target','http://repos.deltares.nl/repos/OpenEarthRawData/trunk/',...
    'icon','reficon');

% OpenDAP server
toolboxdoc.contentitems(3).children(2) = tbcontentitem(...
    'name','OpenDAP server',...
    'target','http://dtvirt5.deltares.nl:8080/thredds/catalog/opendap/catalog.html',...
    'icon','reficon');

% Data Standards
toolboxdoc.contentitems(3).children(3) = tbcontentitem(...
    'name','Data Standards',...
    'target','http://public.deltares.nl/display/OET/Data+Collection+Protocol',...
    'icon','pageicon');

% Tutorials
toolboxdoc.contentitems(3).children(4) = tbcontentitem(...
    'name','Tutorials',...
    'target','http://public.deltares.nl/display/OET/OpenEarth+tutorials',...
    'icon','pageicon');


%%
% _*OpenEarth Models*_
% This part contains references to model descriptions etc.:
%
% # *Models repository*
% # *Tutorials*
%

% Models repository
toolboxdoc.contentitems(4).children(1) = tbcontentitem(...
    'name','Models repository',...
    'target','http://repos.deltares.nl/repos/OpenEarthModels/trunk/',...
    'icon','reficon');

% Tutorials
toolboxdoc.contentitems(4).children(2) = tbcontentitem(...
    'name','Tutorials',...
    'target','http://public.deltares.nl/display/OET/OpenEarth+tutorials',...
    'icon','pageicon');

%%
% _*OpenEarth Tools*_
% This part has one main page and also lists the sprint sessions:
%
% # *Tools repository* 
% # *Tools standards*
% # *Tutorials*
%

% Tools repository
toolboxdoc.contentitems(5).children(1) = tbcontentitem(...
    'name','Tools repository',...
    'target','http://repos.deltares.nl/repos/OpenEarthTools/trunk/',...
    'icon','reficon');

% Tools standards
toolboxdoc.contentitems(5).children(2) = tbcontentitem(...
    'name','Tools standards',...
    'target','http://public.deltares.nl/display/OET/OpenEarth+tools+conventions',...
    'icon','pagesicon',...
    'children',tbcontentitem);
toolboxdoc.contentitems(5).children(2).children(1) = tbcontentitem(...
    'name','Matlab style guide',...
    'target','http://www.mathworks.com/matlabcentral/fileexchange/2529',...
    'icon','matlabicon');
toolboxdoc.contentitems(5).children(2).children(2) = tbcontentitem(...
    'name','Python style guide',...
    'target','http://www.python.org/dev/peps/pep-0008/',...
    'icon','webicon');

% Tutorials
toolboxdoc.contentitems(5).children(3) = tbcontentitem(...
    'name','Tutorials',...
    'target','http://public.deltares.nl/display/OET/OpenEarth+tutorials',...
    'icon','pageicon');

%% Generation of the documentation
% Execute the makedocumentation method of the tbtoolbox object. This
% invokes the generation of the necessery info.xml and helptoc.xml.
toolboxdoc.makedocumentation;

% This should not be created ==> TODO in tbdocumentation
rmdir(fullfile(openearthtoolsroot,'matlab','docs','OpenEarthDocs','oethelpdocs','html'),'s');