function D = t_tide_read(fname,varargin)
%t_tide_read   load ascii 'output' file as generated by t_tide
%
% D = t_tide_read(filename)
%
%See also: t_tide, textscan

%   --------------------------------------------------------------------
%   Copyright (C) 2010 Deltares
%       Gerben J. de Boer
%
%       gerben.deboer@deltares.nl	
%
%       Deltares
%       P.O. Box 177
%       2600 MH Delft
%       The Netherlands
%
%   This library is free software: you can redistribute it and/or
%   modify it under the terms of the GNU Lesser General Public
%   License as published by the Free Software Foundation, either
%   version 2.1 of the License, or (at your option) any later version.
%
%   This library is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%   Lesser General Public License for more details.
%
%   You should have received a copy of the GNU Lesser General Public
%   License along with this library. If not, see <http://www.gnu.org/licenses/>.
%   --------------------------------------------------------------------

% This tool is part of <a href="http://OpenEarth.nl">OpenEarthTools</a>.
% OpenEarthTools is an online collaboration to share and manage data and 
% programming tools in an open source, version controlled environment.
% Sign up to recieve regular updates of this function, and to contribute 
% your own tools.

%% Version <http://svnbook.red-bean.com/en/1.5/svn.advanced.props.special.keywords.html>
% $Id$
% $HeadURL$
% $Keywords: $

  %OPT.platform_id   = '';
   OPT.platform_name = '';
   OPT.lon           = [];
   OPT.lat           = [];

   OPT = setproperty(OPT,varargin);

   fid     = fopen(fname,'r');
      
%% meta

      tmp     = dir(fname);
      
      if length(tmp)==0
          error(['file not found "',fname,'"'])
      end
      D.name  = tmp.name;
      D.date  = tmp.date;
      D.bytes = tmp.bytes;

%% header
      
      for ii=1:16
         D.header{ii} = fgetl(fid);   
      end
  
      %-------------
      %
      %    file name: fname
      %    date: 01-Dec-2010
      %    nobs = 26281,  ngood = 26281,  record length (days) = 182.51
      %    start time: 01-Jan-1998
      %    rayleigh criterion = 1.0
      %    Greenwich phase computed with nodal corrections applied to amplitude \n and phase relative to center time
      %    
      %    x0= 5.97, x trend= 0
      %    
      %    var(x)= 3169321519.5862   var(xp)= 3053240866.7394   var(xres)= 115904582.427
      %    percent var predicted/var original= 96.3 %
      %    
      %         tidal amplitude and phase with 95% CI estimates
      %    
      %    tide   freq       amp     amp_err    pha    pha_err     snr
      % MM   0.0015122    0.0000  000.000   000.00   000.00        0
      % ...  
      % M8   0.3220456    0.0000  000.000   000.00   000.00        0
      %-------------
   
%% data

      C = textscan(fid,'%s%f%f%f%f%f%f');
        
      fclose(fid);
   
      D.data.name  = char(C{1});
     %D.data.significance    = cellfun(@(x) strcmp(x(1),'*'),D.component_name);
      D.data.significance    = D.data.name(:,1)=='*';
      D.data.name(D.significance,1) = ' ';
      D.data.name  = char(strtrim(cellstr(D.component_name)));
      
      D.data.frequency  = C{2};

      D.data.fmaj       = C{3};
      D.data.emaj       = C{4};
      D.data.pha        = C{5};
      D.data.epha       = C{6};

% implement velocities too

%     D.data.fmaj       = tidestruc.tidecon(:,1);D.name.fmaj = 'sema'           ;D.units.fmaj = OPT.units     ;D.long_name.fmaj = 'major ellipse axis of tidal component';
%     D.data.emaj       = tidestruc.tidecon(:,2);D.name.emaj = 'sema_error'     ;D.units.emaj = OPT.units     ;D.long_name.emaj = 'estimate of error of major ellipse axis of tidal component';
%     D.data.fmin       = tidestruc.tidecon(:,3);D.name.fmin = 'semi'           ;D.units.fmin = OPT.units     ;D.long_name.fmin = 'minor ellipse axis of tidal component';
%     D.data.emin       = tidestruc.tidecon(:,4);D.name.emin = 'semi_error'     ;D.units.emin = OPT.units     ;D.long_name.emin = 'estimate of error of minor ellipse axis of tidal component';
%     D.data.finc       = tidestruc.tidecon(:,5);D.name.finc = 'inc'            ;D.units.finc = 'degrees_true';D.long_name.finc = 'ellipse orientation';
%     D.data.einc       = tidestruc.tidecon(:,6);D.name.einc = 'inc_error'      ;D.units.einc = 'degrees_true';D.long_name.einc = 'estimate of error of ellipse orientation';
%     D.data.pha        = tidestruc.tidecon(:,7);D.name.pha  = 'phase'          ;D.units.pha  = 'degrees'     ;D.long_name.pha  = 'phase of tidal component';
%     D.data.epha       = tidestruc.tidecon(:,8);D.name.epha = 'phase_error'    ;D.units.epha = 'degrees'     ;D.long_name.epha = 'estimate of error of phase of tidal component';

      D.data.snr        = C{7};

      %%
     %D.name            = OPT.platform_id;  
      D.name            = OPT.platform_name;
      D.longitude       = OPT.lon;
      D.latitude        = OPT.lat;
