function xbSettings = xb_read_bcflist(filename, varargin)
%XB_READ_BCFLIST  Reads bcflist files generated by XBeach
%
%   Reads ebcflist or qbcflist files generated by XBeach. The files contain
%   references to other files containing realized wave and flux fields. The
%   referred files are read as well. The result is retruned in the form of
%   a XBeach structure.
%
%   Syntax:
%   xbSettings = xb_read_bcflist(filename, varargin)
%
%   Input:
%   filename    = filename of the ebcflist or qbcflist file to be read
%   varargin    = none
%
%   Output:
%   xbSettings  = XBeach structure array
%
%   Example
%   xbSettings = xb_read_bcflist(filename)
%
%   See also xb_read_waves

%% Copyright notice
%   --------------------------------------------------------------------
%   Copyright (C) 2010 Deltares
%       Bas Hoonhout
%
%       bas.hoonhout@deltares.nl	
%
%       Rotterdamseweg 185
%       2629HD Delft
%
%   This library is free software: you can redistribute it and/or
%   modify it under the terms of the GNU Lesser General Public
%   License as published by the Free Software Foundation, either
%   version 2.1 of the License, or (at your option) any later version.
%
%   This library is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%   Lesser General Public License for more details.
%
%   You should have received a copy of the GNU Lesser General Public
%   License along with this library. If not, see <http://www.gnu.org/licenses/>.
%   --------------------------------------------------------------------

% This tool is part of <a href="http://OpenEarth.nl">OpenEarthTools</a>.
% OpenEarthTools is an online collaboration to share and manage data and 
% programming tools in an open source, version controlled environment.
% Sign up to recieve regular updates of this function, and to contribute 
% your own tools.

%% Version <http://svnbook.red-bean.com/en/1.5/svn.advanced.props.special.keywords.html>
% Created: 24 Nov 2010
% Created with Matlab version: 7.9.0.529 (R2009b)

% $Id$
% $Date$
% $Author$
% $Revision$
% $HeadURL$
% $Keywords: $

%% read options

OPT = struct( ...
);

OPT = setproperty(OPT, varargin{:});

%% read bcf list

if ~exist(filename, 'file')
    error(['File does not exist [' filename ']'])
end

tlength = 1;

fdir = fileparts(filename);

[bcendtime rt dt trep mainang data] = deal([]);
filenames = {};

fid = fopen(filename);
while ~feof(fid)
    fline = fgetl(fid);
    if isempty(fline); continue; end;

    [bcendtime(tlength) rt(tlength) dt(tlength) trep(tlength) mainang(tlength) fname] = ...
        strread(fline, '%f%f%f%f%f%s\n', 'delimiter', ' ');

    fname = fullfile(fdir, [fname{:}]);
    filenames = [filenames {fname}];
    
    data(:,:,:,tlength) = read_bcf(fname);
    
    tlength = tlength+1;
end
fclose(fid);

%% create xbeach struct

xbSettings = xb_empty();
xbSettings = xb_set(xbSettings, '-units', 'time', {bcendtime 's'}, 'duration', {rt 's'}, ...
    'timestep', {dt 's'}, 'Trep', {trep 's'}, 'main_angle', {mainang 'degrees'}, ...
    'data', {data 'J/m^2'});
xbSettings = xb_meta(xbSettings, mfilename, 'boundaryconditions', [{filename} filenames]);

%% private functions %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function data = read_bcf(filename)

fdir = fileparts(filename);

% determine dimensions
dims = xb_read_dims(fdir);

% read file
fid = fopen(filename, 'r');

data = nan([dims.ny+1 dims.ntheta dims.nt+4]);

for i = 1:dims.nt+4
    data(:,:,i) = fread(fid, [dims.ny+1 dims.ntheta], 'double');
end

fclose(fid);